///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BankModelData {
/*
{
  "banks": [
    "BANK BRI"
  ]
} 
*/

  List<String?>? banks;

  BankModelData({
    this.banks,
  });
  BankModelData.fromJson(Map<String, dynamic> json) {
    if (json['banks'] != null) {
      final v = json['banks'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      banks = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (banks != null) {
      final v = banks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['banks'] = arr0;
    }
    return data;
  }
}

class BankModel {
/*
{
  "success": true,
  "data": {
    "banks": [
      "BANK BRI"
    ]
  },
  "message": "success"
} 
*/

  bool? success;
  BankModelData? data;
  String? message;

  BankModel({
    this.success,
    this.data,
    this.message,
  });
  BankModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? BankModelData.fromJson(json['data']) : null;
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['Message'] = message;
    return data;
  }
}
