///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DokumenModelData {
/*
{
  "url": "https://dev.chatourtravel.id/storage/document/certificate-266527412.pdf"
} 
*/

  String? url;

  DokumenModelData({
    this.url,
  });
  DokumenModelData.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    return data;
  }
}

class DokumenModel {
/*
{
  "success": true,
  "data": {
    "url": "https://dev.chatourtravel.id/storage/document/certificate-266527412.pdf"
  },
  "message": "success"
} 
*/

  bool? success;
  DokumenModelData? data;
  String? message;

  DokumenModel({
    this.success,
    this.data,
    this.message,
  });
  DokumenModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data =
        (json['data'] != null) ? DokumenModelData.fromJson(json['data']) : null;
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['Message'] = message;
    return data;
  }
}
