///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProfileModelData {
/*
{
  "id": "",
  "name": "Agen Demo 1",
  "email": "agen_demo1@demo.com",
  "photo": "https://dev.chatourtravel.id/chatour/media/image-no.jpg",
  "nik": "",
  "address": "",
  "city": "",
  "postal_code": "",
  "province": "",
  "district": "",
  "subdistrict": "",
  "phone": "",
  "fax": "",
  "gender": 1,
  "npwp": "",
  "member_no": "",
  "birth_date": "2000-01-01",
  "birth_place": "Surabaya",
  "bank_account": "",
  "bank_name": "",
  "bank_account_name": "",
  "country": "null",
  "partner_level_id": "null",
  "photo_path": "https://dev.chatourtravel.id/chatour/media/image-no.jpg",
  "sales": "null",
  "signature_attachment": "",
  "status": "",
  "balance": 0,
  "subagent_count": 0,
  "jamaah_count": 0
} 
*/

  String? id;
  String? name;
  String? email;
  String? photo;
  String? nik;
  String? address;
  String? city;
  String? cityId;
  String? postalCode;
  String? province;
  String? provinceId;
  String? district;
  String? subdistrict;
  String? subdistrictId;
  String? phone;
  String? fax;
  int? gender;
  String? npwp;
  String? memberNo;
  String? birthDate;
  String? birthPlace;
  String? bankAccount;
  String? bankName;
  String? bankAccountName;
  String? country;
  String? partnerLevelId;
  String? photoPath;
  String? sales;
  String? signatureAttachment;
  String? status;
  int? balance;
  int? subagentCount;
  int? jamaahCount;

  ProfileModelData({
    this.id,
    this.name,
    this.email,
    this.photo,
    this.nik,
    this.address,
    this.city,
    this.postalCode,
    this.province,
    this.district,
    this.subdistrict,
    this.phone,
    this.fax,
    this.gender,
    this.npwp,
    this.memberNo,
    this.birthDate,
    this.birthPlace,
    this.bankAccount,
    this.bankName,
    this.bankAccountName,
    this.country,
    this.partnerLevelId,
    this.photoPath,
    this.sales,
    this.signatureAttachment,
    this.status,
    this.balance,
    this.subagentCount,
    this.jamaahCount,
  });
  ProfileModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    photo = json['photo']?.toString();
    nik = json['nik']?.toString();
    address = json['address']?.toString();
    city = json['city']?.toString();
    cityId = json['city_id']?.toString();
    postalCode = json['postal_code']?.toString();
    province = json['province']?.toString();
    provinceId = json['province_id']?.toString();
    district = json['district']?.toString();
    subdistrict = json['subdistrict']?.toString();
    subdistrictId = json['subdistrict_id']?.toString();
    phone = json['phone']?.toString();
    fax = json['fax']?.toString();
    gender = json['gender']?.toInt();
    npwp = json['npwp']?.toString();
    memberNo = json['member_no']?.toString();
    birthDate = json['birth_date']?.toString();
    birthPlace = json['birth_place']?.toString();
    bankAccount = json['bank_account']?.toString();
    bankName = json['bank_name']?.toString();
    bankAccountName = json['bank_account_name']?.toString();
    country = json['country']?.toString();
    partnerLevelId = json['partner_level_id']?.toString();
    photoPath = json['photo_path']?.toString();
    sales = json['sales']?.toString();
    signatureAttachment = json['signature_attachment']?.toString();
    status = json['status']?.toString();
    balance = json['balance']?.toInt();
    subagentCount = json['subagent_count']?.toInt();
    jamaahCount = json['jamaah_count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['photo'] = photo;
    data['nik'] = nik;
    data['address'] = address;
    data['city'] = city;
    data['city_id'] = cityId;
    data['postal_code'] = postalCode;
    data['province'] = province;
    data['province_id'] = provinceId;
    data['district'] = district;
    data['subdistrict'] = subdistrict;
    data['subdistrict_id'] = subdistrictId;
    data['phone'] = phone;
    data['fax'] = fax;
    data['gender'] = gender;
    data['npwp'] = npwp;
    data['member_no'] = memberNo;
    data['birth_date'] = birthDate;
    data['birth_place'] = birthPlace;
    data['bank_account'] = bankAccount;
    data['bank_name'] = bankName;
    data['bank_account_name'] = bankAccountName;
    data['country'] = country;
    data['partner_level_id'] = partnerLevelId;
    data['photo_path'] = photoPath;
    data['sales'] = sales;
    data['signature_attachment'] = signatureAttachment;
    data['status'] = status;
    data['balance'] = balance;
    data['subagent_count'] = subagentCount;
    data['jamaah_count'] = jamaahCount;
    return data;
  }
}

class ProfileModel {
/*
{
  "success": true,
  "data": {
    "id": "",
    "name": "Agen Demo 1",
    "email": "agen_demo1@demo.com",
    "photo": "https://dev.chatourtravel.id/chatour/media/image-no.jpg",
    "nik": "",
    "address": "",
    "city": "",
    "postal_code": "",
    "province": "",
    "district": "",
    "subdistrict": "",
    "phone": "",
    "fax": "",
    "gender": 1,
    "npwp": "",
    "member_no": "",
    "birth_date": "2000-01-01",
    "birth_place": "Surabaya",
    "bank_account": "",
    "bank_name": "",
    "bank_account_name": "",
    "country": "null",
    "partner_level_id": "null",
    "photo_path": "https://dev.chatourtravel.id/chatour/media/image-no.jpg",
    "sales": "null",
    "signature_attachment": "",
    "status": "",
    "balance": 0,
    "subagent_count": 0,
    "jamaah_count": 0
  },
  "message": "success"
} 
*/

  bool? success;
  ProfileModelData? data;
  String? message;

  ProfileModel({
    this.success,
    this.data,
    this.message,
  });
  ProfileModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data =
        (json['data'] != null) ? ProfileModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
