///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TurbineDetailModelDataDetailDataUpperD {
/*
{
  "1": 55,
  "2": 55,
  "3": 55
} 
*/

  int? the1;
  int? the2;
  int? the3;

  TurbineDetailModelDataDetailDataUpperD({
    this.the1,
    this.the2,
    this.the3,
  });
  TurbineDetailModelDataDetailDataUpperD.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toInt();
    the2 = json['2']?.toInt();
    the3 = json['3']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    return data;
  }
}

class TurbineDetailModelDataDetailDataUpperC {
/*
{
  "1": 46,
  "2": 46,
  "3": 46
} 
*/

  int? the1;
  int? the2;
  int? the3;

  TurbineDetailModelDataDetailDataUpperC({
    this.the1,
    this.the2,
    this.the3,
  });
  TurbineDetailModelDataDetailDataUpperC.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toInt();
    the2 = json['2']?.toInt();
    the3 = json['3']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    return data;
  }
}

class TurbineDetailModelDataDetailDataUpperB {
/*
{
  "1": 48,
  "2": 48,
  "3": 48
} 
*/

  int? the1;
  int? the2;
  int? the3;

  TurbineDetailModelDataDetailDataUpperB({
    this.the1,
    this.the2,
    this.the3,
  });
  TurbineDetailModelDataDetailDataUpperB.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toInt();
    the2 = json['2']?.toInt();
    the3 = json['3']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    return data;
  }
}

class TurbineDetailModelDataDetailDataUpperA {
/*
{
  "1": 50,
  "2": 50,
  "3": 50
} 
*/

  int? the1;
  int? the2;
  int? the3;

  TurbineDetailModelDataDetailDataUpperA({
    this.the1,
    this.the2,
    this.the3,
  });
  TurbineDetailModelDataDetailDataUpperA.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toInt();
    the2 = json['2']?.toInt();
    the3 = json['3']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    return data;
  }
}

class TurbineDetailModelDataDetailDataUpper {
/*
{
  "A": {
    "1": 50,
    "2": 50,
    "3": 50
  },
  "B": {
    "1": 48,
    "2": 48,
    "3": 48
  },
  "C": {
    "1": 46,
    "2": 46,
    "3": 46
  },
  "D": {
    "1": 55,
    "2": 55,
    "3": 55
  }
} 
*/

  TurbineDetailModelDataDetailDataUpperA? A;
  TurbineDetailModelDataDetailDataUpperB? B;
  TurbineDetailModelDataDetailDataUpperC? C;
  TurbineDetailModelDataDetailDataUpperD? D;

  TurbineDetailModelDataDetailDataUpper({
    this.A,
    this.B,
    this.C,
    this.D,
  });
  TurbineDetailModelDataDetailDataUpper.fromJson(Map<String, dynamic> json) {
    A = (json['A'] != null)
        ? TurbineDetailModelDataDetailDataUpperA.fromJson(json['A'])
        : null;
    B = (json['B'] != null)
        ? TurbineDetailModelDataDetailDataUpperB.fromJson(json['B'])
        : null;
    C = (json['C'] != null)
        ? TurbineDetailModelDataDetailDataUpperC.fromJson(json['C'])
        : null;
    D = (json['D'] != null)
        ? TurbineDetailModelDataDetailDataUpperD.fromJson(json['D'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (A != null) {
      data['A'] = A!.toJson();
    }
    if (B != null) {
      data['B'] = B!.toJson();
    }
    if (C != null) {
      data['C'] = C!.toJson();
    }
    if (D != null) {
      data['D'] = D!.toJson();
    }
    return data;
  }
}

class TurbineDetailModelDataDetailDataTurbineD {
/*
{
  "1": 40.5,
  "2": 40.5,
  "3": 40.5,
  "4": 41
} 
*/

  double? the1;
  double? the2;
  double? the3;
  int? the4;

  TurbineDetailModelDataDetailDataTurbineD({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineDetailModelDataDetailDataTurbineD.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toDouble();
    the2 = json['2']?.toDouble();
    the3 = json['3']?.toDouble();
    the4 = json['4']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineDetailModelDataDetailDataTurbineC {
/*
{
  "1": 48,
  "2": 48,
  "3": 48,
  "4": 48
} 
*/

  int? the1;
  int? the2;
  int? the3;
  int? the4;

  TurbineDetailModelDataDetailDataTurbineC({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineDetailModelDataDetailDataTurbineC.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toInt();
    the2 = json['2']?.toInt();
    the3 = json['3']?.toInt();
    the4 = json['4']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineDetailModelDataDetailDataTurbineB {
/*
{
  "1": 42,
  "2": 42,
  "3": 42,
  "4": 42.5
} 
*/

  int? the1;
  int? the2;
  int? the3;
  double? the4;

  TurbineDetailModelDataDetailDataTurbineB({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineDetailModelDataDetailDataTurbineB.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toInt();
    the2 = json['2']?.toInt();
    the3 = json['3']?.toInt();
    the4 = json['4']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineDetailModelDataDetailDataTurbineA {
/*
{
  "1": 50,
  "2": 50,
  "3": 50,
  "4": 50
} 
*/

  int? the1;
  int? the2;
  int? the3;
  int? the4;

  TurbineDetailModelDataDetailDataTurbineA({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineDetailModelDataDetailDataTurbineA.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toInt();
    the2 = json['2']?.toInt();
    the3 = json['3']?.toInt();
    the4 = json['4']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineDetailModelDataDetailDataTurbine {
/*
{
  "A": {
    "1": 50,
    "2": 50,
    "3": 50,
    "4": 50
  },
  "B": {
    "1": 42,
    "2": 42,
    "3": 42,
    "4": 42.5
  },
  "C": {
    "1": 48,
    "2": 48,
    "3": 48,
    "4": 48
  },
  "D": {
    "1": 40.5,
    "2": 40.5,
    "3": 40.5,
    "4": 41
  }
} 
*/

  TurbineDetailModelDataDetailDataTurbineA? A;
  TurbineDetailModelDataDetailDataTurbineB? B;
  TurbineDetailModelDataDetailDataTurbineC? C;
  TurbineDetailModelDataDetailDataTurbineD? D;

  TurbineDetailModelDataDetailDataTurbine({
    this.A,
    this.B,
    this.C,
    this.D,
  });
  TurbineDetailModelDataDetailDataTurbine.fromJson(Map<String, dynamic> json) {
    A = (json['A'] != null)
        ? TurbineDetailModelDataDetailDataTurbineA.fromJson(json['A'])
        : null;
    B = (json['B'] != null)
        ? TurbineDetailModelDataDetailDataTurbineB.fromJson(json['B'])
        : null;
    C = (json['C'] != null)
        ? TurbineDetailModelDataDetailDataTurbineC.fromJson(json['C'])
        : null;
    D = (json['D'] != null)
        ? TurbineDetailModelDataDetailDataTurbineD.fromJson(json['D'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (A != null) {
      data['A'] = A!.toJson();
    }
    if (B != null) {
      data['B'] = B!.toJson();
    }
    if (C != null) {
      data['C'] = C!.toJson();
    }
    if (D != null) {
      data['D'] = D!.toJson();
    }
    return data;
  }
}

class TurbineDetailModelDataDetailDataClutchD {
/*
{
  "1": 51,
  "2": 51,
  "3": 51,
  "4": 51
} 
*/

  int? the1;
  int? the2;
  int? the3;
  int? the4;

  TurbineDetailModelDataDetailDataClutchD({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineDetailModelDataDetailDataClutchD.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toInt();
    the2 = json['2']?.toInt();
    the3 = json['3']?.toInt();
    the4 = json['4']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineDetailModelDataDetailDataClutchC {
/*
{
  "1": 46,
  "2": 46,
  "3": 46,
  "4": 46
} 
*/

  int? the1;
  int? the2;
  int? the3;
  int? the4;

  TurbineDetailModelDataDetailDataClutchC({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineDetailModelDataDetailDataClutchC.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toInt();
    the2 = json['2']?.toInt();
    the3 = json['3']?.toInt();
    the4 = json['4']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineDetailModelDataDetailDataClutchB {
/*
{
  "1": 46,
  "2": 46,
  "3": 46,
  "4": 46
} 
*/

  int? the1;
  int? the2;
  int? the3;
  int? the4;

  TurbineDetailModelDataDetailDataClutchB({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineDetailModelDataDetailDataClutchB.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toInt();
    the2 = json['2']?.toInt();
    the3 = json['3']?.toInt();
    the4 = json['4']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineDetailModelDataDetailDataClutchA {
/*
{
  "1": 50,
  "2": 50,
  "3": 50,
  "4": 50
} 
*/

  int? the1;
  int? the2;
  int? the3;
  int? the4;

  TurbineDetailModelDataDetailDataClutchA({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineDetailModelDataDetailDataClutchA.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toInt();
    the2 = json['2']?.toInt();
    the3 = json['3']?.toInt();
    the4 = json['4']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineDetailModelDataDetailDataClutch {
/*
{
  "A": {
    "1": 50,
    "2": 50,
    "3": 50,
    "4": 50
  },
  "B": {
    "1": 46,
    "2": 46,
    "3": 46,
    "4": 46
  },
  "C": {
    "1": 46,
    "2": 46,
    "3": 46,
    "4": 46
  },
  "D": {
    "1": 51,
    "2": 51,
    "3": 51,
    "4": 51
  }
} 
*/

  TurbineDetailModelDataDetailDataClutchA? A;
  TurbineDetailModelDataDetailDataClutchB? B;
  TurbineDetailModelDataDetailDataClutchC? C;
  TurbineDetailModelDataDetailDataClutchD? D;

  TurbineDetailModelDataDetailDataClutch({
    this.A,
    this.B,
    this.C,
    this.D,
  });
  TurbineDetailModelDataDetailDataClutch.fromJson(Map<String, dynamic> json) {
    A = (json['A'] != null)
        ? TurbineDetailModelDataDetailDataClutchA.fromJson(json['A'])
        : null;
    B = (json['B'] != null)
        ? TurbineDetailModelDataDetailDataClutchB.fromJson(json['B'])
        : null;
    C = (json['C'] != null)
        ? TurbineDetailModelDataDetailDataClutchC.fromJson(json['C'])
        : null;
    D = (json['D'] != null)
        ? TurbineDetailModelDataDetailDataClutchD.fromJson(json['D'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (A != null) {
      data['A'] = A!.toJson();
    }
    if (B != null) {
      data['B'] = B!.toJson();
    }
    if (C != null) {
      data['C'] = C!.toJson();
    }
    if (D != null) {
      data['D'] = D!.toJson();
    }
    return data;
  }
}

class TurbineDetailModelDataDetailData {
/*
{
  "Clutch": {
    "A": {
      "1": 50,
      "2": 50,
      "3": 50,
      "4": 50
    },
    "B": {
      "1": 46,
      "2": 46,
      "3": 46,
      "4": 46
    },
    "C": {
      "1": 46,
      "2": 46,
      "3": 46,
      "4": 46
    },
    "D": {
      "1": 51,
      "2": 51,
      "3": 51,
      "4": 51
    }
  },
  "Turbine": {
    "A": {
      "1": 50,
      "2": 50,
      "3": 50,
      "4": 50
    },
    "B": {
      "1": 42,
      "2": 42,
      "3": 42,
      "4": 42.5
    },
    "C": {
      "1": 48,
      "2": 48,
      "3": 48,
      "4": 48
    },
    "D": {
      "1": 40.5,
      "2": 40.5,
      "3": 40.5,
      "4": 41
    }
  },
  "Upper": {
    "A": {
      "1": 50,
      "2": 50,
      "3": 50
    },
    "B": {
      "1": 48,
      "2": 48,
      "3": 48
    },
    "C": {
      "1": 46,
      "2": 46,
      "3": 46
    },
    "D": {
      "1": 55,
      "2": 55,
      "3": 55
    }
  }
} 
*/

  TurbineDetailModelDataDetailDataClutch? Clutch;
  TurbineDetailModelDataDetailDataTurbine? Turbine;
  TurbineDetailModelDataDetailDataUpper? Upper;

  TurbineDetailModelDataDetailData({
    this.Clutch,
    this.Turbine,
    this.Upper,
  });
  TurbineDetailModelDataDetailData.fromJson(Map<String, dynamic> json) {
    Clutch = (json['Clutch'] != null)
        ? TurbineDetailModelDataDetailDataClutch.fromJson(json['Clutch'])
        : null;
    Turbine = (json['Turbine'] != null)
        ? TurbineDetailModelDataDetailDataTurbine.fromJson(json['Turbine'])
        : null;
    Upper = (json['Upper'] != null)
        ? TurbineDetailModelDataDetailDataUpper.fromJson(json['Upper'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (Clutch != null) {
      data['Clutch'] = Clutch!.toJson();
    }
    if (Turbine != null) {
      data['Turbine'] = Turbine!.toJson();
    }
    if (Upper != null) {
      data['Upper'] = Upper!.toJson();
    }
    return data;
  }
}

class TurbineDetailModelDataChartBD {
/*
{
  "Clutch": "-2.000000|0",
  "Turbine": "-8.500000|424.000000",
  "Upper": "0|440.000000"
} 
*/

  String? Clutch;
  String? Turbine;
  String? Upper;

  TurbineDetailModelDataChartBD({
    this.Clutch,
    this.Turbine,
    this.Upper,
  });
  TurbineDetailModelDataChartBD.fromJson(Map<String, dynamic> json) {
    Clutch = json['Clutch']?.toString();
    Turbine = json['Turbine']?.toString();
    Upper = json['Upper']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Clutch'] = Clutch;
    data['Turbine'] = Turbine;
    data['Upper'] = Upper;
    return data;
  }
}

class TurbineDetailModelDataChartAC {
/*
{
  "Clutch": "0.000000|0",
  "Turbine": "2.000000|424.000000",
  "Upper": "0|440.000000"
} 
*/

  String? Clutch;
  String? Turbine;
  String? Upper;

  TurbineDetailModelDataChartAC({
    this.Clutch,
    this.Turbine,
    this.Upper,
  });
  TurbineDetailModelDataChartAC.fromJson(Map<String, dynamic> json) {
    Clutch = json['Clutch']?.toString();
    Turbine = json['Turbine']?.toString();
    Upper = json['Upper']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Clutch'] = Clutch;
    data['Turbine'] = Turbine;
    data['Upper'] = Upper;
    return data;
  }
}

class TurbineDetailModelDataChart {
/*
{
  "AC": {
    "Clutch": "0.000000|0",
    "Turbine": "2.000000|424.000000",
    "Upper": "0|440.000000"
  },
  "BD": {
    "Clutch": "-2.000000|0",
    "Turbine": "-8.500000|424.000000",
    "Upper": "0|440.000000"
  },
  "Upper": "1.037380|5.422861"
} 
*/

  TurbineDetailModelDataChartAC? AC;
  TurbineDetailModelDataChartBD? BD;
  String? Upper;

  TurbineDetailModelDataChart({
    this.AC,
    this.BD,
    this.Upper,
  });
  TurbineDetailModelDataChart.fromJson(Map<String, dynamic> json) {
    AC = (json['AC'] != null)
        ? TurbineDetailModelDataChartAC.fromJson(json['AC'])
        : null;
    BD = (json['BD'] != null)
        ? TurbineDetailModelDataChartBD.fromJson(json['BD'])
        : null;
    Upper = json['Upper']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (AC != null) {
      data['AC'] = AC!.toJson();
    }
    if (BD != null) {
      data['BD'] = BD!.toJson();
    }
    data['Upper'] = Upper;
    return data;
  }
}

class TurbineDetailModelDataShaft {
/*
{
  "GenBearingToCoupling": 440,
  "CouplingToTurbine": 424,
  "Total": 864,
  "Ratio": 0.5092592592592593
} 
*/

  int? GenBearingToCoupling;
  int? CouplingToTurbine;
  int? Total;
  double? Ratio;

  TurbineDetailModelDataShaft({
    this.GenBearingToCoupling,
    this.CouplingToTurbine,
    this.Total,
    this.Ratio,
  });
  TurbineDetailModelDataShaft.fromJson(Map<String, dynamic> json) {
    GenBearingToCoupling = json['GenBearingToCoupling']?.toInt();
    CouplingToTurbine = json['CouplingToTurbine']?.toInt();
    Total = json['Total']?.toInt();
    Ratio = json['Ratio']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['GenBearingToCoupling'] = GenBearingToCoupling;
    data['CouplingToTurbine'] = CouplingToTurbine;
    data['Total'] = Total;
    data['Ratio'] = Ratio;
    return data;
  }
}

class TurbineDetailModelData {
/*
{
  "Id": "01J06H7N5A16M6FGP600A6MH0F",
  "TowerName": "PLTA Malang - 0H823A1",
  "Shaft": {
    "GenBearingToCoupling": 440,
    "CouplingToTurbine": 424,
    "Total": 864,
    "Ratio": 0.5092592592592593
  },
  "Chart": {
    "AC": {
      "Clutch": "0.000000|0",
      "Turbine": "2.000000|424.000000",
      "Upper": "0|440.000000"
    },
    "BD": {
      "Clutch": "-2.000000|0",
      "Turbine": "-8.500000|424.000000",
      "Upper": "0|440.000000"
    },
    "Upper": "1.037380|5.422861"
  },
  "DetailData": {
    "Clutch": {
      "A": {
        "1": 50,
        "2": 50,
        "3": 50,
        "4": 50
      },
      "B": {
        "1": 46,
        "2": 46,
        "3": 46,
        "4": 46
      },
      "C": {
        "1": 46,
        "2": 46,
        "3": 46,
        "4": 46
      },
      "D": {
        "1": 51,
        "2": 51,
        "3": 51,
        "4": 51
      }
    },
    "Turbine": {
      "A": {
        "1": 50,
        "2": 50,
        "3": 50,
        "4": 50
      },
      "B": {
        "1": 42,
        "2": 42,
        "3": 42,
        "4": 42.5
      },
      "C": {
        "1": 48,
        "2": 48,
        "3": 48,
        "4": 48
      },
      "D": {
        "1": 40.5,
        "2": 40.5,
        "3": 40.5,
        "4": 41
      }
    },
    "Upper": {
      "A": {
        "1": 50,
        "2": 50,
        "3": 50
      },
      "B": {
        "1": 48,
        "2": 48,
        "3": 48
      },
      "C": {
        "1": 46,
        "2": 46,
        "3": 46
      },
      "D": {
        "1": 55,
        "2": 55,
        "3": 55
      }
    }
  },
  "TotalCrockedness": 2.5417003978062613,
  "CreatedAt": "2024-06-12 22:32:01",
  "CreatedBy": "aditya fullname"
} 
*/

  String? Id;
  String? TowerName;
  TurbineDetailModelDataShaft? Shaft;
  TurbineDetailModelDataChart? Chart;
  TurbineDetailModelDataDetailData? DetailData;
  double? TotalCrockedness;
  String? CreatedAt;
  String? CreatedBy;

  TurbineDetailModelData({
    this.Id,
    this.TowerName,
    this.Shaft,
    this.Chart,
    this.DetailData,
    this.TotalCrockedness,
    this.CreatedAt,
    this.CreatedBy,
  });
  TurbineDetailModelData.fromJson(Map<String, dynamic> json) {
    Id = json['Id']?.toString();
    TowerName = json['TowerName']?.toString();
    Shaft = (json['Shaft'] != null)
        ? TurbineDetailModelDataShaft.fromJson(json['Shaft'])
        : null;
    Chart = (json['Chart'] != null)
        ? TurbineDetailModelDataChart.fromJson(json['Chart'])
        : null;
    DetailData = (json['DetailData'] != null)
        ? TurbineDetailModelDataDetailData.fromJson(json['DetailData'])
        : null;
    TotalCrockedness = json['TotalCrockedness']?.toDouble();
    CreatedAt = json['CreatedAt']?.toString();
    CreatedBy = json['CreatedBy']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Id'] = Id;
    data['TowerName'] = TowerName;
    if (Shaft != null) {
      data['Shaft'] = Shaft!.toJson();
    }
    if (Chart != null) {
      data['Chart'] = Chart!.toJson();
    }
    if (DetailData != null) {
      data['DetailData'] = DetailData!.toJson();
    }
    data['TotalCrockedness'] = TotalCrockedness;
    data['CreatedAt'] = CreatedAt;
    data['CreatedBy'] = CreatedBy;
    return data;
  }
}

class TurbineDetailModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil mendapatkan data turbine",
  "Data": {
    "Id": "01J06H7N5A16M6FGP600A6MH0F",
    "TowerName": "PLTA Malang - 0H823A1",
    "Shaft": {
      "GenBearingToCoupling": 440,
      "CouplingToTurbine": 424,
      "Total": 864,
      "Ratio": 0.5092592592592593
    },
    "Chart": {
      "AC": {
        "Clutch": "0.000000|0",
        "Turbine": "2.000000|424.000000",
        "Upper": "0|440.000000"
      },
      "BD": {
        "Clutch": "-2.000000|0",
        "Turbine": "-8.500000|424.000000",
        "Upper": "0|440.000000"
      },
      "Upper": "1.037380|5.422861"
    },
    "DetailData": {
      "Clutch": {
        "A": {
          "1": 50,
          "2": 50,
          "3": 50,
          "4": 50
        },
        "B": {
          "1": 46,
          "2": 46,
          "3": 46,
          "4": 46
        },
        "C": {
          "1": 46,
          "2": 46,
          "3": 46,
          "4": 46
        },
        "D": {
          "1": 51,
          "2": 51,
          "3": 51,
          "4": 51
        }
      },
      "Turbine": {
        "A": {
          "1": 50,
          "2": 50,
          "3": 50,
          "4": 50
        },
        "B": {
          "1": 42,
          "2": 42,
          "3": 42,
          "4": 42.5
        },
        "C": {
          "1": 48,
          "2": 48,
          "3": 48,
          "4": 48
        },
        "D": {
          "1": 40.5,
          "2": 40.5,
          "3": 40.5,
          "4": 41
        }
      },
      "Upper": {
        "A": {
          "1": 50,
          "2": 50,
          "3": 50
        },
        "B": {
          "1": 48,
          "2": 48,
          "3": 48
        },
        "C": {
          "1": 46,
          "2": 46,
          "3": 46
        },
        "D": {
          "1": 55,
          "2": 55,
          "3": 55
        }
      }
    },
    "TotalCrockedness": 2.5417003978062613,
    "CreatedAt": "2024-06-12 22:32:01",
    "CreatedBy": "aditya fullname"
  }
} 
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  TurbineDetailModelData? Data;

  TurbineDetailModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
  });
  TurbineDetailModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    Data = (json['Data'] != null)
        ? TurbineDetailModelData.fromJson(json['Data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
