///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TurbineCreateModelDataDetailDataUpperD {
/*
{
  "1": 51,
  "2": 52,
  "3": 51,
  "4": 52
} 
*/

  double? the1;
  double? the2;
  double? the3;
  double? the4;

  TurbineCreateModelDataDetailDataUpperD({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineCreateModelDataDetailDataUpperD.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toDouble();
    the2 = json['2']?.toDouble();
    the3 = json['3']?.toDouble();
    the4 = json['4']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineCreateModelDataDetailDataUpperC {
/*
{
  "1": 51,
  "2": 51,
  "3": 51,
  "4": 51
} 
*/

  double? the1;
  double? the2;
  double? the3;
  double? the4;

  TurbineCreateModelDataDetailDataUpperC({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineCreateModelDataDetailDataUpperC.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toDouble();
    the2 = json['2']?.toDouble();
    the3 = json['3']?.toDouble();
    the4 = json['4']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineCreateModelDataDetailDataUpperB {
/*
{
  "1": 51,
  "2": 52,
  "3": 51,
  "4": 52
} 
*/

  double? the1;
  double? the2;
  double? the3;
  double? the4;

  TurbineCreateModelDataDetailDataUpperB({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineCreateModelDataDetailDataUpperB.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toDouble();
    the2 = json['2']?.toDouble();
    the3 = json['3']?.toDouble();
    the4 = json['4']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineCreateModelDataDetailDataUpperA {
/*
{
  "1": 48,
  "2": 48,
  "3": 48,
  "4": 49
} 
*/

  double? the1;
  double? the2;
  double? the3;
  double? the4;

  TurbineCreateModelDataDetailDataUpperA({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineCreateModelDataDetailDataUpperA.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toDouble();
    the2 = json['2']?.toDouble();
    the3 = json['3']?.toDouble();
    the4 = json['4']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineCreateModelDataDetailDataUpper {
/*
{
  "A": {
    "1": 48,
    "2": 48,
    "3": 48,
    "4": 49
  },
  "B": {
    "1": 51,
    "2": 52,
    "3": 51,
    "4": 52
  },
  "C": {
    "1": 51,
    "2": 51,
    "3": 51,
    "4": 51
  },
  "D": {
    "1": 51,
    "2": 52,
    "3": 51,
    "4": 52
  }
} 
*/

  TurbineCreateModelDataDetailDataUpperA? A;
  TurbineCreateModelDataDetailDataUpperB? B;
  TurbineCreateModelDataDetailDataUpperC? C;
  TurbineCreateModelDataDetailDataUpperD? D;

  TurbineCreateModelDataDetailDataUpper({
    this.A,
    this.B,
    this.C,
    this.D,
  });
  TurbineCreateModelDataDetailDataUpper.fromJson(Map<String, dynamic> json) {
    A = (json['A'] != null)
        ? TurbineCreateModelDataDetailDataUpperA.fromJson(json['A'])
        : null;
    B = (json['B'] != null)
        ? TurbineCreateModelDataDetailDataUpperB.fromJson(json['B'])
        : null;
    C = (json['C'] != null)
        ? TurbineCreateModelDataDetailDataUpperC.fromJson(json['C'])
        : null;
    D = (json['D'] != null)
        ? TurbineCreateModelDataDetailDataUpperD.fromJson(json['D'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (A != null) {
      data['A'] = A!.toJson();
    }
    if (B != null) {
      data['B'] = B!.toJson();
    }
    if (C != null) {
      data['C'] = C!.toJson();
    }
    if (D != null) {
      data['D'] = D!.toJson();
    }
    return data;
  }
}

class TurbineCreateModelDataDetailDataTurbineD {
/*
{
  "1": 51,
  "2": 51,
  "3": 52,
  "4": 51
} 
*/

  double? the1;
  double? the2;
  double? the3;
  double? the4;

  TurbineCreateModelDataDetailDataTurbineD({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineCreateModelDataDetailDataTurbineD.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toDouble();
    the2 = json['2']?.toDouble();
    the3 = json['3']?.toDouble();
    the4 = json['4']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineCreateModelDataDetailDataTurbineC {
/*
{
  "1": 50,
  "2": 50,
  "3": 50,
  "4": 50
} 
*/

  double? the1;
  double? the2;
  double? the3;
  double? the4;

  TurbineCreateModelDataDetailDataTurbineC({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineCreateModelDataDetailDataTurbineC.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toDouble();
    the2 = json['2']?.toDouble();
    the3 = json['3']?.toDouble();
    the4 = json['4']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineCreateModelDataDetailDataTurbineB {
/*
{
  "1": 51,
  "2": 51,
  "3": 51,
  "4": 51
} 
*/

  double? the1;
  double? the2;
  double? the3;
  double? the4;

  TurbineCreateModelDataDetailDataTurbineB({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineCreateModelDataDetailDataTurbineB.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toDouble();
    the2 = json['2']?.toDouble();
    the3 = json['3']?.toDouble();
    the4 = json['4']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineCreateModelDataDetailDataTurbineA {
/*
{
  "1": 43,
  "2": 43,
  "3": 43,
  "4": 41
} 
*/

  double? the1;
  double? the2;
  double? the3;
  double? the4;

  TurbineCreateModelDataDetailDataTurbineA({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineCreateModelDataDetailDataTurbineA.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toDouble();
    the2 = json['2']?.toDouble();
    the3 = json['3']?.toDouble();
    the4 = json['4']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineCreateModelDataDetailDataTurbine {
/*
{
  "A": {
    "1": 43,
    "2": 43,
    "3": 43,
    "4": 41
  },
  "B": {
    "1": 51,
    "2": 51,
    "3": 51,
    "4": 51
  },
  "C": {
    "1": 50,
    "2": 50,
    "3": 50,
    "4": 50
  },
  "D": {
    "1": 51,
    "2": 51,
    "3": 52,
    "4": 51
  }
} 
*/

  TurbineCreateModelDataDetailDataTurbineA? A;
  TurbineCreateModelDataDetailDataTurbineB? B;
  TurbineCreateModelDataDetailDataTurbineC? C;
  TurbineCreateModelDataDetailDataTurbineD? D;

  TurbineCreateModelDataDetailDataTurbine({
    this.A,
    this.B,
    this.C,
    this.D,
  });
  TurbineCreateModelDataDetailDataTurbine.fromJson(Map<String, dynamic> json) {
    A = (json['A'] != null)
        ? TurbineCreateModelDataDetailDataTurbineA.fromJson(json['A'])
        : null;
    B = (json['B'] != null)
        ? TurbineCreateModelDataDetailDataTurbineB.fromJson(json['B'])
        : null;
    C = (json['C'] != null)
        ? TurbineCreateModelDataDetailDataTurbineC.fromJson(json['C'])
        : null;
    D = (json['D'] != null)
        ? TurbineCreateModelDataDetailDataTurbineD.fromJson(json['D'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (A != null) {
      data['A'] = A!.toJson();
    }
    if (B != null) {
      data['B'] = B!.toJson();
    }
    if (C != null) {
      data['C'] = C!.toJson();
    }
    if (D != null) {
      data['D'] = D!.toJson();
    }
    return data;
  }
}

class TurbineCreateModelDataDetailDataClutchD {
/*
{
  "1": 52,
  "2": 51,
  "3": 51,
  "4": 51
} 
*/

  double? the1;
  double? the2;
  double? the3;
  double? the4;

  TurbineCreateModelDataDetailDataClutchD({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineCreateModelDataDetailDataClutchD.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toDouble();
    the2 = json['2']?.toDouble();
    the3 = json['3']?.toDouble();
    the4 = json['4']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineCreateModelDataDetailDataClutchC {
/*
{
  "1": 51,
  "2": 51,
  "3": 51,
  "4": 51
} 
*/

  double? the1;
  double? the2;
  double? the3;
  double? the4;

  TurbineCreateModelDataDetailDataClutchC({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineCreateModelDataDetailDataClutchC.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toDouble();
    the2 = json['2']?.toDouble();
    the3 = json['3']?.toDouble();
    the4 = json['4']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineCreateModelDataDetailDataClutchB {
/*
{
  "1": 48,
  "2": 48,
  "3": 48,
  "4": 48
} 
*/

  double? the1;
  double? the2;
  double? the3;
  double? the4;

  TurbineCreateModelDataDetailDataClutchB({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineCreateModelDataDetailDataClutchB.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toDouble();
    the2 = json['2']?.toDouble();
    the3 = json['3']?.toDouble();
    the4 = json['4']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineCreateModelDataDetailDataClutchA {
/*
{
  "1": 52,
  "2": 51,
  "3": 51,
  "4": 51
} 
*/

  double? the1;
  double? the2;
  double? the3;
  double? the4;

  TurbineCreateModelDataDetailDataClutchA({
    this.the1,
    this.the2,
    this.the3,
    this.the4,
  });
  TurbineCreateModelDataDetailDataClutchA.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toDouble();
    the2 = json['2']?.toDouble();
    the3 = json['3']?.toDouble();
    the4 = json['4']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    data['3'] = the3;
    data['4'] = the4;
    return data;
  }
}

class TurbineCreateModelDataDetailDataClutch {
/*
{
  "A": {
    "1": 52,
    "2": 51,
    "3": 51,
    "4": 51
  },
  "B": {
    "1": 48,
    "2": 48,
    "3": 48,
    "4": 48
  },
  "C": {
    "1": 51,
    "2": 51,
    "3": 51,
    "4": 51
  },
  "D": {
    "1": 52,
    "2": 51,
    "3": 51,
    "4": 51
  }
} 
*/

  TurbineCreateModelDataDetailDataClutchA? A;
  TurbineCreateModelDataDetailDataClutchB? B;
  TurbineCreateModelDataDetailDataClutchC? C;
  TurbineCreateModelDataDetailDataClutchD? D;

  TurbineCreateModelDataDetailDataClutch({
    this.A,
    this.B,
    this.C,
    this.D,
  });
  TurbineCreateModelDataDetailDataClutch.fromJson(Map<String, dynamic> json) {
    A = (json['A'] != null)
        ? TurbineCreateModelDataDetailDataClutchA.fromJson(json['A'])
        : null;
    B = (json['B'] != null)
        ? TurbineCreateModelDataDetailDataClutchB.fromJson(json['B'])
        : null;
    C = (json['C'] != null)
        ? TurbineCreateModelDataDetailDataClutchC.fromJson(json['C'])
        : null;
    D = (json['D'] != null)
        ? TurbineCreateModelDataDetailDataClutchD.fromJson(json['D'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (A != null) {
      data['A'] = A!.toJson();
    }
    if (B != null) {
      data['B'] = B!.toJson();
    }
    if (C != null) {
      data['C'] = C!.toJson();
    }
    if (D != null) {
      data['D'] = D!.toJson();
    }
    return data;
  }
}

class TurbineCreateModelDataDetailData {
/*
{
  "Clutch": {
    "A": {
      "1": 52,
      "2": 51,
      "3": 51,
      "4": 51
    },
    "B": {
      "1": 48,
      "2": 48,
      "3": 48,
      "4": 48
    },
    "C": {
      "1": 51,
      "2": 51,
      "3": 51,
      "4": 51
    },
    "D": {
      "1": 52,
      "2": 51,
      "3": 51,
      "4": 51
    }
  },
  "Turbine": {
    "A": {
      "1": 43,
      "2": 43,
      "3": 43,
      "4": 41
    },
    "B": {
      "1": 51,
      "2": 51,
      "3": 51,
      "4": 51
    },
    "C": {
      "1": 50,
      "2": 50,
      "3": 50,
      "4": 50
    },
    "D": {
      "1": 51,
      "2": 51,
      "3": 52,
      "4": 51
    }
  },
  "Upper": {
    "A": {
      "1": 48,
      "2": 48,
      "3": 48,
      "4": 49
    },
    "B": {
      "1": 51,
      "2": 52,
      "3": 51,
      "4": 52
    },
    "C": {
      "1": 51,
      "2": 51,
      "3": 51,
      "4": 51
    },
    "D": {
      "1": 51,
      "2": 52,
      "3": 51,
      "4": 52
    }
  }
} 
*/

  TurbineCreateModelDataDetailDataClutch? Clutch;
  TurbineCreateModelDataDetailDataTurbine? Turbine;
  TurbineCreateModelDataDetailDataUpper? Upper;

  TurbineCreateModelDataDetailData({
    this.Clutch,
    this.Turbine,
    this.Upper,
  });
  TurbineCreateModelDataDetailData.fromJson(Map<String, dynamic> json) {
    Clutch = (json['Clutch'] != null)
        ? TurbineCreateModelDataDetailDataClutch.fromJson(json['Clutch'])
        : null;
    Turbine = (json['Turbine'] != null)
        ? TurbineCreateModelDataDetailDataTurbine.fromJson(json['Turbine'])
        : null;
    Upper = (json['Upper'] != null)
        ? TurbineCreateModelDataDetailDataUpper.fromJson(json['Upper'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (Clutch != null) {
      data['Clutch'] = Clutch!.toJson();
    }
    if (Turbine != null) {
      data['Turbine'] = Turbine!.toJson();
    }
    if (Upper != null) {
      data['Upper'] = Upper!.toJson();
    }
    return data;
  }
}

class TurbineCreateModelDataChartBD {
/*
{
  "Clutch": "3.250000|0",
  "Turbine": "0.250000|7000.000000",
  "Upper": "0|5000.000000"
} 
*/

  String? Clutch;
  String? Turbine;
  String? Upper;

  TurbineCreateModelDataChartBD({
    this.Clutch,
    this.Turbine,
    this.Upper,
  });
  TurbineCreateModelDataChartBD.fromJson(Map<String, dynamic> json) {
    Clutch = json['Clutch']?.toString();
    Turbine = json['Turbine']?.toString();
    Upper = json['Upper']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Clutch'] = Clutch;
    data['Turbine'] = Turbine;
    data['Upper'] = Upper;
    return data;
  }
}

class TurbineCreateModelDataChartAC {
/*
{
  "Clutch": "-3.000000|0",
  "Turbine": "4.750000|7000.000000",
  "Upper": "0|5000.000000"
} 
*/

  String? Clutch;
  String? Turbine;
  String? Upper;

  TurbineCreateModelDataChartAC({
    this.Clutch,
    this.Turbine,
    this.Upper,
  });
  TurbineCreateModelDataChartAC.fromJson(Map<String, dynamic> json) {
    Clutch = json['Clutch']?.toString();
    Turbine = json['Turbine']?.toString();
    Upper = json['Upper']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Clutch'] = Clutch;
    data['Turbine'] = Turbine;
    data['Upper'] = Upper;
    return data;
  }
}

class TurbineCreateModelDataChart {
/*
{
  "AC": {
    "Clutch": "-3.000000|0",
    "Turbine": "4.750000|7000.000000",
    "Upper": "0|5000.000000"
  },
  "BD": {
    "Clutch": "3.250000|0",
    "Turbine": "0.250000|7000.000000",
    "Upper": "0|5000.000000"
  },
  "Upper": "24.792101|9.896267"
} 
*/

  TurbineCreateModelDataChartAC? AC;
  TurbineCreateModelDataChartBD? BD;
  String? Upper;

  TurbineCreateModelDataChart({
    this.AC,
    this.BD,
    this.Upper,
  });
  TurbineCreateModelDataChart.fromJson(Map<String, dynamic> json) {
    AC = (json['AC'] != null)
        ? TurbineCreateModelDataChartAC.fromJson(json['AC'])
        : null;
    BD = (json['BD'] != null)
        ? TurbineCreateModelDataChartBD.fromJson(json['BD'])
        : null;
    Upper = json['Upper']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (AC != null) {
      data['AC'] = AC!.toJson();
    }
    if (BD != null) {
      data['BD'] = BD!.toJson();
    }
    data['Upper'] = Upper;
    return data;
  }
}

class TurbineCreateModelDataShaft {
/*
{
  "GenBearingToCoupling": 5000,
  "CouplingToTurbine": 7000,
  "Total": 12000,
  "Ratio": 0.4166666666666667
} 
*/

  int? GenBearingToCoupling;
  int? CouplingToTurbine;
  int? Total;
  double? Ratio;

  TurbineCreateModelDataShaft({
    this.GenBearingToCoupling,
    this.CouplingToTurbine,
    this.Total,
    this.Ratio,
  });
  TurbineCreateModelDataShaft.fromJson(Map<String, dynamic> json) {
    GenBearingToCoupling = json['GenBearingToCoupling']?.toInt();
    CouplingToTurbine = json['CouplingToTurbine']?.toInt();
    Total = json['Total']?.toInt();
    Ratio = json['Ratio']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['GenBearingToCoupling'] = GenBearingToCoupling;
    data['CouplingToTurbine'] = CouplingToTurbine;
    data['Total'] = Total;
    data['Ratio'] = Ratio;
    return data;
  }
}

class TurbineCreateModelData {
/*
{
  "Id": "01J1WSYW0G5VRCRB599NA6P1A5",
  "TowerName": "PLTA Lodoyo - 1",
  "Shaft": {
    "GenBearingToCoupling": 5000,
    "CouplingToTurbine": 7000,
    "Total": 12000,
    "Ratio": 0.4166666666666667
  },
  "Chart": {
    "AC": {
      "Clutch": "-3.000000|0",
      "Turbine": "4.750000|7000.000000",
      "Upper": "0|5000.000000"
    },
    "BD": {
      "Clutch": "3.250000|0",
      "Turbine": "0.250000|7000.000000",
      "Upper": "0|5000.000000"
    },
    "Upper": "24.792101|9.896267"
  },
  "DetailData": {
    "Clutch": {
      "A": {
        "1": 52,
        "2": 51,
        "3": 51,
        "4": 51
      },
      "B": {
        "1": 48,
        "2": 48,
        "3": 48,
        "4": 48
      },
      "C": {
        "1": 51,
        "2": 51,
        "3": 51,
        "4": 51
      },
      "D": {
        "1": 52,
        "2": 51,
        "3": 51,
        "4": 51
      }
    },
    "Turbine": {
      "A": {
        "1": 43,
        "2": 43,
        "3": 43,
        "4": 41
      },
      "B": {
        "1": 51,
        "2": 51,
        "3": 51,
        "4": 51
      },
      "C": {
        "1": 50,
        "2": 50,
        "3": 50,
        "4": 50
      },
      "D": {
        "1": 51,
        "2": 51,
        "3": 52,
        "4": 51
      }
    },
    "Upper": {
      "A": {
        "1": 48,
        "2": 48,
        "3": 48,
        "4": 49
      },
      "B": {
        "1": 51,
        "2": 52,
        "3": 51,
        "4": 52
      },
      "C": {
        "1": 51,
        "2": 51,
        "3": 51,
        "4": 51
      },
      "D": {
        "1": 51,
        "2": 52,
        "3": 51,
        "4": 52
      }
    }
  },
  "ACCrockedness": 24.792100694444446,
  "BDCrockedness": 9.896267361111112,
  "TotalCrockedness": 5.889683188046328,
  "CreatedAt": "2024-07-04 00:23:30",
  "CreatedBy": "aditya fullname",
  "Status": false
} 
*/

  String? Id;
  String? TowerName;
  TurbineCreateModelDataShaft? Shaft;
  TurbineCreateModelDataChart? Chart;
  TurbineCreateModelDataDetailData? DetailData;
  double? ACCrockedness;
  double? BDCrockedness;
  double? TotalCrockedness;
  String? CreatedAt;
  String? CreatedBy;
  bool? Status;

  TurbineCreateModelData({
    this.Id,
    this.TowerName,
    this.Shaft,
    this.Chart,
    this.DetailData,
    this.ACCrockedness,
    this.BDCrockedness,
    this.TotalCrockedness,
    this.CreatedAt,
    this.CreatedBy,
    this.Status,
  });
  TurbineCreateModelData.fromJson(Map<String, dynamic> json) {
    Id = json['Id']?.toString();
    TowerName = json['TowerName']?.toString();
    Shaft = (json['Shaft'] != null)
        ? TurbineCreateModelDataShaft.fromJson(json['Shaft'])
        : null;
    Chart = (json['Chart'] != null)
        ? TurbineCreateModelDataChart.fromJson(json['Chart'])
        : null;
    DetailData = (json['DetailData'] != null)
        ? TurbineCreateModelDataDetailData.fromJson(json['DetailData'])
        : null;
    ACCrockedness = json['ACCrockedness']?.toDouble();
    BDCrockedness = json['BDCrockedness']?.toDouble();
    TotalCrockedness = json['TotalCrockedness']?.toDouble();
    CreatedAt = json['CreatedAt']?.toString();
    CreatedBy = json['CreatedBy']?.toString();
    Status = json['Status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Id'] = Id;
    data['TowerName'] = TowerName;
    if (Shaft != null) {
      data['Shaft'] = Shaft!.toJson();
    }
    if (Chart != null) {
      data['Chart'] = Chart!.toJson();
    }
    if (DetailData != null) {
      data['DetailData'] = DetailData!.toJson();
    }
    data['ACCrockedness'] = ACCrockedness;
    data['BDCrockedness'] = BDCrockedness;
    data['TotalCrockedness'] = TotalCrockedness;
    data['CreatedAt'] = CreatedAt;
    data['CreatedBy'] = CreatedBy;
    data['Status'] = Status;
    return data;
  }
}

class TurbineCreateModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil menambahkan data turbine baru",
  "Data": {
    "Id": "01J1WSYW0G5VRCRB599NA6P1A5",
    "TowerName": "PLTA Lodoyo - 1",
    "Shaft": {
      "GenBearingToCoupling": 5000,
      "CouplingToTurbine": 7000,
      "Total": 12000,
      "Ratio": 0.4166666666666667
    },
    "Chart": {
      "AC": {
        "Clutch": "-3.000000|0",
        "Turbine": "4.750000|7000.000000",
        "Upper": "0|5000.000000"
      },
      "BD": {
        "Clutch": "3.250000|0",
        "Turbine": "0.250000|7000.000000",
        "Upper": "0|5000.000000"
      },
      "Upper": "24.792101|9.896267"
    },
    "DetailData": {
      "Clutch": {
        "A": {
          "1": 52,
          "2": 51,
          "3": 51,
          "4": 51
        },
        "B": {
          "1": 48,
          "2": 48,
          "3": 48,
          "4": 48
        },
        "C": {
          "1": 51,
          "2": 51,
          "3": 51,
          "4": 51
        },
        "D": {
          "1": 52,
          "2": 51,
          "3": 51,
          "4": 51
        }
      },
      "Turbine": {
        "A": {
          "1": 43,
          "2": 43,
          "3": 43,
          "4": 41
        },
        "B": {
          "1": 51,
          "2": 51,
          "3": 51,
          "4": 51
        },
        "C": {
          "1": 50,
          "2": 50,
          "3": 50,
          "4": 50
        },
        "D": {
          "1": 51,
          "2": 51,
          "3": 52,
          "4": 51
        }
      },
      "Upper": {
        "A": {
          "1": 48,
          "2": 48,
          "3": 48,
          "4": 49
        },
        "B": {
          "1": 51,
          "2": 52,
          "3": 51,
          "4": 52
        },
        "C": {
          "1": 51,
          "2": 51,
          "3": 51,
          "4": 51
        },
        "D": {
          "1": 51,
          "2": 52,
          "3": 51,
          "4": 52
        }
      }
    },
    "ACCrockedness": 24.792100694444446,
    "BDCrockedness": 9.896267361111112,
    "TotalCrockedness": 5.889683188046328,
    "CreatedAt": "2024-07-04 00:23:30",
    "CreatedBy": "aditya fullname",
    "Status": false
  }
} 
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  TurbineCreateModelData? Data;

  TurbineCreateModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
  });
  TurbineCreateModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    Data = (json['Data'] != null)
        ? TurbineCreateModelData.fromJson(json['Data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
