///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TurbineModelMeta {
/*
{
  "Next": "",
  "Prev": ""
} 
*/

  String? Next;
  String? Prev;

  TurbineModelMeta({
    this.Next,
    this.Prev,
  });
  TurbineModelMeta.fromJson(Map<String, dynamic> json) {
    Next = json['Next']?.toString();
    Prev = json['Prev']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Next'] = Next;
    data['Prev'] = Prev;
    return data;
  }
}

class TurbineModelData {
/*
{
  "Id": "01J06H7N5A16M6FGP600A6MH0F",
  "TowerName": "PLTA Malang - 0H823A1",
  "CreatedAt": "2024-06-12 22:32:01"
} 
*/

  String? Id;
  String? TowerName;
  String? CreatedAt;

  TurbineModelData({
    this.Id,
    this.TowerName,
    this.CreatedAt,
  });
  TurbineModelData.fromJson(Map<String, dynamic> json) {
    Id = json['Id']?.toString();
    TowerName = json['TowerName']?.toString();
    CreatedAt = json['CreatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Id'] = Id;
    data['TowerName'] = TowerName;
    data['CreatedAt'] = CreatedAt;
    return data;
  }
}

class TurbineModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil mendapatkan semua data turbine",
  "Data": [
    {
      "Id": "01J06H7N5A16M6FGP600A6MH0F",
      "TowerName": "PLTA Malang - 0H823A1",
      "CreatedAt": "2024-06-12 22:32:01"
    }
  ],
  "Meta": {
    "Next": "",
    "Prev": ""
  }
} 
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  List<TurbineModelData?>? Data;
  TurbineModelMeta? Meta;

  TurbineModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
    this.Meta,
  });
  TurbineModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    if (json['Data'] != null) {
      final v = json['Data'];
      final arr0 = <TurbineModelData>[];
      v.forEach((v) {
        arr0.add(TurbineModelData.fromJson(v));
      });
      Data = arr0;
    }
    Meta =
        (json['Meta'] != null) ? TurbineModelMeta.fromJson(json['Meta']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      final v = Data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Data'] = arr0;
    }
    if (Meta != null) {
      data['Meta'] = Meta!.toJson();
    }
    return data;
  }
}
