///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OperationHoursViewModelData {
/*
{
  "id": 8120,
  "doc_no": "AM-2024-0008",
  "asset_code": "2000021020",
  "cabang_code": "CAB27",
  "regional_code": "REG05",
  "asset_meter_code": "Jam-Operasi",
  "meter_reading": 200,
  "meter_lalu": 0,
  "date_doc": "2024-02-20",
  "description": "tes",
  "time": "21:21:28",
  "is_delete": 0,
  "is_reset": 0,
  "company_id": 1,
  "created_at": 1710138105,
  "created_by": 1,
  "updated_at": 1710138105,
  "updated_by": 1
} 
*/

  String? id;
  String? docNo;
  String? assetCode;
  String? cabangCode;
  String? regionalCode;
  String? assetMeterCode;
  String? meterReading;
  String? meterLalu;
  String? dateDoc;
  String? description;
  String? time;
  String? isDelete;
  String? isReset;
  String? companyId;
  String? createdAt;
  String? createdBy;
  String? updatedAt;
  String? updatedBy;

  OperationHoursViewModelData({
    this.id,
    this.docNo,
    this.assetCode,
    this.cabangCode,
    this.regionalCode,
    this.assetMeterCode,
    this.meterReading,
    this.meterLalu,
    this.dateDoc,
    this.description,
    this.time,
    this.isDelete,
    this.isReset,
    this.companyId,
    this.createdAt,
    this.createdBy,
    this.updatedAt,
    this.updatedBy,
  });
  OperationHoursViewModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    docNo = json['doc_no']?.toString();
    assetCode = json['asset_code']?.toString();
    cabangCode = json['cabang_code']?.toString();
    regionalCode = json['regional_code']?.toString();
    assetMeterCode = json['asset_meter_code']?.toString();
    meterReading = json['meter_reading']?.toString();
    meterLalu = json['meter_lalu']?.toString();
    dateDoc = json['date_doc']?.toString();
    description = json['description']?.toString();
    time = json['time']?.toString();
    isDelete = json['is_delete']?.toString();
    isReset = json['is_reset']?.toString();
    companyId = json['company_id']?.toString();
    createdAt = json['created_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedAt = json['updated_at']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['doc_no'] = docNo;
    data['asset_code'] = assetCode;
    data['cabang_code'] = cabangCode;
    data['regional_code'] = regionalCode;
    data['asset_meter_code'] = assetMeterCode;
    data['meter_reading'] = meterReading;
    data['meter_lalu'] = meterLalu;
    data['date_doc'] = dateDoc;
    data['description'] = description;
    data['time'] = time;
    data['is_delete'] = isDelete;
    data['is_reset'] = isReset;
    data['company_id'] = companyId;
    data['created_at'] = createdAt;
    data['created_by'] = createdBy;
    data['updated_at'] = updatedAt;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class OperationHoursViewModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 8120,
      "doc_no": "AM-2024-0008",
      "asset_code": "2000021020",
      "cabang_code": "CAB27",
      "regional_code": "REG05",
      "asset_meter_code": "Jam-Operasi",
      "meter_reading": 200,
      "meter_lalu": 0,
      "date_doc": "2024-02-20",
      "description": "tes",
      "time": "21:21:28",
      "is_delete": 0,
      "is_reset": 0,
      "company_id": 1,
      "created_at": 1710138105,
      "created_by": 1,
      "updated_at": 1710138105,
      "updated_by": 1
    }
  ],
  "page": 1,
  "length": 10,
  "message": "Sukses"
} 
*/

  bool? success;
  List<OperationHoursViewModelData?>? data;
  String? page;
  String? length;
  String? message;

  OperationHoursViewModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  OperationHoursViewModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <OperationHoursViewModelData>[];
      v.forEach((v) {
        arr0.add(OperationHoursViewModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['message'] = message;
    return data;
  }
}
