///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NotifikasiViewModelDataNextApprover {
/*
{
  "id": 6,
  "username": "791021026",
  "confirmation_token": null,
  "status": 1,
  "superadmin": 0,
  "created_at": 1657009971,
  "updated_at": 1694496752,
  "type": null,
  "company_id": 1,
  "personil_id": 67,
  "registration_ip": "180.247.212.150",
  "bind_to_ip": "",
  "email": "",
  "email_confirmed": 0,
  "username_centra": "setiawan",
  "password_centra": null,
  "token_centra": null,
  "valid_token": null,
  "firebase_token": null
} 
*/

  String? id;
  String? username;
  String? confirmationToken;
  String? status;
  String? superadmin;
  String? createdAt;
  String? updatedAt;
  String? type;
  String? companyId;
  String? personilId;
  String? registrationIp;
  String? bindToIp;
  String? email;
  String? emailConfirmed;
  String? usernameCentra;
  String? passwordCentra;
  String? tokenCentra;
  String? validToken;
  String? firebaseToken;

  NotifikasiViewModelDataNextApprover({
    this.id,
    this.username,
    this.confirmationToken,
    this.status,
    this.superadmin,
    this.createdAt,
    this.updatedAt,
    this.type,
    this.companyId,
    this.personilId,
    this.registrationIp,
    this.bindToIp,
    this.email,
    this.emailConfirmed,
    this.usernameCentra,
    this.passwordCentra,
    this.tokenCentra,
    this.validToken,
    this.firebaseToken,
  });
  NotifikasiViewModelDataNextApprover.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    username = json['username']?.toString();
    confirmationToken = json['confirmation_token']?.toString();
    status = json['status']?.toString();
    superadmin = json['superadmin']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    type = json['type']?.toString();
    companyId = json['company_id']?.toString();
    personilId = json['personil_id']?.toString();
    registrationIp = json['registration_ip']?.toString();
    bindToIp = json['bind_to_ip']?.toString();
    email = json['email']?.toString();
    emailConfirmed = json['email_confirmed']?.toString();
    usernameCentra = json['username_centra']?.toString();
    passwordCentra = json['password_centra']?.toString();
    tokenCentra = json['token_centra']?.toString();
    validToken = json['valid_token']?.toString();
    firebaseToken = json['firebase_token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['username'] = username;
    data['confirmation_token'] = confirmationToken;
    data['status'] = status;
    data['superadmin'] = superadmin;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['type'] = type;
    data['company_id'] = companyId;
    data['personil_id'] = personilId;
    data['registration_ip'] = registrationIp;
    data['bind_to_ip'] = bindToIp;
    data['email'] = email;
    data['email_confirmed'] = emailConfirmed;
    data['username_centra'] = usernameCentra;
    data['password_centra'] = passwordCentra;
    data['token_centra'] = tokenCentra;
    data['valid_token'] = validToken;
    data['firebase_token'] = firebaseToken;
    return data;
  }
}

class NotifikasiViewModelDataDataNextApproverUser {
/*
{
  "id": 6,
  "username": "791021026",
  "confirmation_token": null,
  "status": 1,
  "superadmin": 0,
  "created_at": 1657009971,
  "updated_at": 1694496752,
  "type": null,
  "company_id": 1,
  "personil_id": 67,
  "registration_ip": "180.247.212.150",
  "bind_to_ip": "",
  "email": "",
  "email_confirmed": 0,
  "username_centra": "setiawan",
  "password_centra": null,
  "token_centra": null,
  "valid_token": null,
  "firebase_token": null
} 
*/

  String? id;
  String? username;
  String? confirmationToken;
  String? status;
  String? superadmin;
  String? createdAt;
  String? updatedAt;
  String? type;
  String? companyId;
  String? personilId;
  String? registrationIp;
  String? bindToIp;
  String? email;
  String? emailConfirmed;
  String? usernameCentra;
  String? passwordCentra;
  String? tokenCentra;
  String? validToken;
  String? firebaseToken;

  NotifikasiViewModelDataDataNextApproverUser({
    this.id,
    this.username,
    this.confirmationToken,
    this.status,
    this.superadmin,
    this.createdAt,
    this.updatedAt,
    this.type,
    this.companyId,
    this.personilId,
    this.registrationIp,
    this.bindToIp,
    this.email,
    this.emailConfirmed,
    this.usernameCentra,
    this.passwordCentra,
    this.tokenCentra,
    this.validToken,
    this.firebaseToken,
  });
  NotifikasiViewModelDataDataNextApproverUser.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    username = json['username']?.toString();
    confirmationToken = json['confirmation_token']?.toString();
    status = json['status']?.toString();
    superadmin = json['superadmin']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    type = json['type']?.toString();
    companyId = json['company_id']?.toString();
    personilId = json['personil_id']?.toString();
    registrationIp = json['registration_ip']?.toString();
    bindToIp = json['bind_to_ip']?.toString();
    email = json['email']?.toString();
    emailConfirmed = json['email_confirmed']?.toString();
    usernameCentra = json['username_centra']?.toString();
    passwordCentra = json['password_centra']?.toString();
    tokenCentra = json['token_centra']?.toString();
    validToken = json['valid_token']?.toString();
    firebaseToken = json['firebase_token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['username'] = username;
    data['confirmation_token'] = confirmationToken;
    data['status'] = status;
    data['superadmin'] = superadmin;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['type'] = type;
    data['company_id'] = companyId;
    data['personil_id'] = personilId;
    data['registration_ip'] = registrationIp;
    data['bind_to_ip'] = bindToIp;
    data['email'] = email;
    data['email_confirmed'] = emailConfirmed;
    data['username_centra'] = usernameCentra;
    data['password_centra'] = passwordCentra;
    data['token_centra'] = tokenCentra;
    data['valid_token'] = validToken;
    data['firebase_token'] = firebaseToken;
    return data;
  }
}

class NotifikasiViewModelDataDataNextApprover {
/*
{
  "id": 29905,
  "module_id": "work-order-p",
  "doc_id": 7827,
  "apv_level": 2,
  "user_id": 6,
  "time_create": "2024-02-29 13:51:29",
  "max_level": 2,
  "user": {
    "id": 6,
    "username": "791021026",
    "confirmation_token": null,
    "status": 1,
    "superadmin": 0,
    "created_at": 1657009971,
    "updated_at": 1694496752,
    "type": null,
    "company_id": 1,
    "personil_id": 67,
    "registration_ip": "180.247.212.150",
    "bind_to_ip": "",
    "email": "",
    "email_confirmed": 0,
    "username_centra": "setiawan",
    "password_centra": null,
    "token_centra": null,
    "valid_token": null,
    "firebase_token": null
  }
} 
*/

  String? id;
  String? moduleId;
  String? docId;
  String? apvLevel;
  String? userId;
  String? timeCreate;
  String? maxLevel;
  NotifikasiViewModelDataDataNextApproverUser? user;

  NotifikasiViewModelDataDataNextApprover({
    this.id,
    this.moduleId,
    this.docId,
    this.apvLevel,
    this.userId,
    this.timeCreate,
    this.maxLevel,
    this.user,
  });
  NotifikasiViewModelDataDataNextApprover.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    moduleId = json['module_id']?.toString();
    docId = json['doc_id']?.toString();
    apvLevel = json['apv_level']?.toString();
    userId = json['user_id']?.toString();
    timeCreate = json['time_create']?.toString();
    maxLevel = json['max_level']?.toString();
    user = (json['user'] != null)
        ? NotifikasiViewModelDataDataNextApproverUser.fromJson(json['user'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['module_id'] = moduleId;
    data['doc_id'] = docId;
    data['apv_level'] = apvLevel;
    data['user_id'] = userId;
    data['time_create'] = timeCreate;
    data['max_level'] = maxLevel;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}

class NotifikasiViewModelDataDataUserCreate {
/*
{
  "id": 1,
  "username": "adminatria",
  "confirmation_token": null,
  "status": 1,
  "superadmin": 1,
  "created_at": 1599308626,
  "updated_at": 1702448766,
  "type": null,
  "company_id": 1,
  "personil_id": 737,
  "registration_ip": null,
  "bind_to_ip": "",
  "email": "it@ptbima.id",
  "email_confirmed": 0,
  "username_centra": "admin",
  "password_centra": "adminp3",
  "token_centra": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvY2VudHJhLXFhLnBlbGluZG8uY28uaWRcL3B1YmxpY1wvYXBpXC9sb2dpbi1tb2JpbGUiLCJpYXQiOjE3MDI0NDg3NjUsImV4cCI6MTczNDA3MTE2NSwibmJmIjoxNzAyNDQ4NzY1LCJqdGkiOiIxdWh1Wm9SQVJKY0IwOTBGIiwic3ViIjoxLCJwcnYiOiIwMmU5YzhmZjQxY2NlYjdlMGQyMGIyZDg0NTFkZDY2NjBkZjY2NGI1In0.vA7Hb7mZFDKDaEzz60pM4R-xpE0cY2D5JCGbUfaBOFs",
  "valid_token": 1,
  "firebase_token": "xpE0cY2D5JCGbUfaBOFs111"
} 
*/

  String? id;
  String? username;
  String? confirmationToken;
  String? status;
  String? superadmin;
  String? createdAt;
  String? updatedAt;
  String? type;
  String? companyId;
  String? personilId;
  String? registrationIp;
  String? bindToIp;
  String? email;
  String? emailConfirmed;
  String? usernameCentra;
  String? passwordCentra;
  String? tokenCentra;
  String? validToken;
  String? firebaseToken;

  NotifikasiViewModelDataDataUserCreate({
    this.id,
    this.username,
    this.confirmationToken,
    this.status,
    this.superadmin,
    this.createdAt,
    this.updatedAt,
    this.type,
    this.companyId,
    this.personilId,
    this.registrationIp,
    this.bindToIp,
    this.email,
    this.emailConfirmed,
    this.usernameCentra,
    this.passwordCentra,
    this.tokenCentra,
    this.validToken,
    this.firebaseToken,
  });
  NotifikasiViewModelDataDataUserCreate.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    username = json['username']?.toString();
    confirmationToken = json['confirmation_token']?.toString();
    status = json['status']?.toString();
    superadmin = json['superadmin']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    type = json['type']?.toString();
    companyId = json['company_id']?.toString();
    personilId = json['personil_id']?.toString();
    registrationIp = json['registration_ip']?.toString();
    bindToIp = json['bind_to_ip']?.toString();
    email = json['email']?.toString();
    emailConfirmed = json['email_confirmed']?.toString();
    usernameCentra = json['username_centra']?.toString();
    passwordCentra = json['password_centra']?.toString();
    tokenCentra = json['token_centra']?.toString();
    validToken = json['valid_token']?.toString();
    firebaseToken = json['firebase_token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['username'] = username;
    data['confirmation_token'] = confirmationToken;
    data['status'] = status;
    data['superadmin'] = superadmin;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['type'] = type;
    data['company_id'] = companyId;
    data['personil_id'] = personilId;
    data['registration_ip'] = registrationIp;
    data['bind_to_ip'] = bindToIp;
    data['email'] = email;
    data['email_confirmed'] = emailConfirmed;
    data['username_centra'] = usernameCentra;
    data['password_centra'] = passwordCentra;
    data['token_centra'] = tokenCentra;
    data['valid_token'] = validToken;
    data['firebase_token'] = firebaseToken;
    return data;
  }
}

class NotifikasiViewModelDataDataWoActivities {
/*
{
  "id": 101292,
  "workorder_id": 7827,
  "task_number": 1,
  "task_name": "test",
  "description": null,
  "type_trans": "persetujuan",
  "task_duration": "3",
  "created_at": 1709189351,
  "updated_at": 1709189351,
  "created_by": 1,
  "updated_by": 1
} 
*/

  String? id;
  String? workorderId;
  String? taskNumber;
  String? taskName;
  String? description;
  String? typeTrans;
  String? taskDuration;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  NotifikasiViewModelDataDataWoActivities({
    this.id,
    this.workorderId,
    this.taskNumber,
    this.taskName,
    this.description,
    this.typeTrans,
    this.taskDuration,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  NotifikasiViewModelDataDataWoActivities.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    workorderId = json['workorder_id']?.toString();
    taskNumber = json['task_number']?.toString();
    taskName = json['task_name']?.toString();
    description = json['description']?.toString();
    typeTrans = json['type_trans']?.toString();
    taskDuration = json['task_duration']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['workorder_id'] = workorderId;
    data['task_number'] = taskNumber;
    data['task_name'] = taskName;
    data['description'] = description;
    data['type_trans'] = typeTrans;
    data['task_duration'] = taskDuration;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class NotifikasiViewModelDataDataWoSpareparts {
/*
{
  "id": 9477,
  "workorder_id": 7827,
  "code": "AA-001-000001",
  "name": "USHA MARTIN;WIRE ROPE;25 MM;IWRC;RHOL;1960 N/MM2;6X29;GALV;0;LENGHT 960 METER",
  "quantity": 1,
  "uom": "METER",
  "type_trans": "persetujuan",
  "status": 10,
  "company_id": 1,
  "created_at": "1709189351",
  "updated_at": "1709189351",
  "created_by": "1",
  "updated_by": "1",
  "wh_code": "1100",
  "wh_name": "BENOA",
  "unit_code": "1100",
  "unit_name": "Site Benoa",
  "price": "0.00",
  "eta": "2024-02-29",
  "description": "",
  "type": null
} 
*/

  String? id;
  String? workorderId;
  String? code;
  String? name;
  String? quantity;
  String? uom;
  String? typeTrans;
  String? status;
  String? companyId;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;
  String? whCode;
  String? whName;
  String? unitCode;
  String? unitName;
  String? price;
  String? eta;
  String? description;
  String? type;

  NotifikasiViewModelDataDataWoSpareparts({
    this.id,
    this.workorderId,
    this.code,
    this.name,
    this.quantity,
    this.uom,
    this.typeTrans,
    this.status,
    this.companyId,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
    this.whCode,
    this.whName,
    this.unitCode,
    this.unitName,
    this.price,
    this.eta,
    this.description,
    this.type,
  });
  NotifikasiViewModelDataDataWoSpareparts.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    workorderId = json['workorder_id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    quantity = json['quantity']?.toString();
    uom = json['uom']?.toString();
    typeTrans = json['type_trans']?.toString();
    status = json['status']?.toString();
    companyId = json['company_id']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
    whCode = json['wh_code']?.toString();
    whName = json['wh_name']?.toString();
    unitCode = json['unit_code']?.toString();
    unitName = json['unit_name']?.toString();
    price = json['price']?.toString();
    eta = json['eta']?.toString();
    description = json['description']?.toString();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['workorder_id'] = workorderId;
    data['code'] = code;
    data['name'] = name;
    data['quantity'] = quantity;
    data['uom'] = uom;
    data['type_trans'] = typeTrans;
    data['status'] = status;
    data['company_id'] = companyId;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    data['wh_code'] = whCode;
    data['wh_name'] = whName;
    data['unit_code'] = unitCode;
    data['unit_name'] = unitName;
    data['price'] = price;
    data['eta'] = eta;
    data['description'] = description;
    data['type'] = type;
    return data;
  }
}

class NotifikasiViewModelDataDataAsset {
/*
{
  "id": 543,
  "code": "ATRIA-00001",
  "name": "Aset BIMA",
  "kapasitas": "1000",
  "merk": "BIMA",
  "country_of_origin": null,
  "equipment_serial_number": null,
  "model": null,
  "power_source": null,
  "merk_engine": null,
  "engine_type": null,
  "serial_number_engine": null,
  "jenis_asset_code": "A01",
  "regional_code": "REG05",
  "cabang_code": "CAB27",
  "tahun": 2023,
  "is_delete": 0,
  "is_downtime": 1,
  "is_active": 1,
  "company_id": 1,
  "doc_status": "Completed",
  "apv_level": 2,
  "created_at": "1692089727",
  "updated_at": "1692089727",
  "created_by": 1,
  "updated_by": 1
} 
*/

  String? id;
  String? code;
  String? name;
  String? kapasitas;
  String? merk;
  String? countryOfOrigin;
  String? equipmentSerialNumber;
  String? model;
  String? powerSource;
  String? merkEngine;
  String? engineType;
  String? serialNumberEngine;
  String? jenisAssetCode;
  String? regionalCode;
  String? cabangCode;
  String? tahun;
  String? isDelete;
  String? isDowntime;
  String? isActive;
  String? companyId;
  String? docStatus;
  String? apvLevel;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  NotifikasiViewModelDataDataAsset({
    this.id,
    this.code,
    this.name,
    this.kapasitas,
    this.merk,
    this.countryOfOrigin,
    this.equipmentSerialNumber,
    this.model,
    this.powerSource,
    this.merkEngine,
    this.engineType,
    this.serialNumberEngine,
    this.jenisAssetCode,
    this.regionalCode,
    this.cabangCode,
    this.tahun,
    this.isDelete,
    this.isDowntime,
    this.isActive,
    this.companyId,
    this.docStatus,
    this.apvLevel,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  NotifikasiViewModelDataDataAsset.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    kapasitas = json['kapasitas']?.toString();
    merk = json['merk']?.toString();
    countryOfOrigin = json['country_of_origin']?.toString();
    equipmentSerialNumber = json['equipment_serial_number']?.toString();
    model = json['model']?.toString();
    powerSource = json['power_source']?.toString();
    merkEngine = json['merk_engine']?.toString();
    engineType = json['engine_type']?.toString();
    serialNumberEngine = json['serial_number_engine']?.toString();
    jenisAssetCode = json['jenis_asset_code']?.toString();
    regionalCode = json['regional_code']?.toString();
    cabangCode = json['cabang_code']?.toString();
    tahun = json['tahun']?.toString();
    isDelete = json['is_delete']?.toString();
    isDowntime = json['is_downtime']?.toString();
    isActive = json['is_active']?.toString();
    companyId = json['company_id']?.toString();
    docStatus = json['doc_status']?.toString();
    apvLevel = json['apv_level']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    data['kapasitas'] = kapasitas;
    data['merk'] = merk;
    data['country_of_origin'] = countryOfOrigin;
    data['equipment_serial_number'] = equipmentSerialNumber;
    data['model'] = model;
    data['power_source'] = powerSource;
    data['merk_engine'] = merkEngine;
    data['engine_type'] = engineType;
    data['serial_number_engine'] = serialNumberEngine;
    data['jenis_asset_code'] = jenisAssetCode;
    data['regional_code'] = regionalCode;
    data['cabang_code'] = cabangCode;
    data['tahun'] = tahun;
    data['is_delete'] = isDelete;
    data['is_downtime'] = isDowntime;
    data['is_active'] = isActive;
    data['company_id'] = companyId;
    data['doc_status'] = docStatus;
    data['apv_level'] = apvLevel;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class NotifikasiViewModelDataData {
/*
{
  "id": 7827,
  "doc_no": "WO-2024-0000004",
  "asset_code": "ATRIA-00001",
  "asset_category_code": "A01",
  "ba_no_persetujuan": null,
  "ba_no_realisasi": null,
  "type_work": "PDM",
  "asset_meter_code": null,
  "type_trans": "persetujuan",
  "date_doc": "2024-02-29",
  "cabang_code": "CAB27",
  "regional_code": "REG05",
  "description": "",
  "doc_status": "REVIEW",
  "is_downtime": 1,
  "apv_level": 1,
  "preventive_maintanance_id": null,
  "jobplan_id": null,
  "workorder_id": null,
  "frequency_time_based": 0,
  "frequency_unit_based": null,
  "meter_reading": 0,
  "is_delete": 0,
  "company_id": 1,
  "status_part": "waiting",
  "date_start": null,
  "date_end": null,
  "created_at": 1709189351,
  "updated_at": null,
  "created_by": 1,
  "updated_by": null,
  "is_mr": 1,
  "submit_rls": null,
  "start_downtime": null,
  "up_date": null,
  "asset": {
    "id": 543,
    "code": "ATRIA-00001",
    "name": "Aset BIMA",
    "kapasitas": "1000",
    "merk": "BIMA",
    "country_of_origin": null,
    "equipment_serial_number": null,
    "model": null,
    "power_source": null,
    "merk_engine": null,
    "engine_type": null,
    "serial_number_engine": null,
    "jenis_asset_code": "A01",
    "regional_code": "REG05",
    "cabang_code": "CAB27",
    "tahun": 2023,
    "is_delete": 0,
    "is_downtime": 1,
    "is_active": 1,
    "company_id": 1,
    "doc_status": "Completed",
    "apv_level": 2,
    "created_at": "1692089727",
    "updated_at": "1692089727",
    "created_by": 1,
    "updated_by": 1
  },
  "wo_spareparts": [
    {
      "id": 9477,
      "workorder_id": 7827,
      "code": "AA-001-000001",
      "name": "USHA MARTIN;WIRE ROPE;25 MM;IWRC;RHOL;1960 N/MM2;6X29;GALV;0;LENGHT 960 METER",
      "quantity": 1,
      "uom": "METER",
      "type_trans": "persetujuan",
      "status": 10,
      "company_id": 1,
      "created_at": "1709189351",
      "updated_at": "1709189351",
      "created_by": "1",
      "updated_by": "1",
      "wh_code": "1100",
      "wh_name": "BENOA",
      "unit_code": "1100",
      "unit_name": "Site Benoa",
      "price": "0.00",
      "eta": "2024-02-29",
      "description": "",
      "type": null
    }
  ],
  "wo_activities": [
    {
      "id": 101292,
      "workorder_id": 7827,
      "task_number": 1,
      "task_name": "test",
      "description": null,
      "type_trans": "persetujuan",
      "task_duration": "3",
      "created_at": 1709189351,
      "updated_at": 1709189351,
      "created_by": 1,
      "updated_by": 1
    }
  ],
  "wo_failures": [
    null
  ],
  "wo_files": [
    null
  ],
  "wo_labours": [
    null
  ],
  "wo_progress": [
    null
  ],
  "wo_services": [
    null
  ],
  "wo_tools": [
    null
  ],
  "user_create": {
    "id": 1,
    "username": "adminatria",
    "confirmation_token": null,
    "status": 1,
    "superadmin": 1,
    "created_at": 1599308626,
    "updated_at": 1702448766,
    "type": null,
    "company_id": 1,
    "personil_id": 737,
    "registration_ip": null,
    "bind_to_ip": "",
    "email": "it@ptbima.id",
    "email_confirmed": 0,
    "username_centra": "admin",
    "password_centra": "adminp3",
    "token_centra": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvY2VudHJhLXFhLnBlbGluZG8uY28uaWRcL3B1YmxpY1wvYXBpXC9sb2dpbi1tb2JpbGUiLCJpYXQiOjE3MDI0NDg3NjUsImV4cCI6MTczNDA3MTE2NSwibmJmIjoxNzAyNDQ4NzY1LCJqdGkiOiIxdWh1Wm9SQVJKY0IwOTBGIiwic3ViIjoxLCJwcnYiOiIwMmU5YzhmZjQxY2NlYjdlMGQyMGIyZDg0NTFkZDY2NjBkZjY2NGI1In0.vA7Hb7mZFDKDaEzz60pM4R-xpE0cY2D5JCGbUfaBOFs",
    "valid_token": 1,
    "firebase_token": "xpE0cY2D5JCGbUfaBOFs111"
  },
  "next_approver": {
    "id": 29905,
    "module_id": "work-order-p",
    "doc_id": 7827,
    "apv_level": 2,
    "user_id": 6,
    "time_create": "2024-02-29 13:51:29",
    "max_level": 2,
    "user": {
      "id": 6,
      "username": "791021026",
      "confirmation_token": null,
      "status": 1,
      "superadmin": 0,
      "created_at": 1657009971,
      "updated_at": 1694496752,
      "type": null,
      "company_id": 1,
      "personil_id": 67,
      "registration_ip": "180.247.212.150",
      "bind_to_ip": "",
      "email": "",
      "email_confirmed": 0,
      "username_centra": "setiawan",
      "password_centra": null,
      "token_centra": null,
      "valid_token": null,
      "firebase_token": null
    }
  }
} 
*/

  String? id;
  String? docNo;
  String? assetCode;
  String? assetCategoryCode;
  String? baNoPersetujuan;
  String? baNoRealisasi;
  String? typeWork;
  String? assetMeterCode;
  String? typeTrans;
  String? dateDoc;
  String? cabangCode;
  String? regionalCode;
  String? description;
  String? docStatus;
  String? isDowntime;
  String? apvLevel;
  String? preventiveMaintananceId;
  String? jobplanId;
  String? workorderId;
  String? frequencyTimeBased;
  String? frequencyUnitBased;
  String? meterReading;
  String? isDelete;
  String? companyId;
  String? statusPart;
  String? dateStart;
  String? dateEnd;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;
  String? isMr;
  String? submitRls;
  String? startDowntime;
  String? upDate;
  NotifikasiViewModelDataDataAsset? asset;
  List<NotifikasiViewModelDataDataWoSpareparts?>? woSpareparts;
  List<NotifikasiViewModelDataDataWoActivities?>? woActivities;
  List<String?>? woFailures;
  List<String?>? woFiles;
  List<String?>? woLabours;
  List<String?>? woProgress;
  List<String?>? woServices;
  List<String?>? woTools;
  NotifikasiViewModelDataDataUserCreate? userCreate;
  NotifikasiViewModelDataDataNextApprover? nextApprover;

  NotifikasiViewModelDataData({
    this.id,
    this.docNo,
    this.assetCode,
    this.assetCategoryCode,
    this.baNoPersetujuan,
    this.baNoRealisasi,
    this.typeWork,
    this.assetMeterCode,
    this.typeTrans,
    this.dateDoc,
    this.cabangCode,
    this.regionalCode,
    this.description,
    this.docStatus,
    this.isDowntime,
    this.apvLevel,
    this.preventiveMaintananceId,
    this.jobplanId,
    this.workorderId,
    this.frequencyTimeBased,
    this.frequencyUnitBased,
    this.meterReading,
    this.isDelete,
    this.companyId,
    this.statusPart,
    this.dateStart,
    this.dateEnd,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
    this.isMr,
    this.submitRls,
    this.startDowntime,
    this.upDate,
    this.asset,
    this.woSpareparts,
    this.woActivities,
    this.woFailures,
    this.woFiles,
    this.woLabours,
    this.woProgress,
    this.woServices,
    this.woTools,
    this.userCreate,
    this.nextApprover,
  });
  NotifikasiViewModelDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    docNo = json['doc_no']?.toString();
    assetCode = json['asset_code']?.toString();
    assetCategoryCode = json['asset_category_code']?.toString();
    baNoPersetujuan = json['ba_no_persetujuan']?.toString();
    baNoRealisasi = json['ba_no_realisasi']?.toString();
    typeWork = json['type_work']?.toString();
    assetMeterCode = json['asset_meter_code']?.toString();
    typeTrans = json['type_trans']?.toString();
    dateDoc = json['date_doc']?.toString();
    cabangCode = json['cabang_code']?.toString();
    regionalCode = json['regional_code']?.toString();
    description = json['description']?.toString();
    docStatus = json['doc_status']?.toString();
    isDowntime = json['is_downtime']?.toString();
    apvLevel = json['apv_level']?.toString();
    preventiveMaintananceId = json['preventive_maintanance_id']?.toString();
    jobplanId = json['jobplan_id']?.toString();
    workorderId = json['workorder_id']?.toString();
    frequencyTimeBased = json['frequency_time_based']?.toString();
    frequencyUnitBased = json['frequency_unit_based']?.toString();
    meterReading = json['meter_reading']?.toString();
    isDelete = json['is_delete']?.toString();
    companyId = json['company_id']?.toString();
    statusPart = json['status_part']?.toString();
    dateStart = json['date_start']?.toString();
    dateEnd = json['date_end']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
    isMr = json['is_mr']?.toString();
    submitRls = json['submit_rls']?.toString();
    startDowntime = json['start_downtime']?.toString();
    upDate = json['up_date']?.toString();
    asset = (json['asset'] != null)
        ? NotifikasiViewModelDataDataAsset.fromJson(json['asset'])
        : null;
    if (json['wo_spareparts'] != null) {
      final v = json['wo_spareparts'];
      final arr0 = <NotifikasiViewModelDataDataWoSpareparts>[];
      v.forEach((v) {
        arr0.add(NotifikasiViewModelDataDataWoSpareparts.fromJson(v));
      });
      woSpareparts = arr0;
    }
    if (json['wo_activities'] != null) {
      final v = json['wo_activities'];
      final arr0 = <NotifikasiViewModelDataDataWoActivities>[];
      v.forEach((v) {
        arr0.add(NotifikasiViewModelDataDataWoActivities.fromJson(v));
      });
      woActivities = arr0;
    }

    userCreate = (json['user_create'] != null)
        ? NotifikasiViewModelDataDataUserCreate.fromJson(json['user_create'])
        : null;
    nextApprover = (json['next_approver'] != null)
        ? NotifikasiViewModelDataDataNextApprover.fromJson(
            json['next_approver'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['doc_no'] = docNo;
    data['asset_code'] = assetCode;
    data['asset_category_code'] = assetCategoryCode;
    data['ba_no_persetujuan'] = baNoPersetujuan;
    data['ba_no_realisasi'] = baNoRealisasi;
    data['type_work'] = typeWork;
    data['asset_meter_code'] = assetMeterCode;
    data['type_trans'] = typeTrans;
    data['date_doc'] = dateDoc;
    data['cabang_code'] = cabangCode;
    data['regional_code'] = regionalCode;
    data['description'] = description;
    data['doc_status'] = docStatus;
    data['is_downtime'] = isDowntime;
    data['apv_level'] = apvLevel;
    data['preventive_maintanance_id'] = preventiveMaintananceId;
    data['jobplan_id'] = jobplanId;
    data['workorder_id'] = workorderId;
    data['frequency_time_based'] = frequencyTimeBased;
    data['frequency_unit_based'] = frequencyUnitBased;
    data['meter_reading'] = meterReading;
    data['is_delete'] = isDelete;
    data['company_id'] = companyId;
    data['status_part'] = statusPart;
    data['date_start'] = dateStart;
    data['date_end'] = dateEnd;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    data['is_mr'] = isMr;
    data['submit_rls'] = submitRls;
    data['start_downtime'] = startDowntime;
    data['up_date'] = upDate;
    if (asset != null) {
      data['asset'] = asset!.toJson();
    }
    if (woSpareparts != null) {
      final v = woSpareparts;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['wo_spareparts'] = arr0;
    }
    if (woActivities != null) {
      final v = woActivities;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['wo_activities'] = arr0;
    }

    if (userCreate != null) {
      data['user_create'] = userCreate!.toJson();
    }
    if (nextApprover != null) {
      data['next_approver'] = nextApprover!.toJson();
    }
    return data;
  }
}

class NotifikasiViewModelData {
/*
{
  "pdfFile": "http://bimops-api.erdata.id/storage/pdf/notif/QmltYXlpaTI3ODI3.pdf",
  "data": {
    "id": 7827,
    "doc_no": "WO-2024-0000004",
    "asset_code": "ATRIA-00001",
    "asset_category_code": "A01",
    "ba_no_persetujuan": null,
    "ba_no_realisasi": null,
    "type_work": "PDM",
    "asset_meter_code": null,
    "type_trans": "persetujuan",
    "date_doc": "2024-02-29",
    "cabang_code": "CAB27",
    "regional_code": "REG05",
    "description": "",
    "doc_status": "REVIEW",
    "is_downtime": 1,
    "apv_level": 1,
    "preventive_maintanance_id": null,
    "jobplan_id": null,
    "workorder_id": null,
    "frequency_time_based": 0,
    "frequency_unit_based": null,
    "meter_reading": 0,
    "is_delete": 0,
    "company_id": 1,
    "status_part": "waiting",
    "date_start": null,
    "date_end": null,
    "created_at": 1709189351,
    "updated_at": null,
    "created_by": 1,
    "updated_by": null,
    "is_mr": 1,
    "submit_rls": null,
    "start_downtime": null,
    "up_date": null,
    "asset": {
      "id": 543,
      "code": "ATRIA-00001",
      "name": "Aset BIMA",
      "kapasitas": "1000",
      "merk": "BIMA",
      "country_of_origin": null,
      "equipment_serial_number": null,
      "model": null,
      "power_source": null,
      "merk_engine": null,
      "engine_type": null,
      "serial_number_engine": null,
      "jenis_asset_code": "A01",
      "regional_code": "REG05",
      "cabang_code": "CAB27",
      "tahun": 2023,
      "is_delete": 0,
      "is_downtime": 1,
      "is_active": 1,
      "company_id": 1,
      "doc_status": "Completed",
      "apv_level": 2,
      "created_at": "1692089727",
      "updated_at": "1692089727",
      "created_by": 1,
      "updated_by": 1
    },
    "wo_spareparts": [
      {
        "id": 9477,
        "workorder_id": 7827,
        "code": "AA-001-000001",
        "name": "USHA MARTIN;WIRE ROPE;25 MM;IWRC;RHOL;1960 N/MM2;6X29;GALV;0;LENGHT 960 METER",
        "quantity": 1,
        "uom": "METER",
        "type_trans": "persetujuan",
        "status": 10,
        "company_id": 1,
        "created_at": "1709189351",
        "updated_at": "1709189351",
        "created_by": "1",
        "updated_by": "1",
        "wh_code": "1100",
        "wh_name": "BENOA",
        "unit_code": "1100",
        "unit_name": "Site Benoa",
        "price": "0.00",
        "eta": "2024-02-29",
        "description": "",
        "type": null
      }
    ],
    "wo_activities": [
      {
        "id": 101292,
        "workorder_id": 7827,
        "task_number": 1,
        "task_name": "test",
        "description": null,
        "type_trans": "persetujuan",
        "task_duration": "3",
        "created_at": 1709189351,
        "updated_at": 1709189351,
        "created_by": 1,
        "updated_by": 1
      }
    ],
    "wo_failures": [
      null
    ],
    "wo_files": [
      null
    ],
    "wo_labours": [
      null
    ],
    "wo_progress": [
      null
    ],
    "wo_services": [
      null
    ],
    "wo_tools": [
      null
    ],
    "user_create": {
      "id": 1,
      "username": "adminatria",
      "confirmation_token": null,
      "status": 1,
      "superadmin": 1,
      "created_at": 1599308626,
      "updated_at": 1702448766,
      "type": null,
      "company_id": 1,
      "personil_id": 737,
      "registration_ip": null,
      "bind_to_ip": "",
      "email": "it@ptbima.id",
      "email_confirmed": 0,
      "username_centra": "admin",
      "password_centra": "adminp3",
      "token_centra": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvY2VudHJhLXFhLnBlbGluZG8uY28uaWRcL3B1YmxpY1wvYXBpXC9sb2dpbi1tb2JpbGUiLCJpYXQiOjE3MDI0NDg3NjUsImV4cCI6MTczNDA3MTE2NSwibmJmIjoxNzAyNDQ4NzY1LCJqdGkiOiIxdWh1Wm9SQVJKY0IwOTBGIiwic3ViIjoxLCJwcnYiOiIwMmU5YzhmZjQxY2NlYjdlMGQyMGIyZDg0NTFkZDY2NjBkZjY2NGI1In0.vA7Hb7mZFDKDaEzz60pM4R-xpE0cY2D5JCGbUfaBOFs",
      "valid_token": 1,
      "firebase_token": "xpE0cY2D5JCGbUfaBOFs111"
    },
    "next_approver": {
      "id": 29905,
      "module_id": "work-order-p",
      "doc_id": 7827,
      "apv_level": 2,
      "user_id": 6,
      "time_create": "2024-02-29 13:51:29",
      "max_level": 2,
      "user": {
        "id": 6,
        "username": "791021026",
        "confirmation_token": null,
        "status": 1,
        "superadmin": 0,
        "created_at": 1657009971,
        "updated_at": 1694496752,
        "type": null,
        "company_id": 1,
        "personil_id": 67,
        "registration_ip": "180.247.212.150",
        "bind_to_ip": "",
        "email": "",
        "email_confirmed": 0,
        "username_centra": "setiawan",
        "password_centra": null,
        "token_centra": null,
        "valid_token": null,
        "firebase_token": null
      }
    }
  },
  "nextApprover": {
    "id": 6,
    "username": "791021026",
    "confirmation_token": null,
    "status": 1,
    "superadmin": 0,
    "created_at": 1657009971,
    "updated_at": 1694496752,
    "type": null,
    "company_id": 1,
    "personil_id": 67,
    "registration_ip": "180.247.212.150",
    "bind_to_ip": "",
    "email": "",
    "email_confirmed": 0,
    "username_centra": "setiawan",
    "password_centra": null,
    "token_centra": null,
    "valid_token": null,
    "firebase_token": null
  }
} 
*/

  String? pdfFile;
  NotifikasiViewModelDataData? data;
  NotifikasiViewModelDataNextApprover? nextApprover;

  NotifikasiViewModelData({
    this.pdfFile,
    this.data,
    this.nextApprover,
  });
  NotifikasiViewModelData.fromJson(Map<String, dynamic> json) {
    pdfFile = json['pdfFile']?.toString();
    data = (json['data'] != null)
        ? NotifikasiViewModelDataData.fromJson(json['data'])
        : null;
    nextApprover = (json['nextApprover'] != null)
        ? NotifikasiViewModelDataNextApprover.fromJson(json['nextApprover'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pdfFile'] = pdfFile;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    if (nextApprover != null) {
      data['nextApprover'] = nextApprover!.toJson();
    }
    return data;
  }
}

class NotifikasiViewModel {
/*
{
  "success": true,
  "data": {
    "pdfFile": "http://bimops-api.erdata.id/storage/pdf/notif/QmltYXlpaTI3ODI3.pdf",
    "data": {
      "id": 7827,
      "doc_no": "WO-2024-0000004",
      "asset_code": "ATRIA-00001",
      "asset_category_code": "A01",
      "ba_no_persetujuan": null,
      "ba_no_realisasi": null,
      "type_work": "PDM",
      "asset_meter_code": null,
      "type_trans": "persetujuan",
      "date_doc": "2024-02-29",
      "cabang_code": "CAB27",
      "regional_code": "REG05",
      "description": "",
      "doc_status": "REVIEW",
      "is_downtime": 1,
      "apv_level": 1,
      "preventive_maintanance_id": null,
      "jobplan_id": null,
      "workorder_id": null,
      "frequency_time_based": 0,
      "frequency_unit_based": null,
      "meter_reading": 0,
      "is_delete": 0,
      "company_id": 1,
      "status_part": "waiting",
      "date_start": null,
      "date_end": null,
      "created_at": 1709189351,
      "updated_at": null,
      "created_by": 1,
      "updated_by": null,
      "is_mr": 1,
      "submit_rls": null,
      "start_downtime": null,
      "up_date": null,
      "asset": {
        "id": 543,
        "code": "ATRIA-00001",
        "name": "Aset BIMA",
        "kapasitas": "1000",
        "merk": "BIMA",
        "country_of_origin": null,
        "equipment_serial_number": null,
        "model": null,
        "power_source": null,
        "merk_engine": null,
        "engine_type": null,
        "serial_number_engine": null,
        "jenis_asset_code": "A01",
        "regional_code": "REG05",
        "cabang_code": "CAB27",
        "tahun": 2023,
        "is_delete": 0,
        "is_downtime": 1,
        "is_active": 1,
        "company_id": 1,
        "doc_status": "Completed",
        "apv_level": 2,
        "created_at": "1692089727",
        "updated_at": "1692089727",
        "created_by": 1,
        "updated_by": 1
      },
      "wo_spareparts": [
        {
          "id": 9477,
          "workorder_id": 7827,
          "code": "AA-001-000001",
          "name": "USHA MARTIN;WIRE ROPE;25 MM;IWRC;RHOL;1960 N/MM2;6X29;GALV;0;LENGHT 960 METER",
          "quantity": 1,
          "uom": "METER",
          "type_trans": "persetujuan",
          "status": 10,
          "company_id": 1,
          "created_at": "1709189351",
          "updated_at": "1709189351",
          "created_by": "1",
          "updated_by": "1",
          "wh_code": "1100",
          "wh_name": "BENOA",
          "unit_code": "1100",
          "unit_name": "Site Benoa",
          "price": "0.00",
          "eta": "2024-02-29",
          "description": "",
          "type": null
        }
      ],
      "wo_activities": [
        {
          "id": 101292,
          "workorder_id": 7827,
          "task_number": 1,
          "task_name": "test",
          "description": null,
          "type_trans": "persetujuan",
          "task_duration": "3",
          "created_at": 1709189351,
          "updated_at": 1709189351,
          "created_by": 1,
          "updated_by": 1
        }
      ],
      "wo_failures": [
        null
      ],
      "wo_files": [
        null
      ],
      "wo_labours": [
        null
      ],
      "wo_progress": [
        null
      ],
      "wo_services": [
        null
      ],
      "wo_tools": [
        null
      ],
      "user_create": {
        "id": 1,
        "username": "adminatria",
        "confirmation_token": null,
        "status": 1,
        "superadmin": 1,
        "created_at": 1599308626,
        "updated_at": 1702448766,
        "type": null,
        "company_id": 1,
        "personil_id": 737,
        "registration_ip": null,
        "bind_to_ip": "",
        "email": "it@ptbima.id",
        "email_confirmed": 0,
        "username_centra": "admin",
        "password_centra": "adminp3",
        "token_centra": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvY2VudHJhLXFhLnBlbGluZG8uY28uaWRcL3B1YmxpY1wvYXBpXC9sb2dpbi1tb2JpbGUiLCJpYXQiOjE3MDI0NDg3NjUsImV4cCI6MTczNDA3MTE2NSwibmJmIjoxNzAyNDQ4NzY1LCJqdGkiOiIxdWh1Wm9SQVJKY0IwOTBGIiwic3ViIjoxLCJwcnYiOiIwMmU5YzhmZjQxY2NlYjdlMGQyMGIyZDg0NTFkZDY2NjBkZjY2NGI1In0.vA7Hb7mZFDKDaEzz60pM4R-xpE0cY2D5JCGbUfaBOFs",
        "valid_token": 1,
        "firebase_token": "xpE0cY2D5JCGbUfaBOFs111"
      },
      "next_approver": {
        "id": 29905,
        "module_id": "work-order-p",
        "doc_id": 7827,
        "apv_level": 2,
        "user_id": 6,
        "time_create": "2024-02-29 13:51:29",
        "max_level": 2,
        "user": {
          "id": 6,
          "username": "791021026",
          "confirmation_token": null,
          "status": 1,
          "superadmin": 0,
          "created_at": 1657009971,
          "updated_at": 1694496752,
          "type": null,
          "company_id": 1,
          "personil_id": 67,
          "registration_ip": "180.247.212.150",
          "bind_to_ip": "",
          "email": "",
          "email_confirmed": 0,
          "username_centra": "setiawan",
          "password_centra": null,
          "token_centra": null,
          "valid_token": null,
          "firebase_token": null
        }
      }
    },
    "nextApprover": {
      "id": 6,
      "username": "791021026",
      "confirmation_token": null,
      "status": 1,
      "superadmin": 0,
      "created_at": 1657009971,
      "updated_at": 1694496752,
      "type": null,
      "company_id": 1,
      "personil_id": 67,
      "registration_ip": "180.247.212.150",
      "bind_to_ip": "",
      "email": "",
      "email_confirmed": 0,
      "username_centra": "setiawan",
      "password_centra": null,
      "token_centra": null,
      "valid_token": null,
      "firebase_token": null
    }
  },
  "message": "Sukses"
} 
*/

  bool? success;
  NotifikasiViewModelData? data;
  String? message;

  NotifikasiViewModel({
    this.success,
    this.data,
    this.message,
  });
  NotifikasiViewModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? NotifikasiViewModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
