///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NotifCountModel {
/*
{
  "success": true,
  "data": 3,
  "message": "Sukses"
} 
*/

  bool? success;
  String? data;
  String? message;

  NotifCountModel({
    this.success,
    this.data,
    this.message,
  });
  NotifCountModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = json['data']?.toString();
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['data'] = this.data;
    data['message'] = message;
    return data;
  }
}
