///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReportModelDataWoTools {
/*
{
  "id": 31629,
  "workorder_id": 7848,
  "tools_id": 1517,
  "quantity": 2,
  "company_id": 1,
  "uom": "PCS",
  "created_at": 1711012799,
  "updated_at": 1711012799,
  "created_by": 1,
  "updated_by": 1
} 
*/

  String? id;
  String? workorderId;
  String? toolsId;
  String? quantity;
  String? companyId;
  String? uom;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  ReportModelDataWoTools({
    this.id,
    this.workorderId,
    this.toolsId,
    this.quantity,
    this.companyId,
    this.uom,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  ReportModelDataWoTools.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    workorderId = json['workorder_id']?.toString();
    toolsId = json['tools_id']?.toString();
    quantity = json['quantity']?.toString();
    companyId = json['company_id']?.toString();
    uom = json['uom']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['workorder_id'] = workorderId;
    data['tools_id'] = toolsId;
    data['quantity'] = quantity;
    data['company_id'] = companyId;
    data['uom'] = uom;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class ReportModelDataWoServices {
/*
{
  "id": 176,
  "workorder_id": 7848,
  "service_id": "DE-017-000001",
  "qty": 1,
  "type_trans": "persetujuan",
  "created_at": 1711012799,
  "updated_at": 1711012799,
  "created_by": 1,
  "updated_by": 1
} 
*/

  String? id;
  String? workorderId;
  String? serviceId;
  String? qty;
  String? typeTrans;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  ReportModelDataWoServices({
    this.id,
    this.workorderId,
    this.serviceId,
    this.qty,
    this.typeTrans,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  ReportModelDataWoServices.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    workorderId = json['workorder_id']?.toString();
    serviceId = json['service_id']?.toString();
    qty = json['qty']?.toString();
    typeTrans = json['type_trans']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['workorder_id'] = workorderId;
    data['service_id'] = serviceId;
    data['qty'] = qty;
    data['type_trans'] = typeTrans;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class ReportModelDataWoLabours {
/*
{
  "id": 26216,
  "workorder_id": 7848,
  "craft": 1,
  "personil": null,
  "skill": 6,
  "amount": "1",
  "created_at": 1711012799,
  "updated_at": 1711012799,
  "created_by": 1,
  "updated_by": 1
} 
*/

  String? id;
  String? workorderId;
  String? craft;
  String? personil;
  String? skill;
  String? amount;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  ReportModelDataWoLabours({
    this.id,
    this.workorderId,
    this.craft,
    this.personil,
    this.skill,
    this.amount,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  ReportModelDataWoLabours.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    workorderId = json['workorder_id']?.toString();
    craft = json['craft']?.toString();
    personil = json['personil']?.toString();
    skill = json['skill']?.toString();
    amount = json['amount']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['workorder_id'] = workorderId;
    data['craft'] = craft;
    data['personil'] = personil;
    data['skill'] = skill;
    data['amount'] = amount;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class ReportModelDataWoFiles {
/*
{
  "id": 12049,
  "workorder_id": 7848,
  "type_trans": "persetujuan",
  "keterangan": "Keterangan",
  "status": null,
  "file": "attachment/inY4e94sCElTLoleNqhAMP836fsseKuA.png",
  "file_name": "Businessmans hand holding question mark 1.png",
  "created_at": 1710909093,
  "updated_at": 1710909093,
  "created_by": 1,
  "updated_by": 1
} 
*/

  String? id;
  String? workorderId;
  String? typeTrans;
  String? keterangan;
  String? status;
  String? file;
  String? fileName;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  ReportModelDataWoFiles({
    this.id,
    this.workorderId,
    this.typeTrans,
    this.keterangan,
    this.status,
    this.file,
    this.fileName,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  ReportModelDataWoFiles.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    workorderId = json['workorder_id']?.toString();
    typeTrans = json['type_trans']?.toString();
    keterangan = json['keterangan']?.toString();
    status = json['status']?.toString();
    file = json['file']?.toString();
    fileName = json['file_name']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['workorder_id'] = workorderId;
    data['type_trans'] = typeTrans;
    data['keterangan'] = keterangan;
    data['status'] = status;
    data['file'] = file;
    data['file_name'] = fileName;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class ReportModelDataWoActivities {
/*
{
  "id": 101763,
  "workorder_id": 7848,
  "task_number": 1,
  "task_name": "Bongkar mesin",
  "description": null,
  "type_trans": "persetujuan",
  "task_duration": "2",
  "created_at": 1711012799,
  "updated_at": 1711012799,
  "created_by": 1,
  "updated_by": 1
} 
*/

  String? id;
  String? workorderId;
  String? taskNumber;
  String? taskName;
  String? description;
  String? typeTrans;
  String? taskDuration;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  ReportModelDataWoActivities({
    this.id,
    this.workorderId,
    this.taskNumber,
    this.taskName,
    this.description,
    this.typeTrans,
    this.taskDuration,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  ReportModelDataWoActivities.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    workorderId = json['workorder_id']?.toString();
    taskNumber = json['task_number']?.toString();
    taskName = json['task_name']?.toString();
    description = json['description']?.toString();
    typeTrans = json['type_trans']?.toString();
    taskDuration = json['task_duration']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['workorder_id'] = workorderId;
    data['task_number'] = taskNumber;
    data['task_name'] = taskName;
    data['description'] = description;
    data['type_trans'] = typeTrans;
    data['task_duration'] = taskDuration;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class ReportModelDataWoSpareparts {
/*
{
  "id": 9578,
  "workorder_id": 7848,
  "code": "AA-001-000001",
  "name": "USHA MARTIN;WIRE ROPE;25 MM;IWRC;RHOL;1960 N/MM2;6X29;GALV;0;LENGHT 960 METER",
  "quantity": 1,
  "uom": "METER",
  "type_trans": "persetujuan",
  "status": 10,
  "company_id": 1,
  "created_at": "1711012799",
  "updated_at": "1711012799",
  "created_by": "1",
  "updated_by": "1",
  "wh_code": "1200",
  "wh_name": "KUPANG",
  "unit_code": "1200",
  "unit_name": "Site Kupang",
  "price": "12000.00",
  "eta": "2024-03-20",
  "description": "",
  "type": null
} 
*/

  String? id;
  String? workorderId;
  String? code;
  String? name;
  String? quantity;
  String? uom;
  String? typeTrans;
  String? status;
  String? companyId;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;
  String? whCode;
  String? whName;
  String? unitCode;
  String? unitName;
  String? price;
  String? eta;
  String? description;
  String? type;

  ReportModelDataWoSpareparts({
    this.id,
    this.workorderId,
    this.code,
    this.name,
    this.quantity,
    this.uom,
    this.typeTrans,
    this.status,
    this.companyId,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
    this.whCode,
    this.whName,
    this.unitCode,
    this.unitName,
    this.price,
    this.eta,
    this.description,
    this.type,
  });
  ReportModelDataWoSpareparts.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    workorderId = json['workorder_id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    quantity = json['quantity']?.toString();
    uom = json['uom']?.toString();
    typeTrans = json['type_trans']?.toString();
    status = json['status']?.toString();
    companyId = json['company_id']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
    whCode = json['wh_code']?.toString();
    whName = json['wh_name']?.toString();
    unitCode = json['unit_code']?.toString();
    unitName = json['unit_name']?.toString();
    price = json['price']?.toString();
    eta = json['eta']?.toString();
    description = json['description']?.toString();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['workorder_id'] = workorderId;
    data['code'] = code;
    data['name'] = name;
    data['quantity'] = quantity;
    data['uom'] = uom;
    data['type_trans'] = typeTrans;
    data['status'] = status;
    data['company_id'] = companyId;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    data['wh_code'] = whCode;
    data['wh_name'] = whName;
    data['unit_code'] = unitCode;
    data['unit_name'] = unitName;
    data['price'] = price;
    data['eta'] = eta;
    data['description'] = description;
    data['type'] = type;
    return data;
  }
}

class ReportModelDataRegional {
/*
{
  "id": 2,
  "code": "REG02",
  "name": "SPTP",
  "description": "SUBHOLDING PELINDO TERMINAL PETIKEMAS",
  "is_delete": 0,
  "created_date": null,
  "created_by": null,
  "updated_date": null,
  "updated_by": null
} 
*/

  String? id;
  String? code;
  String? name;
  String? description;
  String? isDelete;
  String? createdDate;
  String? createdBy;
  String? updatedDate;
  String? updatedBy;

  ReportModelDataRegional({
    this.id,
    this.code,
    this.name,
    this.description,
    this.isDelete,
    this.createdDate,
    this.createdBy,
    this.updatedDate,
    this.updatedBy,
  });
  ReportModelDataRegional.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    isDelete = json['is_delete']?.toString();
    createdDate = json['created_date']?.toString();
    createdBy = json['created_by']?.toString();
    updatedDate = json['updated_date']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    data['description'] = description;
    data['is_delete'] = isDelete;
    data['created_date'] = createdDate;
    data['created_by'] = createdBy;
    data['updated_date'] = updatedDate;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class ReportModelDataUserCreate {
/*
{
  "id": 1,
  "username": "adminatria",
  "confirmation_token": null,
  "status": 1,
  "superadmin": 1,
  "created_at": 1599308626,
  "updated_at": 1702448766,
  "type": null,
  "company_id": 1,
  "personil_id": 737,
  "registration_ip": null,
  "bind_to_ip": "",
  "email": "it@ptbima.id",
  "email_confirmed": 0,
  "username_centra": "admin",
  "password_centra": "adminp3",
  "token_centra": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvY2VudHJhLXFhLnBlbGluZG8uY28uaWRcL3B1YmxpY1wvYXBpXC9sb2dpbi1tb2JpbGUiLCJpYXQiOjE3MDI0NDg3NjUsImV4cCI6MTczNDA3MTE2NSwibmJmIjoxNzAyNDQ4NzY1LCJqdGkiOiIxdWh1Wm9SQVJKY0IwOTBGIiwic3ViIjoxLCJwcnYiOiIwMmU5YzhmZjQxY2NlYjdlMGQyMGIyZDg0NTFkZDY2NjBkZjY2NGI1In0.vA7Hb7mZFDKDaEzz60pM4R-xpE0cY2D5JCGbUfaBOFs",
  "valid_token": 1,
  "firebase_token": "xpE0cY2D5JCGbUfaBOFs111"
} 
*/

  String? id;
  String? username;
  String? confirmationToken;
  String? status;
  String? superadmin;
  String? createdAt;
  String? updatedAt;
  String? type;
  String? companyId;
  String? personilId;
  String? registrationIp;
  String? bindToIp;
  String? email;
  String? emailConfirmed;
  String? usernameCentra;
  String? passwordCentra;
  String? tokenCentra;
  String? validToken;
  String? firebaseToken;

  ReportModelDataUserCreate({
    this.id,
    this.username,
    this.confirmationToken,
    this.status,
    this.superadmin,
    this.createdAt,
    this.updatedAt,
    this.type,
    this.companyId,
    this.personilId,
    this.registrationIp,
    this.bindToIp,
    this.email,
    this.emailConfirmed,
    this.usernameCentra,
    this.passwordCentra,
    this.tokenCentra,
    this.validToken,
    this.firebaseToken,
  });
  ReportModelDataUserCreate.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    username = json['username']?.toString();
    confirmationToken = json['confirmation_token']?.toString();
    status = json['status']?.toString();
    superadmin = json['superadmin']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    type = json['type']?.toString();
    companyId = json['company_id']?.toString();
    personilId = json['personil_id']?.toString();
    registrationIp = json['registration_ip']?.toString();
    bindToIp = json['bind_to_ip']?.toString();
    email = json['email']?.toString();
    emailConfirmed = json['email_confirmed']?.toString();
    usernameCentra = json['username_centra']?.toString();
    passwordCentra = json['password_centra']?.toString();
    tokenCentra = json['token_centra']?.toString();
    validToken = json['valid_token']?.toString();
    firebaseToken = json['firebase_token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['username'] = username;
    data['confirmation_token'] = confirmationToken;
    data['status'] = status;
    data['superadmin'] = superadmin;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['type'] = type;
    data['company_id'] = companyId;
    data['personil_id'] = personilId;
    data['registration_ip'] = registrationIp;
    data['bind_to_ip'] = bindToIp;
    data['email'] = email;
    data['email_confirmed'] = emailConfirmed;
    data['username_centra'] = usernameCentra;
    data['password_centra'] = passwordCentra;
    data['token_centra'] = tokenCentra;
    data['valid_token'] = validToken;
    data['firebase_token'] = firebaseToken;
    return data;
  }
}

class ReportModelDataCabang {
/*
{
  "id": 27,
  "regional_code": "REG02",
  "code": "CAB27",
  "name": "KANTOR PUSAT",
  "description": "KANTOR PUSAT PT BIMA",
  "regional_name": "ANAK PERUSAHAAN",
  "is_delete": 0,
  "created_at": null,
  "created_by": null,
  "updated_at": 1698287966,
  "updated_by": 747,
  "unit_centra_id": 425,
  "unit_centra_code": "BIMA",
  "unit_centra_name": "PT BIMA",
  "delivery_point": "jalan Perak Timur No 428 Pabean Cantian Surabaya",
  "address": "jalan Perak Timur No 428 Pabean Cantian Surabaya",
  "is_mr": 0
} 
*/

  String? id;
  String? regionalCode;
  String? code;
  String? name;
  String? description;
  String? regionalName;
  String? isDelete;
  String? createdAt;
  String? createdBy;
  String? updatedAt;
  String? updatedBy;
  String? unitCentraId;
  String? unitCentraCode;
  String? unitCentraName;
  String? deliveryPoint;
  String? address;
  String? isMr;

  ReportModelDataCabang({
    this.id,
    this.regionalCode,
    this.code,
    this.name,
    this.description,
    this.regionalName,
    this.isDelete,
    this.createdAt,
    this.createdBy,
    this.updatedAt,
    this.updatedBy,
    this.unitCentraId,
    this.unitCentraCode,
    this.unitCentraName,
    this.deliveryPoint,
    this.address,
    this.isMr,
  });
  ReportModelDataCabang.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    regionalCode = json['regional_code']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    regionalName = json['regional_name']?.toString();
    isDelete = json['is_delete']?.toString();
    createdAt = json['created_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedAt = json['updated_at']?.toString();
    updatedBy = json['updated_by']?.toString();
    unitCentraId = json['unit_centra_id']?.toString();
    unitCentraCode = json['unit_centra_code']?.toString();
    unitCentraName = json['unit_centra_name']?.toString();
    deliveryPoint = json['delivery_point']?.toString();
    address = json['address']?.toString();
    isMr = json['is_mr']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['regional_code'] = regionalCode;
    data['code'] = code;
    data['name'] = name;
    data['description'] = description;
    data['regional_name'] = regionalName;
    data['is_delete'] = isDelete;
    data['created_at'] = createdAt;
    data['created_by'] = createdBy;
    data['updated_at'] = updatedAt;
    data['updated_by'] = updatedBy;
    data['unit_centra_id'] = unitCentraId;
    data['unit_centra_code'] = unitCentraCode;
    data['unit_centra_name'] = unitCentraName;
    data['delivery_point'] = deliveryPoint;
    data['address'] = address;
    data['is_mr'] = isMr;
    return data;
  }
}

class ReportModelDataAsset {
/*
{
  "id": 483,
  "code": "2000162002",
  "name": "Genset FC-02-Perkins-Batulicin",
  "kapasitas": "-",
  "merk": "PERKINS",
  "country_of_origin": null,
  "equipment_serial_number": null,
  "model": null,
  "power_source": null,
  "merk_engine": null,
  "engine_type": null,
  "serial_number_engine": null,
  "jenis_asset_code": "A10",
  "regional_code": "REG03",
  "cabang_code": "CAB09",
  "tahun": 2014,
  "is_delete": 0,
  "is_downtime": 0,
  "is_active": 1,
  "company_id": 5,
  "doc_status": "Completed",
  "apv_level": 0,
  "created_at": "1655891721",
  "updated_at": "1655895514",
  "created_by": 4,
  "updated_by": 1
} 
*/

  String? id;
  String? code;
  String? name;
  String? kapasitas;
  String? merk;
  String? countryOfOrigin;
  String? equipmentSerialNumber;
  String? model;
  String? powerSource;
  String? merkEngine;
  String? engineType;
  String? serialNumberEngine;
  String? jenisAssetCode;
  String? regionalCode;
  String? cabangCode;
  String? tahun;
  String? isDelete;
  String? isDowntime;
  String? isActive;
  String? companyId;
  String? docStatus;
  String? apvLevel;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  ReportModelDataAsset({
    this.id,
    this.code,
    this.name,
    this.kapasitas,
    this.merk,
    this.countryOfOrigin,
    this.equipmentSerialNumber,
    this.model,
    this.powerSource,
    this.merkEngine,
    this.engineType,
    this.serialNumberEngine,
    this.jenisAssetCode,
    this.regionalCode,
    this.cabangCode,
    this.tahun,
    this.isDelete,
    this.isDowntime,
    this.isActive,
    this.companyId,
    this.docStatus,
    this.apvLevel,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  ReportModelDataAsset.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    kapasitas = json['kapasitas']?.toString();
    merk = json['merk']?.toString();
    countryOfOrigin = json['country_of_origin']?.toString();
    equipmentSerialNumber = json['equipment_serial_number']?.toString();
    model = json['model']?.toString();
    powerSource = json['power_source']?.toString();
    merkEngine = json['merk_engine']?.toString();
    engineType = json['engine_type']?.toString();
    serialNumberEngine = json['serial_number_engine']?.toString();
    jenisAssetCode = json['jenis_asset_code']?.toString();
    regionalCode = json['regional_code']?.toString();
    cabangCode = json['cabang_code']?.toString();
    tahun = json['tahun']?.toString();
    isDelete = json['is_delete']?.toString();
    isDowntime = json['is_downtime']?.toString();
    isActive = json['is_active']?.toString();
    companyId = json['company_id']?.toString();
    docStatus = json['doc_status']?.toString();
    apvLevel = json['apv_level']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    data['kapasitas'] = kapasitas;
    data['merk'] = merk;
    data['country_of_origin'] = countryOfOrigin;
    data['equipment_serial_number'] = equipmentSerialNumber;
    data['model'] = model;
    data['power_source'] = powerSource;
    data['merk_engine'] = merkEngine;
    data['engine_type'] = engineType;
    data['serial_number_engine'] = serialNumberEngine;
    data['jenis_asset_code'] = jenisAssetCode;
    data['regional_code'] = regionalCode;
    data['cabang_code'] = cabangCode;
    data['tahun'] = tahun;
    data['is_delete'] = isDelete;
    data['is_downtime'] = isDowntime;
    data['is_active'] = isActive;
    data['company_id'] = companyId;
    data['doc_status'] = docStatus;
    data['apv_level'] = apvLevel;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class ReportModelDataTypeWork {
/*
{
  "code": "PDM",
  "name": "Predictive Maintenance",
  "status": 1
} 
*/

  String? code;
  String? name;
  String? status;

  ReportModelDataTypeWork({
    this.code,
    this.name,
    this.status,
  });
  ReportModelDataTypeWork.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    name = json['name']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['name'] = name;
    data['status'] = status;
    return data;
  }
}

class ReportModelData {
/*
{
  "id": 7848,
  "doc_no": "WO-2024-0000025",
  "asset_code": "2000162002",
  "asset_category_code": "A10",
  "ba_no_persetujuan": null,
  "ba_no_realisasi": null,
  "type_work": {
    "code": "PDM",
    "name": "Predictive Maintenance",
    "status": 1
  },
  "asset_meter_code": null,
  "type_trans": "persetujuan",
  "date_doc": "2024-03-20",
  "cabang_code": "CAB27",
  "regional_code": "REG02",
  "description": "Testing notifikasi",
  "doc_status": "Draft",
  "is_downtime": 1,
  "apv_level": 0,
  "preventive_maintanance_id": null,
  "jobplan_id": null,
  "workorder_id": null,
  "frequency_time_based": 0,
  "frequency_unit_based": null,
  "meter_reading": 0,
  "is_delete": 0,
  "company_id": 5,
  "status_part": "waiting",
  "date_start": null,
  "date_end": null,
  "created_at": 1710909093,
  "updated_at": null,
  "created_by": 1,
  "updated_by": null,
  "is_mr": 0,
  "submit_rls": null,
  "start_downtime": null,
  "up_date": null,
  "asset": {
    "id": 483,
    "code": "2000162002",
    "name": "Genset FC-02-Perkins-Batulicin",
    "kapasitas": "-",
    "merk": "PERKINS",
    "country_of_origin": null,
    "equipment_serial_number": null,
    "model": null,
    "power_source": null,
    "merk_engine": null,
    "engine_type": null,
    "serial_number_engine": null,
    "jenis_asset_code": "A10",
    "regional_code": "REG03",
    "cabang_code": "CAB09",
    "tahun": 2014,
    "is_delete": 0,
    "is_downtime": 0,
    "is_active": 1,
    "company_id": 5,
    "doc_status": "Completed",
    "apv_level": 0,
    "created_at": "1655891721",
    "updated_at": "1655895514",
    "created_by": 4,
    "updated_by": 1
  },
  "cabang": {
    "id": 27,
    "regional_code": "REG02",
    "code": "CAB27",
    "name": "KANTOR PUSAT",
    "description": "KANTOR PUSAT PT BIMA",
    "regional_name": "ANAK PERUSAHAAN",
    "is_delete": 0,
    "created_at": null,
    "created_by": null,
    "updated_at": 1698287966,
    "updated_by": 747,
    "unit_centra_id": 425,
    "unit_centra_code": "BIMA",
    "unit_centra_name": "PT BIMA",
    "delivery_point": "jalan Perak Timur No 428 Pabean Cantian Surabaya",
    "address": "jalan Perak Timur No 428 Pabean Cantian Surabaya",
    "is_mr": 0
  },
  "user_create": {
    "id": 1,
    "username": "adminatria",
    "confirmation_token": null,
    "status": 1,
    "superadmin": 1,
    "created_at": 1599308626,
    "updated_at": 1702448766,
    "type": null,
    "company_id": 1,
    "personil_id": 737,
    "registration_ip": null,
    "bind_to_ip": "",
    "email": "it@ptbima.id",
    "email_confirmed": 0,
    "username_centra": "admin",
    "password_centra": "adminp3",
    "token_centra": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvY2VudHJhLXFhLnBlbGluZG8uY28uaWRcL3B1YmxpY1wvYXBpXC9sb2dpbi1tb2JpbGUiLCJpYXQiOjE3MDI0NDg3NjUsImV4cCI6MTczNDA3MTE2NSwibmJmIjoxNzAyNDQ4NzY1LCJqdGkiOiIxdWh1Wm9SQVJKY0IwOTBGIiwic3ViIjoxLCJwcnYiOiIwMmU5YzhmZjQxY2NlYjdlMGQyMGIyZDg0NTFkZDY2NjBkZjY2NGI1In0.vA7Hb7mZFDKDaEzz60pM4R-xpE0cY2D5JCGbUfaBOFs",
    "valid_token": 1,
    "firebase_token": "xpE0cY2D5JCGbUfaBOFs111"
  },
  "regional": {
    "id": 2,
    "code": "REG02",
    "name": "SPTP",
    "description": "SUBHOLDING PELINDO TERMINAL PETIKEMAS",
    "is_delete": 0,
    "created_date": null,
    "created_by": null,
    "updated_date": null,
    "updated_by": null
  },
  "wo_spareparts": [
    {
      "id": 9578,
      "workorder_id": 7848,
      "code": "AA-001-000001",
      "name": "USHA MARTIN;WIRE ROPE;25 MM;IWRC;RHOL;1960 N/MM2;6X29;GALV;0;LENGHT 960 METER",
      "quantity": 1,
      "uom": "METER",
      "type_trans": "persetujuan",
      "status": 10,
      "company_id": 1,
      "created_at": "1711012799",
      "updated_at": "1711012799",
      "created_by": "1",
      "updated_by": "1",
      "wh_code": "1200",
      "wh_name": "KUPANG",
      "unit_code": "1200",
      "unit_name": "Site Kupang",
      "price": "12000.00",
      "eta": "2024-03-20",
      "description": "",
      "type": null
    }
  ],
  "wo_activities": [
    {
      "id": 101763,
      "workorder_id": 7848,
      "task_number": 1,
      "task_name": "Bongkar mesin",
      "description": null,
      "type_trans": "persetujuan",
      "task_duration": "2",
      "created_at": 1711012799,
      "updated_at": 1711012799,
      "created_by": 1,
      "updated_by": 1
    }
  ],
  "wo_failures": [
    null
  ],
  "wo_files": [
    {
      "id": 12049,
      "workorder_id": 7848,
      "type_trans": "persetujuan",
      "keterangan": "Keterangan",
      "status": null,
      "file": "attachment/inY4e94sCElTLoleNqhAMP836fsseKuA.png",
      "file_name": "Businessmans hand holding question mark 1.png",
      "created_at": 1710909093,
      "updated_at": 1710909093,
      "created_by": 1,
      "updated_by": 1
    }
  ],
  "wo_labours": [
    {
      "id": 26216,
      "workorder_id": 7848,
      "craft": 1,
      "personil": null,
      "skill": 6,
      "amount": "1",
      "created_at": 1711012799,
      "updated_at": 1711012799,
      "created_by": 1,
      "updated_by": 1
    }
  ],
  "wo_progress": [
    null
  ],
  "wo_services": [
    {
      "id": 176,
      "workorder_id": 7848,
      "service_id": "DE-017-000001",
      "qty": 1,
      "type_trans": "persetujuan",
      "created_at": 1711012799,
      "updated_at": 1711012799,
      "created_by": 1,
      "updated_by": 1
    }
  ],
  "wo_tools": [
    {
      "id": 31629,
      "workorder_id": 7848,
      "tools_id": 1517,
      "quantity": 2,
      "company_id": 1,
      "uom": "PCS",
      "created_at": 1711012799,
      "updated_at": 1711012799,
      "created_by": 1,
      "updated_by": 1
    }
  ],
  "approver": null,
  "approver_p": null
} 
*/

  String? id;
  String? docNo;
  String? assetCode;
  String? assetCategoryCode;
  String? baNoPersetujuan;
  String? baNoRealisasi;
  ReportModelDataTypeWork? typeWork;
  String? assetMeterCode;
  String? typeTrans;
  String? dateDoc;
  String? cabangCode;
  String? regionalCode;
  String? description;
  String? docStatus;
  String? isDowntime;
  String? apvLevel;
  String? preventiveMaintananceId;
  String? jobplanId;
  String? workorderId;
  String? frequencyTimeBased;
  String? frequencyUnitBased;
  String? meterReading;
  String? isDelete;
  String? companyId;
  String? statusPart;
  String? dateStart;
  String? dateEnd;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;
  String? isMr;
  String? submitRls;
  String? startDowntime;
  String? upDate;
  ReportModelDataAsset? asset;
  ReportModelDataCabang? cabang;
  ReportModelDataUserCreate? userCreate;
  ReportModelDataRegional? regional;
  List<ReportModelDataWoSpareparts?>? woSpareparts;
  List<ReportModelDataWoActivities?>? woActivities;
  List<String?>? woFailures;
  List<ReportModelDataWoFiles?>? woFiles;
  List<ReportModelDataWoLabours?>? woLabours;
  List<String?>? woProgress;
  List<ReportModelDataWoServices?>? woServices;
  List<ReportModelDataWoTools?>? woTools;
  String? approver;
  String? approverP;

  ReportModelData({
    this.id,
    this.docNo,
    this.assetCode,
    this.assetCategoryCode,
    this.baNoPersetujuan,
    this.baNoRealisasi,
    this.typeWork,
    this.assetMeterCode,
    this.typeTrans,
    this.dateDoc,
    this.cabangCode,
    this.regionalCode,
    this.description,
    this.docStatus,
    this.isDowntime,
    this.apvLevel,
    this.preventiveMaintananceId,
    this.jobplanId,
    this.workorderId,
    this.frequencyTimeBased,
    this.frequencyUnitBased,
    this.meterReading,
    this.isDelete,
    this.companyId,
    this.statusPart,
    this.dateStart,
    this.dateEnd,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
    this.isMr,
    this.submitRls,
    this.startDowntime,
    this.upDate,
    this.asset,
    this.cabang,
    this.userCreate,
    this.regional,
    this.woSpareparts,
    this.woActivities,
    this.woFailures,
    this.woFiles,
    this.woLabours,
    this.woProgress,
    this.woServices,
    this.woTools,
    this.approver,
    this.approverP,
  });
  ReportModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    docNo = json['doc_no']?.toString();
    assetCode = json['asset_code']?.toString();
    assetCategoryCode = json['asset_category_code']?.toString();
    baNoPersetujuan = json['ba_no_persetujuan']?.toString();
    baNoRealisasi = json['ba_no_realisasi']?.toString();
    typeWork = (json['type_work'] != null)
        ? ReportModelDataTypeWork.fromJson(json['type_work'])
        : null;
    assetMeterCode = json['asset_meter_code']?.toString();
    typeTrans = json['type_trans']?.toString();
    dateDoc = json['date_doc']?.toString();
    cabangCode = json['cabang_code']?.toString();
    regionalCode = json['regional_code']?.toString();
    description = json['description']?.toString();
    docStatus = json['doc_status']?.toString();
    isDowntime = json['is_downtime']?.toString();
    apvLevel = json['apv_level']?.toString();
    preventiveMaintananceId = json['preventive_maintanance_id']?.toString();
    jobplanId = json['jobplan_id']?.toString();
    workorderId = json['workorder_id']?.toString();
    frequencyTimeBased = json['frequency_time_based']?.toString();
    frequencyUnitBased = json['frequency_unit_based']?.toString();
    meterReading = json['meter_reading']?.toString();
    isDelete = json['is_delete']?.toString();
    companyId = json['company_id']?.toString();
    statusPart = json['status_part']?.toString();
    dateStart = json['date_start']?.toString();
    dateEnd = json['date_end']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
    isMr = json['is_mr']?.toString();
    submitRls = json['submit_rls']?.toString();
    startDowntime = json['start_downtime']?.toString();
    upDate = json['up_date']?.toString();
    asset = (json['asset'] != null)
        ? ReportModelDataAsset.fromJson(json['asset'])
        : null;
    cabang = (json['cabang'] != null)
        ? ReportModelDataCabang.fromJson(json['cabang'])
        : null;
    userCreate = (json['user_create'] != null)
        ? ReportModelDataUserCreate.fromJson(json['user_create'])
        : null;
    regional = (json['regional'] != null)
        ? ReportModelDataRegional.fromJson(json['regional'])
        : null;
    if (json['wo_spareparts'] != null) {
      final v = json['wo_spareparts'];
      final arr0 = <ReportModelDataWoSpareparts>[];
      v.forEach((v) {
        arr0.add(ReportModelDataWoSpareparts.fromJson(v));
      });
      woSpareparts = arr0;
    }
    if (json['wo_activities'] != null) {
      final v = json['wo_activities'];
      final arr0 = <ReportModelDataWoActivities>[];
      v.forEach((v) {
        arr0.add(ReportModelDataWoActivities.fromJson(v));
      });
      woActivities = arr0;
    }

    if (json['wo_files'] != null) {
      final v = json['wo_files'];
      final arr0 = <ReportModelDataWoFiles>[];
      v.forEach((v) {
        arr0.add(ReportModelDataWoFiles.fromJson(v));
      });
      woFiles = arr0;
    }
    if (json['wo_labours'] != null) {
      final v = json['wo_labours'];
      final arr0 = <ReportModelDataWoLabours>[];
      v.forEach((v) {
        arr0.add(ReportModelDataWoLabours.fromJson(v));
      });
      woLabours = arr0;
    }

    if (json['wo_services'] != null) {
      final v = json['wo_services'];
      final arr0 = <ReportModelDataWoServices>[];
      v.forEach((v) {
        arr0.add(ReportModelDataWoServices.fromJson(v));
      });
      woServices = arr0;
    }
    if (json['wo_tools'] != null) {
      final v = json['wo_tools'];
      final arr0 = <ReportModelDataWoTools>[];
      v.forEach((v) {
        arr0.add(ReportModelDataWoTools.fromJson(v));
      });
      woTools = arr0;
    }
    approver = json['approver']?.toString();
    approverP = json['approver_p']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['doc_no'] = docNo;
    data['asset_code'] = assetCode;
    data['asset_category_code'] = assetCategoryCode;
    data['ba_no_persetujuan'] = baNoPersetujuan;
    data['ba_no_realisasi'] = baNoRealisasi;
    if (typeWork != null) {
      data['type_work'] = typeWork!.toJson();
    }
    data['asset_meter_code'] = assetMeterCode;
    data['type_trans'] = typeTrans;
    data['date_doc'] = dateDoc;
    data['cabang_code'] = cabangCode;
    data['regional_code'] = regionalCode;
    data['description'] = description;
    data['doc_status'] = docStatus;
    data['is_downtime'] = isDowntime;
    data['apv_level'] = apvLevel;
    data['preventive_maintanance_id'] = preventiveMaintananceId;
    data['jobplan_id'] = jobplanId;
    data['workorder_id'] = workorderId;
    data['frequency_time_based'] = frequencyTimeBased;
    data['frequency_unit_based'] = frequencyUnitBased;
    data['meter_reading'] = meterReading;
    data['is_delete'] = isDelete;
    data['company_id'] = companyId;
    data['status_part'] = statusPart;
    data['date_start'] = dateStart;
    data['date_end'] = dateEnd;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    data['is_mr'] = isMr;
    data['submit_rls'] = submitRls;
    data['start_downtime'] = startDowntime;
    data['up_date'] = upDate;
    if (asset != null) {
      data['asset'] = asset!.toJson();
    }
    if (cabang != null) {
      data['cabang'] = cabang!.toJson();
    }
    if (userCreate != null) {
      data['user_create'] = userCreate!.toJson();
    }
    if (regional != null) {
      data['regional'] = regional!.toJson();
    }
    if (woSpareparts != null) {
      final v = woSpareparts;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['wo_spareparts'] = arr0;
    }
    if (woActivities != null) {
      final v = woActivities;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['wo_activities'] = arr0;
    }

    if (woFiles != null) {
      final v = woFiles;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['wo_files'] = arr0;
    }
    if (woLabours != null) {
      final v = woLabours;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['wo_labours'] = arr0;
    }

    if (woServices != null) {
      final v = woServices;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['wo_services'] = arr0;
    }
    if (woTools != null) {
      final v = woTools;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['wo_tools'] = arr0;
    }
    data['approver'] = approver;
    data['approver_p'] = approverP;
    return data;
  }
}

class ReportModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 7848,
      "doc_no": "WO-2024-0000025",
      "asset_code": "2000162002",
      "asset_category_code": "A10",
      "ba_no_persetujuan": null,
      "ba_no_realisasi": null,
      "type_work": {
        "code": "PDM",
        "name": "Predictive Maintenance",
        "status": 1
      },
      "asset_meter_code": null,
      "type_trans": "persetujuan",
      "date_doc": "2024-03-20",
      "cabang_code": "CAB27",
      "regional_code": "REG02",
      "description": "Testing notifikasi",
      "doc_status": "Draft",
      "is_downtime": 1,
      "apv_level": 0,
      "preventive_maintanance_id": null,
      "jobplan_id": null,
      "workorder_id": null,
      "frequency_time_based": 0,
      "frequency_unit_based": null,
      "meter_reading": 0,
      "is_delete": 0,
      "company_id": 5,
      "status_part": "waiting",
      "date_start": null,
      "date_end": null,
      "created_at": 1710909093,
      "updated_at": null,
      "created_by": 1,
      "updated_by": null,
      "is_mr": 0,
      "submit_rls": null,
      "start_downtime": null,
      "up_date": null,
      "asset": {
        "id": 483,
        "code": "2000162002",
        "name": "Genset FC-02-Perkins-Batulicin",
        "kapasitas": "-",
        "merk": "PERKINS",
        "country_of_origin": null,
        "equipment_serial_number": null,
        "model": null,
        "power_source": null,
        "merk_engine": null,
        "engine_type": null,
        "serial_number_engine": null,
        "jenis_asset_code": "A10",
        "regional_code": "REG03",
        "cabang_code": "CAB09",
        "tahun": 2014,
        "is_delete": 0,
        "is_downtime": 0,
        "is_active": 1,
        "company_id": 5,
        "doc_status": "Completed",
        "apv_level": 0,
        "created_at": "1655891721",
        "updated_at": "1655895514",
        "created_by": 4,
        "updated_by": 1
      },
      "cabang": {
        "id": 27,
        "regional_code": "REG02",
        "code": "CAB27",
        "name": "KANTOR PUSAT",
        "description": "KANTOR PUSAT PT BIMA",
        "regional_name": "ANAK PERUSAHAAN",
        "is_delete": 0,
        "created_at": null,
        "created_by": null,
        "updated_at": 1698287966,
        "updated_by": 747,
        "unit_centra_id": 425,
        "unit_centra_code": "BIMA",
        "unit_centra_name": "PT BIMA",
        "delivery_point": "jalan Perak Timur No 428 Pabean Cantian Surabaya",
        "address": "jalan Perak Timur No 428 Pabean Cantian Surabaya",
        "is_mr": 0
      },
      "user_create": {
        "id": 1,
        "username": "adminatria",
        "confirmation_token": null,
        "status": 1,
        "superadmin": 1,
        "created_at": 1599308626,
        "updated_at": 1702448766,
        "type": null,
        "company_id": 1,
        "personil_id": 737,
        "registration_ip": null,
        "bind_to_ip": "",
        "email": "it@ptbima.id",
        "email_confirmed": 0,
        "username_centra": "admin",
        "password_centra": "adminp3",
        "token_centra": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvY2VudHJhLXFhLnBlbGluZG8uY28uaWRcL3B1YmxpY1wvYXBpXC9sb2dpbi1tb2JpbGUiLCJpYXQiOjE3MDI0NDg3NjUsImV4cCI6MTczNDA3MTE2NSwibmJmIjoxNzAyNDQ4NzY1LCJqdGkiOiIxdWh1Wm9SQVJKY0IwOTBGIiwic3ViIjoxLCJwcnYiOiIwMmU5YzhmZjQxY2NlYjdlMGQyMGIyZDg0NTFkZDY2NjBkZjY2NGI1In0.vA7Hb7mZFDKDaEzz60pM4R-xpE0cY2D5JCGbUfaBOFs",
        "valid_token": 1,
        "firebase_token": "xpE0cY2D5JCGbUfaBOFs111"
      },
      "regional": {
        "id": 2,
        "code": "REG02",
        "name": "SPTP",
        "description": "SUBHOLDING PELINDO TERMINAL PETIKEMAS",
        "is_delete": 0,
        "created_date": null,
        "created_by": null,
        "updated_date": null,
        "updated_by": null
      },
      "wo_spareparts": [
        {
          "id": 9578,
          "workorder_id": 7848,
          "code": "AA-001-000001",
          "name": "USHA MARTIN;WIRE ROPE;25 MM;IWRC;RHOL;1960 N/MM2;6X29;GALV;0;LENGHT 960 METER",
          "quantity": 1,
          "uom": "METER",
          "type_trans": "persetujuan",
          "status": 10,
          "company_id": 1,
          "created_at": "1711012799",
          "updated_at": "1711012799",
          "created_by": "1",
          "updated_by": "1",
          "wh_code": "1200",
          "wh_name": "KUPANG",
          "unit_code": "1200",
          "unit_name": "Site Kupang",
          "price": "12000.00",
          "eta": "2024-03-20",
          "description": "",
          "type": null
        }
      ],
      "wo_activities": [
        {
          "id": 101763,
          "workorder_id": 7848,
          "task_number": 1,
          "task_name": "Bongkar mesin",
          "description": null,
          "type_trans": "persetujuan",
          "task_duration": "2",
          "created_at": 1711012799,
          "updated_at": 1711012799,
          "created_by": 1,
          "updated_by": 1
        }
      ],
      "wo_failures": [
        null
      ],
      "wo_files": [
        {
          "id": 12049,
          "workorder_id": 7848,
          "type_trans": "persetujuan",
          "keterangan": "Keterangan",
          "status": null,
          "file": "attachment/inY4e94sCElTLoleNqhAMP836fsseKuA.png",
          "file_name": "Businessmans hand holding question mark 1.png",
          "created_at": 1710909093,
          "updated_at": 1710909093,
          "created_by": 1,
          "updated_by": 1
        }
      ],
      "wo_labours": [
        {
          "id": 26216,
          "workorder_id": 7848,
          "craft": 1,
          "personil": null,
          "skill": 6,
          "amount": "1",
          "created_at": 1711012799,
          "updated_at": 1711012799,
          "created_by": 1,
          "updated_by": 1
        }
      ],
      "wo_progress": [
        null
      ],
      "wo_services": [
        {
          "id": 176,
          "workorder_id": 7848,
          "service_id": "DE-017-000001",
          "qty": 1,
          "type_trans": "persetujuan",
          "created_at": 1711012799,
          "updated_at": 1711012799,
          "created_by": 1,
          "updated_by": 1
        }
      ],
      "wo_tools": [
        {
          "id": 31629,
          "workorder_id": 7848,
          "tools_id": 1517,
          "quantity": 2,
          "company_id": 1,
          "uom": "PCS",
          "created_at": 1711012799,
          "updated_at": 1711012799,
          "created_by": 1,
          "updated_by": 1
        }
      ],
      "approver": null,
      "approver_p": null
    }
  ],
  "page": 1,
  "length": 10,
  "message": "Sukses"
} 
*/

  bool? success;
  List<ReportModelData?>? data;
  String? page;
  String? length;
  String? message;

  ReportModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  ReportModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ReportModelData>[];
      v.forEach((v) {
        arr0.add(ReportModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['Message'] = message;
    return data;
  }
}
