///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HomeModelData {
/*
{
  "total_asset": "671",
  "ready": "669",
  "not_ready": "2"
} 
*/

  String? totalAsset;
  String? ready;
  String? notReady;

  HomeModelData({
    this.totalAsset,
    this.ready,
    this.notReady,
  });
  HomeModelData.fromJson(Map<String, dynamic> json) {
    totalAsset = json['total_asset']?.toString();
    ready = json['ready']?.toString();
    notReady = json['not_ready']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['total_asset'] = totalAsset;
    data['ready'] = ready;
    data['not_ready'] = notReady;
    return data;
  }
}

class HomeModel {
/*
{
  "success": true,
  "data": [
    {
      "total_asset": "671",
      "ready": "669",
      "not_ready": "2"
    }
  ],
  "message": "Sukses"
} 
*/

  bool? success;
  List<HomeModelData?>? data;
  String? message;

  HomeModel({
    this.success,
    this.data,
    this.message,
  });
  HomeModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <HomeModelData>[];
      v.forEach((v) {
        arr0.add(HomeModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['Message'] = message;
    return data;
  }
}
