///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WOAgreementLogModelData {
/*
{
  "id": 56066,
  "module_id": "work-order",
  "doc_id": 7847,
  "user_id": 1,
  "time": "2024-03-18 12:48:11",
  "apv_level": 0,
  "doc_status": "Draft",
  "note": "-",
  "nip": "890904833",
  "name": "Dusty Widha Hutama"
} 
*/

  String? id;
  String? moduleId;
  String? docId;
  String? userId;
  String? time;
  String? apvLevel;
  String? docStatus;
  String? note;
  String? nip;
  String? name;

  WOAgreementLogModelData({
    this.id,
    this.moduleId,
    this.docId,
    this.userId,
    this.time,
    this.apvLevel,
    this.docStatus,
    this.note,
    this.nip,
    this.name,
  });
  WOAgreementLogModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    moduleId = json['module_id']?.toString();
    docId = json['doc_id']?.toString();
    userId = json['user_id']?.toString();
    time = json['time']?.toString();
    apvLevel = json['apv_level']?.toString();
    docStatus = json['doc_status']?.toString();
    note = json['note']?.toString();
    nip = json['nip']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['module_id'] = moduleId;
    data['doc_id'] = docId;
    data['user_id'] = userId;
    data['time'] = time;
    data['apv_level'] = apvLevel;
    data['doc_status'] = docStatus;
    data['note'] = note;
    data['nip'] = nip;
    data['name'] = name;
    return data;
  }
}

class WOAgreementLogModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 56066,
      "module_id": "work-order",
      "doc_id": 7847,
      "user_id": 1,
      "time": "2024-03-18 12:48:11",
      "apv_level": 0,
      "doc_status": "Draft",
      "note": "-",
      "nip": "890904833",
      "name": "Dusty Widha Hutama"
    }
  ],
  "message": "Sukses"
} 
*/

  bool? success;
  List<WOAgreementLogModelData?>? data;
  String? message;

  WOAgreementLogModel({
    this.success,
    this.data,
    this.message,
  });
  WOAgreementLogModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WOAgreementLogModelData>[];
      v.forEach((v) {
        arr0.add(WOAgreementLogModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['Message'] = message;
    return data;
  }
}
