///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WOToolsSearchModelData {
/*
{
  "id": 1,
  "name": "IMPACT ANGIN",
  "satuan": "PCS",
  "cabang_code": "CAB01",
  "keterangan": null,
  "condition": "100%",
  "qty": 1,
  "company_id": 1,
  "is_active": 1,
  "is_delete": 0,
  "created_at": null,
  "updated_at": null,
  "created_by": null,
  "updated_by": null
} 
*/

  String? id;
  String? name;
  String? satuan;
  String? cabangCode;
  String? keterangan;
  String? condition;
  String? qty;
  String? companyId;
  String? isActive;
  String? isDelete;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  WOToolsSearchModelData({
    this.id,
    this.name,
    this.satuan,
    this.cabangCode,
    this.keterangan,
    this.condition,
    this.qty,
    this.companyId,
    this.isActive,
    this.isDelete,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  WOToolsSearchModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    satuan = json['satuan']?.toString();
    cabangCode = json['cabang_code']?.toString();
    keterangan = json['keterangan']?.toString();
    condition = json['condition']?.toString();
    qty = json['qty']?.toString();
    companyId = json['company_id']?.toString();
    isActive = json['is_active']?.toString();
    isDelete = json['is_delete']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['satuan'] = satuan;
    data['cabang_code'] = cabangCode;
    data['keterangan'] = keterangan;
    data['condition'] = condition;
    data['qty'] = qty;
    data['company_id'] = companyId;
    data['is_active'] = isActive;
    data['is_delete'] = isDelete;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class WOToolsSearchModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 1,
      "name": "IMPACT ANGIN",
      "satuan": "PCS",
      "cabang_code": "CAB01",
      "keterangan": null,
      "condition": "100%",
      "qty": 1,
      "company_id": 1,
      "is_active": 1,
      "is_delete": 0,
      "created_at": null,
      "updated_at": null,
      "created_by": null,
      "updated_by": null
    }
  ],
  "page": 1,
  "length": 10,
  "message": "Sukses"
} 
*/

  bool? success;
  List<WOToolsSearchModelData?>? data;
  String? page;
  String? length;
  String? message;

  WOToolsSearchModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  WOToolsSearchModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WOToolsSearchModelData>[];
      v.forEach((v) {
        arr0.add(WOToolsSearchModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['Message'] = message;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WOServiceSearchModelData {
/*
{
  "id": 6226,
  "centra_id": 461,
  "code": "EG-004-000045",
  "name": "JASA;BONGKAR PASANG PE PED PANEL;PROJECT",
  "description": "DIVISI PROJECT",
  "uom": "BOX",
  "valid_from": "2019-09-01",
  "valid_to": "9999-12-31",
  "doc_status": "Draft",
  "apv_level": 0,
  "is_delete": 0,
  "company_id": 1,
  "created_at": "",
  "updated_at": null,
  "created_by": null,
  "updated_by": null
} 
*/

  String? id;
  String? centraId;
  String? code;
  String? name;
  String? description;
  String? uom;
  String? validFrom;
  String? validTo;
  String? docStatus;
  String? apvLevel;
  String? isDelete;
  String? companyId;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  WOServiceSearchModelData({
    this.id,
    this.centraId,
    this.code,
    this.name,
    this.description,
    this.uom,
    this.validFrom,
    this.validTo,
    this.docStatus,
    this.apvLevel,
    this.isDelete,
    this.companyId,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  WOServiceSearchModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    centraId = json['centra_id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    uom = json['uom']?.toString();
    validFrom = json['valid_from']?.toString();
    validTo = json['valid_to']?.toString();
    docStatus = json['doc_status']?.toString();
    apvLevel = json['apv_level']?.toString();
    isDelete = json['is_delete']?.toString();
    companyId = json['company_id']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['centra_id'] = centraId;
    data['code'] = code;
    data['name'] = name;
    data['description'] = description;
    data['uom'] = uom;
    data['valid_from'] = validFrom;
    data['valid_to'] = validTo;
    data['doc_status'] = docStatus;
    data['apv_level'] = apvLevel;
    data['is_delete'] = isDelete;
    data['company_id'] = companyId;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class WOServiceSearchModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 6226,
      "centra_id": 461,
      "code": "EG-004-000045",
      "name": "JASA;BONGKAR PASANG PE PED PANEL;PROJECT",
      "description": "DIVISI PROJECT",
      "uom": "BOX",
      "valid_from": "2019-09-01",
      "valid_to": "9999-12-31",
      "doc_status": "Draft",
      "apv_level": 0,
      "is_delete": 0,
      "company_id": 1,
      "created_at": "",
      "updated_at": null,
      "created_by": null,
      "updated_by": null
    }
  ],
  "page": 1,
  "length": 10,
  "message": "Sukses"
} 
*/

  bool? success;
  List<WOServiceSearchModelData?>? data;
  String? page;
  String? length;
  String? message;

  WOServiceSearchModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  WOServiceSearchModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WOServiceSearchModelData>[];
      v.forEach((v) {
        arr0.add(WOServiceSearchModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['Message'] = message;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WOSparepartSearchModelData {
/*
{
  "id": 110105,
  "centra_id": 5882,
  "code": "AA-003-000168",
  "name": "0;KLEMP HOSE;1 1/4\"",
  "quantity_updating": 0,
  "spec": null,
  "is_delete": 0,
  "uom": "PCS",
  "description": null,
  "company_id": 1
} 
*/

  String? id;
  String? centraId;
  String? code;
  String? name;
  String? quantityUpdating;
  String? spec;
  String? isDelete;
  String? uom;
  String? description;
  String? companyId;

  WOSparepartSearchModelData({
    this.id,
    this.centraId,
    this.code,
    this.name,
    this.quantityUpdating,
    this.spec,
    this.isDelete,
    this.uom,
    this.description,
    this.companyId,
  });
  WOSparepartSearchModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    centraId = json['centra_id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    quantityUpdating = json['quantity_updating']?.toString();
    spec = json['spec']?.toString();
    isDelete = json['is_delete']?.toString();
    uom = json['uom']?.toString();
    description = json['description']?.toString();
    companyId = json['company_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['centra_id'] = centraId;
    data['code'] = code;
    data['name'] = name;
    data['quantity_updating'] = quantityUpdating;
    data['spec'] = spec;
    data['is_delete'] = isDelete;
    data['uom'] = uom;
    data['description'] = description;
    data['company_id'] = companyId;
    return data;
  }
}

class WOSparepartSearchModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 110105,
      "centra_id": 5882,
      "code": "AA-003-000168",
      "name": "0;KLEMP HOSE;1 1/4\"",
      "quantity_updating": 0,
      "spec": null,
      "is_delete": 0,
      "uom": "PCS",
      "description": null,
      "company_id": 1
    }
  ],
  "page": 1,
  "length": 50,
  "message": "Sukses"
} 
*/

  bool? success;
  List<WOSparepartSearchModelData?>? data;
  String? page;
  String? length;
  String? message;

  WOSparepartSearchModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  WOSparepartSearchModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WOSparepartSearchModelData>[];
      v.forEach((v) {
        arr0.add(WOSparepartSearchModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['Message'] = message;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WOWarehouseSearchModelData {
/*
{
  "id": 1,
  "code": "1100",
  "name": "BENOA",
  "description": "BENOA",
  "address": null,
  "unit_id": 1,
  "unit_code": "1100",
  "unit_name": "Site Benoa",
  "regional_id": 43,
  "regional_code": "1100",
  "regional_name": "Benoa",
  "is_delete": 0,
  "created_by": null,
  "created_at": null,
  "updated_by": 1,
  "updated_at": 1709646212,
  "centra_id": 1,
  "company_id": 1
} 
*/

  String? id;
  String? code;
  String? name;
  String? description;
  String? address;
  String? unitId;
  String? unitCode;
  String? unitName;
  String? regionalId;
  String? regionalCode;
  String? regionalName;
  String? isDelete;
  String? createdBy;
  String? createdAt;
  String? updatedBy;
  String? updatedAt;
  String? centraId;
  String? companyId;

  WOWarehouseSearchModelData({
    this.id,
    this.code,
    this.name,
    this.description,
    this.address,
    this.unitId,
    this.unitCode,
    this.unitName,
    this.regionalId,
    this.regionalCode,
    this.regionalName,
    this.isDelete,
    this.createdBy,
    this.createdAt,
    this.updatedBy,
    this.updatedAt,
    this.centraId,
    this.companyId,
  });
  WOWarehouseSearchModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    address = json['address']?.toString();
    unitId = json['unit_id']?.toString();
    unitCode = json['unit_code']?.toString();
    unitName = json['unit_name']?.toString();
    regionalId = json['regional_id']?.toString();
    regionalCode = json['regional_code']?.toString();
    regionalName = json['regional_name']?.toString();
    isDelete = json['is_delete']?.toString();
    createdBy = json['created_by']?.toString();
    createdAt = json['created_at']?.toString();
    updatedBy = json['updated_by']?.toString();
    updatedAt = json['updated_at']?.toString();
    centraId = json['centra_id']?.toString();
    companyId = json['company_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    data['description'] = description;
    data['address'] = address;
    data['unit_id'] = unitId;
    data['unit_code'] = unitCode;
    data['unit_name'] = unitName;
    data['regional_id'] = regionalId;
    data['regional_code'] = regionalCode;
    data['regional_name'] = regionalName;
    data['is_delete'] = isDelete;
    data['created_by'] = createdBy;
    data['created_at'] = createdAt;
    data['updated_by'] = updatedBy;
    data['updated_at'] = updatedAt;
    data['centra_id'] = centraId;
    data['company_id'] = companyId;
    return data;
  }
}

class WOWarehouseSearchModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 1,
      "code": "1100",
      "name": "BENOA",
      "description": "BENOA",
      "address": null,
      "unit_id": 1,
      "unit_code": "1100",
      "unit_name": "Site Benoa",
      "regional_id": 43,
      "regional_code": "1100",
      "regional_name": "Benoa",
      "is_delete": 0,
      "created_by": null,
      "created_at": null,
      "updated_by": 1,
      "updated_at": 1709646212,
      "centra_id": 1,
      "company_id": 1
    }
  ],
  "page": 1,
  "length": 10,
  "message": "Sukses"
} 
*/

  bool? success;
  List<WOWarehouseSearchModelData?>? data;
  String? page;
  String? length;
  String? message;

  WOWarehouseSearchModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  WOWarehouseSearchModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WOWarehouseSearchModelData>[];
      v.forEach((v) {
        arr0.add(WOWarehouseSearchModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['Message'] = message;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WOSystemSearchModelData {
/*
{
  "id": 1,
  "asset_code": "FLT003-0002",
  "asset_meter_code": null,
  "code": "S1",
  "name": "ENGINE",
  "is_delete": 0,
  "is_active": 1,
  "created_at": "1655906436",
  "updated_at": "1655906513",
  "created_by": 1,
  "updated_by": 1
} 
*/

  String? id;
  String? assetCode;
  String? assetMeterCode;
  String? code;
  String? name;
  String? isDelete;
  String? isActive;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  WOSystemSearchModelData({
    this.id,
    this.assetCode,
    this.assetMeterCode,
    this.code,
    this.name,
    this.isDelete,
    this.isActive,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  WOSystemSearchModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    assetCode = json['asset_code']?.toString();
    assetMeterCode = json['asset_meter_code']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    isDelete = json['is_delete']?.toString();
    isActive = json['is_active']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['asset_code'] = assetCode;
    data['asset_meter_code'] = assetMeterCode;
    data['code'] = code;
    data['name'] = name;
    data['is_delete'] = isDelete;
    data['is_active'] = isActive;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class WOSystemSearchModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 1,
      "asset_code": "FLT003-0002",
      "asset_meter_code": null,
      "code": "S1",
      "name": "ENGINE",
      "is_delete": 0,
      "is_active": 1,
      "created_at": "1655906436",
      "updated_at": "1655906513",
      "created_by": 1,
      "updated_by": 1
    }
  ],
  "page": 1,
  "length": 10,
  "message": "Sukses"
} 
*/

  bool? success;
  List<WOSystemSearchModelData?>? data;
  String? page;
  String? length;
  String? message;

  WOSystemSearchModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  WOSystemSearchModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WOSystemSearchModelData>[];
      v.forEach((v) {
        arr0.add(WOSystemSearchModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['Message'] = message;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WOProgressSearchModelData {
/*
{
  "id": 1,
  "description": "Pemeriksaan"
} 
*/

  String? id;
  String? description;

  WOProgressSearchModelData({
    this.id,
    this.description,
  });
  WOProgressSearchModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    description = json['description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['description'] = description;
    return data;
  }
}

class WOProgressSearchModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 1,
      "description": "Pemeriksaan"
    }
  ],
  "page": -1,
  "length": 6,
  "message": "Sukses"
} 
*/

  bool? success;
  List<WOProgressSearchModelData?>? data;
  String? page;
  String? length;
  String? message;

  WOProgressSearchModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  WOProgressSearchModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WOProgressSearchModelData>[];
      v.forEach((v) {
        arr0.add(WOProgressSearchModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['Message'] = message;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WOSubSystemSearchModelData {
/*
{
  "id": 1,
  "system_code": "S1",
  "asset_code": "FLT003-0002",
  "code": "SS1",
  "name": "CONTROLS AND INSTRUMENTS",
  "is_delete": 0,
  "is_active": 1,
  "created_at": "1657246522",
  "updated_at": "1657246545",
  "created_by": 1,
  "updated_by": 1
} 
*/

  String? id;
  String? systemCode;
  String? assetCode;
  String? code;
  String? name;
  String? isDelete;
  String? isActive;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  WOSubSystemSearchModelData({
    this.id,
    this.systemCode,
    this.assetCode,
    this.code,
    this.name,
    this.isDelete,
    this.isActive,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  WOSubSystemSearchModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    systemCode = json['system_code']?.toString();
    assetCode = json['asset_code']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    isDelete = json['is_delete']?.toString();
    isActive = json['is_active']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['system_code'] = systemCode;
    data['asset_code'] = assetCode;
    data['code'] = code;
    data['name'] = name;
    data['is_delete'] = isDelete;
    data['is_active'] = isActive;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class WOSubSystemSearchModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 1,
      "system_code": "S1",
      "asset_code": "FLT003-0002",
      "code": "SS1",
      "name": "CONTROLS AND INSTRUMENTS",
      "is_delete": 0,
      "is_active": 1,
      "created_at": "1657246522",
      "updated_at": "1657246545",
      "created_by": 1,
      "updated_by": 1
    }
  ],
  "page": -1,
  "length": 9,
  "message": "Sukses"
} 
*/

  bool? success;
  List<WOSubSystemSearchModelData?>? data;
  String? page;
  String? length;
  String? message;

  WOSubSystemSearchModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  WOSubSystemSearchModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WOSubSystemSearchModelData>[];
      v.forEach((v) {
        arr0.add(WOSubSystemSearchModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['Message'] = message;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WOCompleteModelData {
/*
{
  "id": 7864,
  "doc_no": "WO-2024-0000040",
  "asset": "Rail Mounted Gantry Crane 050-RMG-01",
  "type": "BD"
} 
*/

  String? id;
  String? docNo;
  String? asset;
  String? type;

  WOCompleteModelData({
    this.id,
    this.docNo,
    this.asset,
    this.type,
  });
  WOCompleteModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    docNo = json['doc_no']?.toString();
    asset = json['asset']?.toString();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['doc_no'] = docNo;
    data['asset'] = asset;
    data['type'] = type;
    return data;
  }
}

class WOCompleteModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 7864,
      "doc_no": "WO-2024-0000040",
      "asset": "Rail Mounted Gantry Crane 050-RMG-01",
      "type": "BD"
    }
  ],
  "page": 1,
  "length": 1,
  "message": "Sukses"
} 
*/

  bool? success;
  List<WOCompleteModelData?>? data;
  String? page;
  String? length;
  String? message;

  WOCompleteModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  WOCompleteModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WOCompleteModelData>[];
      v.forEach((v) {
        arr0.add(WOCompleteModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['Message'] = message;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WOWorkOrderSearchModelDataWoSpareparts {
/*
{
  "id": 9601,
  "workorder_id": 7864,
  "code": "AA-001-000005",
  "name": "BLUE STRAND;WIRE ROPE;DIA 16 MM, IWRC, LHOL, GRADE 1960 N/MM2, KONST 6X36, UNGALV;Length 55meter",
  "quantity": 1,
  "uom": "METER",
  "type_trans": "realisasi",
  "status": 10,
  "company_id": 1,
  "created_at": "1711343304",
  "updated_at": "1711343304",
  "created_by": "1",
  "updated_by": "1",
  "wh_code": "2300",
  "wh_name": "TJ EMAS",
  "unit_code": "2300",
  "unit_name": "Site Tanjung Emas",
  "price": null,
  "eta": "2024-03-25",
  "description": "",
  "type": null
} 
*/

  String? id;
  String? workorderId;
  String? code;
  String? name;
  String? quantity;
  String? uom;
  String? typeTrans;
  String? status;
  String? companyId;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;
  String? whCode;
  String? whName;
  String? unitCode;
  String? unitName;
  String? price;
  String? eta;
  String? description;
  String? type;

  WOWorkOrderSearchModelDataWoSpareparts({
    this.id,
    this.workorderId,
    this.code,
    this.name,
    this.quantity,
    this.uom,
    this.typeTrans,
    this.status,
    this.companyId,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
    this.whCode,
    this.whName,
    this.unitCode,
    this.unitName,
    this.price,
    this.eta,
    this.description,
    this.type,
  });
  WOWorkOrderSearchModelDataWoSpareparts.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    workorderId = json['workorder_id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    quantity = json['quantity']?.toString();
    uom = json['uom']?.toString();
    typeTrans = json['type_trans']?.toString();
    status = json['status']?.toString();
    companyId = json['company_id']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
    whCode = json['wh_code']?.toString();
    whName = json['wh_name']?.toString();
    unitCode = json['unit_code']?.toString();
    unitName = json['unit_name']?.toString();
    price = json['price']?.toString();
    eta = json['eta']?.toString();
    description = json['description']?.toString();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['workorder_id'] = workorderId;
    data['code'] = code;
    data['name'] = name;
    data['quantity'] = quantity;
    data['uom'] = uom;
    data['type_trans'] = typeTrans;
    data['status'] = status;
    data['company_id'] = companyId;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    data['wh_code'] = whCode;
    data['wh_name'] = whName;
    data['unit_code'] = unitCode;
    data['unit_name'] = unitName;
    data['price'] = price;
    data['eta'] = eta;
    data['description'] = description;
    data['type'] = type;
    return data;
  }
}

class WOWorkOrderSearchModelDataWoServicesService {
/*
{
  "id": 6369,
  "centra_id": 362,
  "code": "DE-017-000001",
  "name": "JASA;REPAIR;ENERPACK",
  "description": null,
  "uom": "LUMPSUM",
  "valid_from": "2019-09-01",
  "valid_to": "9999-12-31",
  "doc_status": "Draft",
  "apv_level": 0,
  "is_delete": 0,
  "company_id": 1,
  "created_at": "",
  "updated_at": null,
  "created_by": null,
  "updated_by": null
} 
*/

  String? id;
  String? centraId;
  String? code;
  String? name;
  String? description;
  String? uom;
  String? validFrom;
  String? validTo;
  String? docStatus;
  String? apvLevel;
  String? isDelete;
  String? companyId;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  WOWorkOrderSearchModelDataWoServicesService({
    this.id,
    this.centraId,
    this.code,
    this.name,
    this.description,
    this.uom,
    this.validFrom,
    this.validTo,
    this.docStatus,
    this.apvLevel,
    this.isDelete,
    this.companyId,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  WOWorkOrderSearchModelDataWoServicesService.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    centraId = json['centra_id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    uom = json['uom']?.toString();
    validFrom = json['valid_from']?.toString();
    validTo = json['valid_to']?.toString();
    docStatus = json['doc_status']?.toString();
    apvLevel = json['apv_level']?.toString();
    isDelete = json['is_delete']?.toString();
    companyId = json['company_id']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['centra_id'] = centraId;
    data['code'] = code;
    data['name'] = name;
    data['description'] = description;
    data['uom'] = uom;
    data['valid_from'] = validFrom;
    data['valid_to'] = validTo;
    data['doc_status'] = docStatus;
    data['apv_level'] = apvLevel;
    data['is_delete'] = isDelete;
    data['company_id'] = companyId;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class WOWorkOrderSearchModelDataWoServices {
/*
{
  "id": 441,
  "workorder_id": 7884,
  "service_id": "6226",
  "qty": 2,
  "type_trans": "persetujuan",
  "created_at": 1712309489,
  "updated_at": null,
  "created_by": 8,
  "updated_by": null,
  "service": {
    "id": 6369,
    "centra_id": 362,
    "code": "DE-017-000001",
    "name": "JASA;REPAIR;ENERPACK",
    "description": null,
    "uom": "LUMPSUM",
    "valid_from": "2019-09-01",
    "valid_to": "9999-12-31",
    "doc_status": "Draft",
    "apv_level": 0,
    "is_delete": 0,
    "company_id": 1,
    "created_at": "",
    "updated_at": null,
    "created_by": null,
    "updated_by": null
  }
} 
*/

  String? id;
  String? workorderId;
  String? serviceId;
  String? qty;
  String? typeTrans;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;
  WOWorkOrderSearchModelDataWoServicesService? service;

  WOWorkOrderSearchModelDataWoServices({
    this.id,
    this.workorderId,
    this.serviceId,
    this.qty,
    this.typeTrans,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
    this.service,
  });
  WOWorkOrderSearchModelDataWoServices.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    workorderId = json['workorder_id']?.toString();
    serviceId = json['service_id']?.toString();
    qty = json['qty']?.toString();
    typeTrans = json['type_trans']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
    service = (json['service'] != null)
        ? WOWorkOrderSearchModelDataWoServicesService.fromJson(json['service'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['workorder_id'] = workorderId;
    data['service_id'] = serviceId;
    data['qty'] = qty;
    data['type_trans'] = typeTrans;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    if (service != null) {
      data['service'] = service!.toJson();
    }
    return data;
  }
}

class WOWorkOrderSearchModelDataWoLaboursSkill {
/*
{
  "id": 2,
  "name": "Junior Mechanic"
} 
*/

  String? id;
  String? name;

  WOWorkOrderSearchModelDataWoLaboursSkill({
    this.id,
    this.name,
  });
  WOWorkOrderSearchModelDataWoLaboursSkill.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class WOWorkOrderSearchModelDataWoLaboursCraft {
/*
{
  "id": 1,
  "name": "Mechanical"
} 
*/

  String? id;
  String? name;

  WOWorkOrderSearchModelDataWoLaboursCraft({
    this.id,
    this.name,
  });
  WOWorkOrderSearchModelDataWoLaboursCraft.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class WOWorkOrderSearchModelDataWoLabours {
/*
{
  "id": 26322,
  "workorder_id": 7864,
  "craft": {
    "id": 1,
    "name": "Mechanical"
  },
  "personil": "67910129;68110134;68510140;68710395;",
  "skill": {
    "id": 2,
    "name": "Junior Mechanic"
  },
  "amount": "4",
  "created_at": 1711343304,
  "updated_at": 1711343304,
  "created_by": 1,
  "updated_by": 1
} 
*/

  String? id;
  String? workorderId;
  WOWorkOrderSearchModelDataWoLaboursCraft? craft;
  String? personil;
  WOWorkOrderSearchModelDataWoLaboursSkill? skill;
  String? amount;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  WOWorkOrderSearchModelDataWoLabours({
    this.id,
    this.workorderId,
    this.craft,
    this.personil,
    this.skill,
    this.amount,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  WOWorkOrderSearchModelDataWoLabours.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    workorderId = json['workorder_id']?.toString();
    craft = (json['craft'] != null)
        ? WOWorkOrderSearchModelDataWoLaboursCraft.fromJson(json['craft'])
        : null;
    personil = json['personil']?.toString();
    skill = (json['skill'] != null)
        ? WOWorkOrderSearchModelDataWoLaboursSkill.fromJson(json['skill'])
        : null;
    amount = json['amount']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['workorder_id'] = workorderId;
    if (craft != null) {
      data['craft'] = craft!.toJson();
    }
    data['personil'] = personil;
    if (skill != null) {
      data['skill'] = skill!.toJson();
    }
    data['amount'] = amount;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class WOWorkOrderSearchModelDataWoToolsTool {
/*
{
  "id": 2723,
  "name": "Kunci Ring Pass 8-32 mm;MFR:Tekiro;PN:-",
  "satuan": "SET",
  "cabang_code": "CAB33",
  "keterangan": null,
  "condition": "Baik",
  "qty": 1,
  "company_id": 3,
  "is_active": 1,
  "is_delete": 0,
  "created_at": null,
  "updated_at": null,
  "created_by": null,
  "updated_by": null
} 
*/

  String? id;
  String? name;
  String? satuan;
  String? cabangCode;
  String? keterangan;
  String? condition;
  String? qty;
  String? companyId;
  String? isActive;
  String? isDelete;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  WOWorkOrderSearchModelDataWoToolsTool({
    this.id,
    this.name,
    this.satuan,
    this.cabangCode,
    this.keterangan,
    this.condition,
    this.qty,
    this.companyId,
    this.isActive,
    this.isDelete,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  WOWorkOrderSearchModelDataWoToolsTool.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    satuan = json['satuan']?.toString();
    cabangCode = json['cabang_code']?.toString();
    keterangan = json['keterangan']?.toString();
    condition = json['condition']?.toString();
    qty = json['qty']?.toString();
    companyId = json['company_id']?.toString();
    isActive = json['is_active']?.toString();
    isDelete = json['is_delete']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['satuan'] = satuan;
    data['cabang_code'] = cabangCode;
    data['keterangan'] = keterangan;
    data['condition'] = condition;
    data['qty'] = qty;
    data['company_id'] = companyId;
    data['is_active'] = isActive;
    data['is_delete'] = isDelete;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class WOWorkOrderSearchModelDataWoTools {
/*
{
  "id": 31739,
  "workorder_id": 7864,
  "tools_id": 2723,
  "quantity": 1,
  "company_id": 3,
  "uom": "SET",
  "created_at": 1711343304,
  "updated_at": 1711343304,
  "created_by": 1,
  "updated_by": 1,
  "tool": {
    "id": 2723,
    "name": "Kunci Ring Pass 8-32 mm;MFR:Tekiro;PN:-",
    "satuan": "SET",
    "cabang_code": "CAB33",
    "keterangan": null,
    "condition": "Baik",
    "qty": 1,
    "company_id": 3,
    "is_active": 1,
    "is_delete": 0,
    "created_at": null,
    "updated_at": null,
    "created_by": null,
    "updated_by": null
  }
} 
*/

  String? id;
  String? workorderId;
  String? toolsId;
  String? quantity;
  String? companyId;
  String? uom;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;
  WOWorkOrderSearchModelDataWoToolsTool? tool;

  WOWorkOrderSearchModelDataWoTools({
    this.id,
    this.workorderId,
    this.toolsId,
    this.quantity,
    this.companyId,
    this.uom,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
    this.tool,
  });
  WOWorkOrderSearchModelDataWoTools.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    workorderId = json['workorder_id']?.toString();
    toolsId = json['tools_id']?.toString();
    quantity = json['quantity']?.toString();
    companyId = json['company_id']?.toString();
    uom = json['uom']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
    tool = (json['tool'] != null)
        ? WOWorkOrderSearchModelDataWoToolsTool.fromJson(json['tool'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['workorder_id'] = workorderId;
    data['tools_id'] = toolsId;
    data['quantity'] = quantity;
    data['company_id'] = companyId;
    data['uom'] = uom;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    if (tool != null) {
      data['tool'] = tool!.toJson();
    }
    return data;
  }
}

class WOWorkOrderSearchModelDataWoActivities {
/*
{
  "id": 101880,
  "workorder_id": 7864,
  "task_number": 1,
  "task_name": "Pergantian wire rope ACM",
  "description": null,
  "type_trans": "persetujuan",
  "task_duration": "240",
  "created_at": 1711342230,
  "updated_at": 1711342230,
  "created_by": 1,
  "updated_by": 1
} 
*/

  String? id;
  String? workorderId;
  String? taskNumber;
  String? taskName;
  String? description;
  String? typeTrans;
  String? taskDuration;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  WOWorkOrderSearchModelDataWoActivities({
    this.id,
    this.workorderId,
    this.taskNumber,
    this.taskName,
    this.description,
    this.typeTrans,
    this.taskDuration,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  WOWorkOrderSearchModelDataWoActivities.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    workorderId = json['workorder_id']?.toString();
    taskNumber = json['task_number']?.toString();
    taskName = json['task_name']?.toString();
    description = json['description']?.toString();
    typeTrans = json['type_trans']?.toString();
    taskDuration = json['task_duration']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['workorder_id'] = workorderId;
    data['task_number'] = taskNumber;
    data['task_name'] = taskName;
    data['description'] = description;
    data['type_trans'] = typeTrans;
    data['task_duration'] = taskDuration;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class WOWorkOrderSearchModelData {
/*
{
  "id": 7864,
  "doc_no": "WO-2024-0000040",
  "asset": "Rail Mounted Gantry Crane 050-RMG-01",
  "type": "BD",
  "wo_activities": [
    {
      "id": 101880,
      "workorder_id": 7864,
      "task_number": 1,
      "task_name": "Pergantian wire rope ACM",
      "description": null,
      "type_trans": "persetujuan",
      "task_duration": "240",
      "created_at": 1711342230,
      "updated_at": 1711342230,
      "created_by": 1,
      "updated_by": 1
    }
  ],
  "wo_tools": [
    {
      "id": 31739,
      "workorder_id": 7864,
      "tools_id": 2723,
      "quantity": 1,
      "company_id": 3,
      "uom": "SET",
      "created_at": 1711343304,
      "updated_at": 1711343304,
      "created_by": 1,
      "updated_by": 1,
      "tool": {
        "id": 2723,
        "name": "Kunci Ring Pass 8-32 mm;MFR:Tekiro;PN:-",
        "satuan": "SET",
        "cabang_code": "CAB33",
        "keterangan": null,
        "condition": "Baik",
        "qty": 1,
        "company_id": 3,
        "is_active": 1,
        "is_delete": 0,
        "created_at": null,
        "updated_at": null,
        "created_by": null,
        "updated_by": null
      }
    }
  ],
  "wo_labours": [
    {
      "id": 26322,
      "workorder_id": 7864,
      "craft": {
        "id": 1,
        "name": "Mechanical"
      },
      "personil": "67910129;68110134;68510140;68710395;",
      "skill": {
        "id": 2,
        "name": "Junior Mechanic"
      },
      "amount": "4",
      "created_at": 1711343304,
      "updated_at": 1711343304,
      "created_by": 1,
      "updated_by": 1
    }
  ],
  "wo_services": [
    {
      "id": 441,
      "workorder_id": 7884,
      "service_id": "6226",
      "qty": 2,
      "type_trans": "persetujuan",
      "created_at": 1712309489,
      "updated_at": null,
      "created_by": 8,
      "updated_by": null,
      "service": {
        "id": 6369,
        "centra_id": 362,
        "code": "DE-017-000001",
        "name": "JASA;REPAIR;ENERPACK",
        "description": null,
        "uom": "LUMPSUM",
        "valid_from": "2019-09-01",
        "valid_to": "9999-12-31",
        "doc_status": "Draft",
        "apv_level": 0,
        "is_delete": 0,
        "company_id": 1,
        "created_at": "",
        "updated_at": null,
        "created_by": null,
        "updated_by": null
      }
    }
  ],
  "wo_spareparts": [
    {
      "id": 9601,
      "workorder_id": 7864,
      "code": "AA-001-000005",
      "name": "BLUE STRAND;WIRE ROPE;DIA 16 MM, IWRC, LHOL, GRADE 1960 N/MM2, KONST 6X36, UNGALV;Length 55meter",
      "quantity": 1,
      "uom": "METER",
      "type_trans": "realisasi",
      "status": 10,
      "company_id": 1,
      "created_at": "1711343304",
      "updated_at": "1711343304",
      "created_by": "1",
      "updated_by": "1",
      "wh_code": "2300",
      "wh_name": "TJ EMAS",
      "unit_code": "2300",
      "unit_name": "Site Tanjung Emas",
      "price": null,
      "eta": "2024-03-25",
      "description": "",
      "type": null
    }
  ]
} 
*/

  String? id;
  String? docNo;
  String? asset;
  String? type;
  List<WOWorkOrderSearchModelDataWoActivities?>? woActivities;
  List<WOWorkOrderSearchModelDataWoTools?>? woTools;
  List<WOWorkOrderSearchModelDataWoLabours?>? woLabours;
  List<WOWorkOrderSearchModelDataWoServices?>? woServices;
  List<WOWorkOrderSearchModelDataWoSpareparts?>? woSpareparts;

  WOWorkOrderSearchModelData({
    this.id,
    this.docNo,
    this.asset,
    this.type,
    this.woActivities,
    this.woTools,
    this.woLabours,
    this.woServices,
    this.woSpareparts,
  });
  WOWorkOrderSearchModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    docNo = json['doc_no']?.toString();
    asset = json['asset']?.toString();
    type = json['type']?.toString();
    if (json['wo_activities'] != null) {
      final v = json['wo_activities'];
      final arr0 = <WOWorkOrderSearchModelDataWoActivities>[];
      v.forEach((v) {
        arr0.add(WOWorkOrderSearchModelDataWoActivities.fromJson(v));
      });
      woActivities = arr0;
    }
    if (json['wo_tools'] != null) {
      final v = json['wo_tools'];
      final arr0 = <WOWorkOrderSearchModelDataWoTools>[];
      v.forEach((v) {
        arr0.add(WOWorkOrderSearchModelDataWoTools.fromJson(v));
      });
      woTools = arr0;
    }
    if (json['wo_labours'] != null) {
      final v = json['wo_labours'];
      final arr0 = <WOWorkOrderSearchModelDataWoLabours>[];
      v.forEach((v) {
        arr0.add(WOWorkOrderSearchModelDataWoLabours.fromJson(v));
      });
      woLabours = arr0;
    }
    if (json['wo_services'] != null) {
      final v = json['wo_services'];
      final arr0 = <WOWorkOrderSearchModelDataWoServices>[];
      v.forEach((v) {
        arr0.add(WOWorkOrderSearchModelDataWoServices.fromJson(v));
      });
      woServices = arr0;
    }
    if (json['wo_spareparts'] != null) {
      final v = json['wo_spareparts'];
      final arr0 = <WOWorkOrderSearchModelDataWoSpareparts>[];
      v.forEach((v) {
        arr0.add(WOWorkOrderSearchModelDataWoSpareparts.fromJson(v));
      });
      woSpareparts = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['doc_no'] = docNo;
    data['asset'] = asset;
    data['type'] = type;
    if (woActivities != null) {
      final v = woActivities;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['wo_activities'] = arr0;
    }
    if (woTools != null) {
      final v = woTools;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['wo_tools'] = arr0;
    }
    if (woLabours != null) {
      final v = woLabours;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['wo_labours'] = arr0;
    }
    if (woServices != null) {
      final v = woServices;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['wo_services'] = arr0;
    }
    if (woSpareparts != null) {
      final v = woSpareparts;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['wo_spareparts'] = arr0;
    }
    return data;
  }
}

class WOWorkOrderSearchModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 7864,
      "doc_no": "WO-2024-0000040",
      "asset": "Rail Mounted Gantry Crane 050-RMG-01",
      "type": "BD",
      "wo_activities": [
        {
          "id": 101880,
          "workorder_id": 7864,
          "task_number": 1,
          "task_name": "Pergantian wire rope ACM",
          "description": null,
          "type_trans": "persetujuan",
          "task_duration": "240",
          "created_at": 1711342230,
          "updated_at": 1711342230,
          "created_by": 1,
          "updated_by": 1
        }
      ],
      "wo_tools": [
        {
          "id": 31739,
          "workorder_id": 7864,
          "tools_id": 2723,
          "quantity": 1,
          "company_id": 3,
          "uom": "SET",
          "created_at": 1711343304,
          "updated_at": 1711343304,
          "created_by": 1,
          "updated_by": 1,
          "tool": {
            "id": 2723,
            "name": "Kunci Ring Pass 8-32 mm;MFR:Tekiro;PN:-",
            "satuan": "SET",
            "cabang_code": "CAB33",
            "keterangan": null,
            "condition": "Baik",
            "qty": 1,
            "company_id": 3,
            "is_active": 1,
            "is_delete": 0,
            "created_at": null,
            "updated_at": null,
            "created_by": null,
            "updated_by": null
          }
        }
      ],
      "wo_labours": [
        {
          "id": 26322,
          "workorder_id": 7864,
          "craft": {
            "id": 1,
            "name": "Mechanical"
          },
          "personil": "67910129;68110134;68510140;68710395;",
          "skill": {
            "id": 2,
            "name": "Junior Mechanic"
          },
          "amount": "4",
          "created_at": 1711343304,
          "updated_at": 1711343304,
          "created_by": 1,
          "updated_by": 1
        }
      ],
      "wo_services": [
        {
          "id": 441,
          "workorder_id": 7884,
          "service_id": "6226",
          "qty": 2,
          "type_trans": "persetujuan",
          "created_at": 1712309489,
          "updated_at": null,
          "created_by": 8,
          "updated_by": null,
          "service": {
            "id": 6369,
            "centra_id": 362,
            "code": "DE-017-000001",
            "name": "JASA;REPAIR;ENERPACK",
            "description": null,
            "uom": "LUMPSUM",
            "valid_from": "2019-09-01",
            "valid_to": "9999-12-31",
            "doc_status": "Draft",
            "apv_level": 0,
            "is_delete": 0,
            "company_id": 1,
            "created_at": "",
            "updated_at": null,
            "created_by": null,
            "updated_by": null
          }
        }
      ],
      "wo_spareparts": [
        {
          "id": 9601,
          "workorder_id": 7864,
          "code": "AA-001-000005",
          "name": "BLUE STRAND;WIRE ROPE;DIA 16 MM, IWRC, LHOL, GRADE 1960 N/MM2, KONST 6X36, UNGALV;Length 55meter",
          "quantity": 1,
          "uom": "METER",
          "type_trans": "realisasi",
          "status": 10,
          "company_id": 1,
          "created_at": "1711343304",
          "updated_at": "1711343304",
          "created_by": "1",
          "updated_by": "1",
          "wh_code": "2300",
          "wh_name": "TJ EMAS",
          "unit_code": "2300",
          "unit_name": "Site Tanjung Emas",
          "price": null,
          "eta": "2024-03-25",
          "description": "",
          "type": null
        }
      ]
    }
  ],
  "page": "1",
  "length": 10,
  "message": "Sukses"
} 
*/

  bool? success;
  List<WOWorkOrderSearchModelData?>? data;
  String? page;
  String? length;
  String? message;

  WOWorkOrderSearchModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  WOWorkOrderSearchModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WOWorkOrderSearchModelData>[];
      v.forEach((v) {
        arr0.add(WOWorkOrderSearchModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['Message'] = message;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WOAssetSearchModelDataCompany {
/*
{
  "id": 2,
  "name": "SPMT",
  "email": "plmt@pelindomultiterminal.co.id",
  "nppkp": "ANAK PERUSAHAAN",
  "alamat": "Jl. Lingkar Pelabuhan No. 1,Belawan, Medan 20411",
  "npwp": "",
  "website": "pelindomultiterminal.co.id",
  "telepon": "(061) 41000055",
  "sap_id": 2,
  "is_delete": 0,
  "is_active": 1,
  "token": null,
  "created_at": null,
  "updated_at": "1659061847",
  "created_by": null,
  "updated_by": "1"
} 
*/

  String? id;
  String? name;
  String? email;
  String? nppkp;
  String? alamat;
  String? npwp;
  String? website;
  String? telepon;
  String? sapId;
  String? isDelete;
  String? isActive;
  String? token;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;

  WOAssetSearchModelDataCompany({
    this.id,
    this.name,
    this.email,
    this.nppkp,
    this.alamat,
    this.npwp,
    this.website,
    this.telepon,
    this.sapId,
    this.isDelete,
    this.isActive,
    this.token,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });
  WOAssetSearchModelDataCompany.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    nppkp = json['nppkp']?.toString();
    alamat = json['alamat']?.toString();
    npwp = json['npwp']?.toString();
    website = json['website']?.toString();
    telepon = json['telepon']?.toString();
    sapId = json['sap_id']?.toString();
    isDelete = json['is_delete']?.toString();
    isActive = json['is_active']?.toString();
    token = json['token']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['nppkp'] = nppkp;
    data['alamat'] = alamat;
    data['npwp'] = npwp;
    data['website'] = website;
    data['telepon'] = telepon;
    data['sap_id'] = sapId;
    data['is_delete'] = isDelete;
    data['is_active'] = isActive;
    data['token'] = token;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class WOAssetSearchModelDataRegional {
/*
{
  "id": 1,
  "code": "REG01",
  "name": "SPMT",
  "description": "SUBHOLDING PELINDO MULTI TERMINAL",
  "is_delete": 0,
  "created_date": null,
  "created_by": null,
  "updated_date": "2020-09-29",
  "updated_by": ""
} 
*/

  String? id;
  String? code;
  String? name;
  String? description;
  String? isDelete;
  String? createdDate;
  String? createdBy;
  String? updatedDate;
  String? updatedBy;

  WOAssetSearchModelDataRegional({
    this.id,
    this.code,
    this.name,
    this.description,
    this.isDelete,
    this.createdDate,
    this.createdBy,
    this.updatedDate,
    this.updatedBy,
  });
  WOAssetSearchModelDataRegional.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    isDelete = json['is_delete']?.toString();
    createdDate = json['created_date']?.toString();
    createdBy = json['created_by']?.toString();
    updatedDate = json['updated_date']?.toString();
    updatedBy = json['updated_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    data['description'] = description;
    data['is_delete'] = isDelete;
    data['created_date'] = createdDate;
    data['created_by'] = createdBy;
    data['updated_date'] = updatedDate;
    data['updated_by'] = updatedBy;
    return data;
  }
}

class WOAssetSearchModelDataCabang {
/*
{
  "id": 10,
  "regional_code": "REG01",
  "code": "CAB03",
  "name": "PELABUHAN TANJUNG INTAN",
  "description": "Pelabuhan Tanjung Intan",
  "regional_name": "JAWA TENGAH",
  "is_delete": 0,
  "created_at": null,
  "created_by": null,
  "updated_at": 1699860260,
  "updated_by": 747,
  "unit_centra_id": 33,
  "unit_centra_code": "33",
  "unit_centra_name": "SITE PELABUHAN TANJUNG INTAN",
  "delivery_point": "Pelabuhan Tanjung Intan",
  "address": "Pelabuhan Tanjung Intan",
  "is_mr": 1
} 
*/

  String? id;
  String? regionalCode;
  String? code;
  String? name;
  String? description;
  String? regionalName;
  String? isDelete;
  String? createdAt;
  String? createdBy;
  String? updatedAt;
  String? updatedBy;
  String? unitCentraId;
  String? unitCentraCode;
  String? unitCentraName;
  String? deliveryPoint;
  String? address;
  String? isMr;

  WOAssetSearchModelDataCabang({
    this.id,
    this.regionalCode,
    this.code,
    this.name,
    this.description,
    this.regionalName,
    this.isDelete,
    this.createdAt,
    this.createdBy,
    this.updatedAt,
    this.updatedBy,
    this.unitCentraId,
    this.unitCentraCode,
    this.unitCentraName,
    this.deliveryPoint,
    this.address,
    this.isMr,
  });
  WOAssetSearchModelDataCabang.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    regionalCode = json['regional_code']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    regionalName = json['regional_name']?.toString();
    isDelete = json['is_delete']?.toString();
    createdAt = json['created_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedAt = json['updated_at']?.toString();
    updatedBy = json['updated_by']?.toString();
    unitCentraId = json['unit_centra_id']?.toString();
    unitCentraCode = json['unit_centra_code']?.toString();
    unitCentraName = json['unit_centra_name']?.toString();
    deliveryPoint = json['delivery_point']?.toString();
    address = json['address']?.toString();
    isMr = json['is_mr']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['regional_code'] = regionalCode;
    data['code'] = code;
    data['name'] = name;
    data['description'] = description;
    data['regional_name'] = regionalName;
    data['is_delete'] = isDelete;
    data['created_at'] = createdAt;
    data['created_by'] = createdBy;
    data['updated_at'] = updatedAt;
    data['updated_by'] = updatedBy;
    data['unit_centra_id'] = unitCentraId;
    data['unit_centra_code'] = unitCentraCode;
    data['unit_centra_name'] = unitCentraName;
    data['delivery_point'] = deliveryPoint;
    data['address'] = address;
    data['is_mr'] = isMr;
    return data;
  }
}

class WOAssetSearchModelData {
/*
{
  "id": 1,
  "code": "BCT015-0008",
  "name": "Bucket-08 15 Ton",
  "kapasitas": "15 Ton",
  "merk": "-",
  "country_of_origin": null,
  "equipment_serial_number": null,
  "model": null,
  "power_source": null,
  "merk_engine": null,
  "engine_type": null,
  "serial_number_engine": null,
  "jenis_asset_code": "A14",
  "regional_code": "REG01",
  "cabang_code": "CAB03",
  "tahun": 0,
  "is_delete": 0,
  "is_downtime": 0,
  "is_active": 1,
  "company_id": 2,
  "doc_status": "Completed",
  "apv_level": 1,
  "created_at": "1655891721",
  "updated_at": "1659063671",
  "created_by": 4,
  "updated_by": 4,
  "cabang": {
    "id": 10,
    "regional_code": "REG01",
    "code": "CAB03",
    "name": "PELABUHAN TANJUNG INTAN",
    "description": "Pelabuhan Tanjung Intan",
    "regional_name": "JAWA TENGAH",
    "is_delete": 0,
    "created_at": null,
    "created_by": null,
    "updated_at": 1699860260,
    "updated_by": 747,
    "unit_centra_id": 33,
    "unit_centra_code": "33",
    "unit_centra_name": "SITE PELABUHAN TANJUNG INTAN",
    "delivery_point": "Pelabuhan Tanjung Intan",
    "address": "Pelabuhan Tanjung Intan",
    "is_mr": 1
  },
  "regional": {
    "id": 1,
    "code": "REG01",
    "name": "SPMT",
    "description": "SUBHOLDING PELINDO MULTI TERMINAL",
    "is_delete": 0,
    "created_date": null,
    "created_by": null,
    "updated_date": "2020-09-29",
    "updated_by": ""
  },
  "company": {
    "id": 2,
    "name": "SPMT",
    "email": "plmt@pelindomultiterminal.co.id",
    "nppkp": "ANAK PERUSAHAAN",
    "alamat": "Jl. Lingkar Pelabuhan No. 1,Belawan, Medan 20411",
    "npwp": "",
    "website": "pelindomultiterminal.co.id",
    "telepon": "(061) 41000055",
    "sap_id": 2,
    "is_delete": 0,
    "is_active": 1,
    "token": null,
    "created_at": null,
    "updated_at": "1659061847",
    "created_by": null,
    "updated_by": "1"
  }
} 
*/

  String? id;
  String? code;
  String? name;
  String? kapasitas;
  String? merk;
  String? countryOfOrigin;
  String? equipmentSerialNumber;
  String? model;
  String? powerSource;
  String? merkEngine;
  String? engineType;
  String? serialNumberEngine;
  String? jenisAssetCode;
  String? regionalCode;
  String? cabangCode;
  String? tahun;
  String? isDelete;
  String? isDowntime;
  String? isActive;
  String? companyId;
  String? docStatus;
  String? apvLevel;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;
  WOAssetSearchModelDataCabang? cabang;
  WOAssetSearchModelDataRegional? regional;
  WOAssetSearchModelDataCompany? company;

  WOAssetSearchModelData({
    this.id,
    this.code,
    this.name,
    this.kapasitas,
    this.merk,
    this.countryOfOrigin,
    this.equipmentSerialNumber,
    this.model,
    this.powerSource,
    this.merkEngine,
    this.engineType,
    this.serialNumberEngine,
    this.jenisAssetCode,
    this.regionalCode,
    this.cabangCode,
    this.tahun,
    this.isDelete,
    this.isDowntime,
    this.isActive,
    this.companyId,
    this.docStatus,
    this.apvLevel,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
    this.cabang,
    this.regional,
    this.company,
  });
  WOAssetSearchModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    kapasitas = json['kapasitas']?.toString();
    merk = json['merk']?.toString();
    countryOfOrigin = json['country_of_origin']?.toString();
    equipmentSerialNumber = json['equipment_serial_number']?.toString();
    model = json['model']?.toString();
    powerSource = json['power_source']?.toString();
    merkEngine = json['merk_engine']?.toString();
    engineType = json['engine_type']?.toString();
    serialNumberEngine = json['serial_number_engine']?.toString();
    jenisAssetCode = json['jenis_asset_code']?.toString();
    regionalCode = json['regional_code']?.toString();
    cabangCode = json['cabang_code']?.toString();
    tahun = json['tahun']?.toString();
    isDelete = json['is_delete']?.toString();
    isDowntime = json['is_downtime']?.toString();
    isActive = json['is_active']?.toString();
    companyId = json['company_id']?.toString();
    docStatus = json['doc_status']?.toString();
    apvLevel = json['apv_level']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
    cabang = (json['cabang'] != null)
        ? WOAssetSearchModelDataCabang.fromJson(json['cabang'])
        : null;
    regional = (json['regional'] != null)
        ? WOAssetSearchModelDataRegional.fromJson(json['regional'])
        : null;
    company = (json['company'] != null)
        ? WOAssetSearchModelDataCompany.fromJson(json['company'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    data['kapasitas'] = kapasitas;
    data['merk'] = merk;
    data['country_of_origin'] = countryOfOrigin;
    data['equipment_serial_number'] = equipmentSerialNumber;
    data['model'] = model;
    data['power_source'] = powerSource;
    data['merk_engine'] = merkEngine;
    data['engine_type'] = engineType;
    data['serial_number_engine'] = serialNumberEngine;
    data['jenis_asset_code'] = jenisAssetCode;
    data['regional_code'] = regionalCode;
    data['cabang_code'] = cabangCode;
    data['tahun'] = tahun;
    data['is_delete'] = isDelete;
    data['is_downtime'] = isDowntime;
    data['is_active'] = isActive;
    data['company_id'] = companyId;
    data['doc_status'] = docStatus;
    data['apv_level'] = apvLevel;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    if (cabang != null) {
      data['cabang'] = cabang!.toJson();
    }
    if (regional != null) {
      data['regional'] = regional!.toJson();
    }
    if (company != null) {
      data['company'] = company!.toJson();
    }
    return data;
  }
}

class WOAssetSearchModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 1,
      "code": "BCT015-0008",
      "name": "Bucket-08 15 Ton",
      "kapasitas": "15 Ton",
      "merk": "-",
      "country_of_origin": null,
      "equipment_serial_number": null,
      "model": null,
      "power_source": null,
      "merk_engine": null,
      "engine_type": null,
      "serial_number_engine": null,
      "jenis_asset_code": "A14",
      "regional_code": "REG01",
      "cabang_code": "CAB03",
      "tahun": 0,
      "is_delete": 0,
      "is_downtime": 0,
      "is_active": 1,
      "company_id": 2,
      "doc_status": "Completed",
      "apv_level": 1,
      "created_at": "1655891721",
      "updated_at": "1659063671",
      "created_by": 4,
      "updated_by": 4,
      "cabang": {
        "id": 10,
        "regional_code": "REG01",
        "code": "CAB03",
        "name": "PELABUHAN TANJUNG INTAN",
        "description": "Pelabuhan Tanjung Intan",
        "regional_name": "JAWA TENGAH",
        "is_delete": 0,
        "created_at": null,
        "created_by": null,
        "updated_at": 1699860260,
        "updated_by": 747,
        "unit_centra_id": 33,
        "unit_centra_code": "33",
        "unit_centra_name": "SITE PELABUHAN TANJUNG INTAN",
        "delivery_point": "Pelabuhan Tanjung Intan",
        "address": "Pelabuhan Tanjung Intan",
        "is_mr": 1
      },
      "regional": {
        "id": 1,
        "code": "REG01",
        "name": "SPMT",
        "description": "SUBHOLDING PELINDO MULTI TERMINAL",
        "is_delete": 0,
        "created_date": null,
        "created_by": null,
        "updated_date": "2020-09-29",
        "updated_by": ""
      },
      "company": {
        "id": 2,
        "name": "SPMT",
        "email": "plmt@pelindomultiterminal.co.id",
        "nppkp": "ANAK PERUSAHAAN",
        "alamat": "Jl. Lingkar Pelabuhan No. 1,Belawan, Medan 20411",
        "npwp": "",
        "website": "pelindomultiterminal.co.id",
        "telepon": "(061) 41000055",
        "sap_id": 2,
        "is_delete": 0,
        "is_active": 1,
        "token": null,
        "created_at": null,
        "updated_at": "1659061847",
        "created_by": null,
        "updated_by": "1"
      }
    }
  ],
  "page": 1,
  "length": 10,
  "message": "Sukses"
} 
*/

  bool? success;
  List<WOAssetSearchModelData?>? data;
  String? page;
  String? length;
  String? message;

  WOAssetSearchModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  WOAssetSearchModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WOAssetSearchModelData>[];
      v.forEach((v) {
        arr0.add(WOAssetSearchModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['Message'] = message;
    return data;
  }
}
