///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserDetailModelData {
/*
{
  "Id": "01J1WQEDH0SZYZWAC1Z9QDTXCK",
  "Name": "UP Brantas",
  "Username": "upbrantas",
  "Email": "upbrantas@gmail.com",
  "Division": "Engineer",
  "Role": "admin",
  "Status": "active",
  "CreatedAt": "2024-07-03 23:39:34",
  "UpdatedAt": ""
} 
*/

  String? Id;
  String? Name;
  String? Username;
  String? Email;
  String? Division;
  String? Role;
  String? Status;
  String? CreatedAt;
  String? UpdatedAt;

  UserDetailModelData({
    this.Id,
    this.Name,
    this.Username,
    this.Email,
    this.Division,
    this.Role,
    this.Status,
    this.CreatedAt,
    this.UpdatedAt,
  });
  UserDetailModelData.fromJson(Map<String, dynamic> json) {
    Id = json['Id']?.toString();
    Name = json['Name']?.toString();
    Username = json['Username']?.toString();
    Email = json['Email']?.toString();
    Division = json['Division']?.toString();
    Role = json['Role']?.toString();
    Status = json['Status']?.toString();
    CreatedAt = json['CreatedAt']?.toString();
    UpdatedAt = json['UpdatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Id'] = Id;
    data['Name'] = Name;
    data['Username'] = Username;
    data['Email'] = Email;
    data['Division'] = Division;
    data['Role'] = Role;
    data['Status'] = Status;
    data['CreatedAt'] = CreatedAt;
    data['UpdatedAt'] = UpdatedAt;
    return data;
  }
}

class UserDetailModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil mendapatkan user",
  "Data": {
    "Id": "01J1WQEDH0SZYZWAC1Z9QDTXCK",
    "Name": "UP Brantas",
    "Username": "upbrantas",
    "Email": "upbrantas@gmail.com",
    "Division": "Engineer",
    "Role": "admin",
    "Status": "active",
    "CreatedAt": "2024-07-03 23:39:34",
    "UpdatedAt": ""
  }
} 
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  UserDetailModelData? Data;

  UserDetailModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
  });
  UserDetailModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    Data = (json['Data'] != null) ? UserDetailModelData.fromJson(json['Data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
