///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WOLaboursCraftModelData {
/*
{
  "id": 1,
  "name": "Mechanical"
} 
*/

  String? id;
  String? name;

  WOLaboursCraftModelData({
    this.id,
    this.name,
  });
  WOLaboursCraftModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class WOLaboursCraftModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 1,
      "name": "Mechanical"
    }
  ],
  "page": -1,
  "length": 3,
  "message": "Sukses"
} 
*/

  bool? success;
  List<WOLaboursCraftModelData?>? data;
  String? page;
  String? length;
  String? message;

  WOLaboursCraftModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  WOLaboursCraftModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WOLaboursCraftModelData>[];
      v.forEach((v) {
        arr0.add(WOLaboursCraftModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['Message'] = message;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WOLaboursSkillModelData {
/*
{
  "id": 1,
  "name": "Junior Electric"
} 
*/

  String? id;
  String? name;

  WOLaboursSkillModelData({
    this.id,
    this.name,
  });
  WOLaboursSkillModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class WOLaboursSkillModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 1,
      "name": "Junior Electric"
    }
  ],
  "page": -1,
  "length": 8,
  "message": "Sukses"
} 
*/

  bool? success;
  List<WOLaboursSkillModelData?>? data;
  String? page;
  String? length;
  String? message;

  WOLaboursSkillModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  WOLaboursSkillModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WOLaboursSkillModelData>[];
      v.forEach((v) {
        arr0.add(WOLaboursSkillModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['Message'] = message;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WOCheckOAModelData {
/*
{
  "type": "Non OA",
  "qty": 0,
  "purchase_price": 0,
  "sale_price": 0,
  "doc_date": null
} 
*/

  String? type;
  String? qty;
  String? purchasePrice;
  String? salePrice;
  String? docDate;

  WOCheckOAModelData({
    this.type,
    this.qty,
    this.purchasePrice,
    this.salePrice,
    this.docDate,
  });
  WOCheckOAModelData.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    qty = json['qty']?.toString();
    purchasePrice = json['purchase_price']?.toString();
    salePrice = json['sale_price']?.toString();
    docDate = json['doc_date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['qty'] = qty;
    data['purchase_price'] = purchasePrice;
    data['sale_price'] = salePrice;
    data['doc_date'] = docDate;
    return data;
  }
}

class WOCheckOAModel {
/*
{
  "success": true,
  "data": {
    "type": "Non OA",
    "qty": 0,
    "purchase_price": 0,
    "sale_price": 0,
    "doc_date": null
  },
  "message": "Sukses"
} 
*/

  bool? success;
  WOCheckOAModelData? data;
  String? message;

  WOCheckOAModel({
    this.success,
    this.data,
    this.message,
  });
  WOCheckOAModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? WOCheckOAModelData.fromJson(json['data'])
        : null;
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['Message'] = message;
    return data;
  }
}
