///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TowerModelData {
/*
{
  "Id": "01J06EX7EJHFXC47Y6AE8SSPTC",
  "Name": "PLTA Malang - 0H823A1"
} 
*/

  String? Id;
  String? Name;

  TowerModelData({
    this.Id,
    this.Name,
  });
  TowerModelData.fromJson(Map<String, dynamic> json) {
    Id = json['Id']?.toString();
    Name = json['Name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Id'] = Id;
    data['Name'] = Name;
    return data;
  }
}

class TowerModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil mendapatkan semua tower master",
  "Data": [
    {
      "Id": "01J06EX7EJHFXC47Y6AE8SSPTC",
      "Name": "PLTA Malang - 0H823A1"
    }
  ]
} 
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  List<TowerModelData?>? Data;

  TowerModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
  });
  TowerModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    if (json['Data'] != null) {
      final v = json['Data'];
      final arr0 = <TowerModelData>[];
      v.forEach((v) {
        arr0.add(TowerModelData.fromJson(v));
      });
      Data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      final v = Data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Data'] = arr0;
    }
    return data;
  }
}
