///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PaketCityDepartureModelData {
/*
{
  "id": 5,
  "country_id": 1,
  "code": "SBY",
  "name": "Surabaya",
  "is_active": 1
} 
*/

  int? id;
  int? countryId;
  String? code;
  String? name;
  int? isActive;

  PaketCityDepartureModelData({
    this.id,
    this.countryId,
    this.code,
    this.name,
    this.isActive,
  });
  PaketCityDepartureModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    countryId = json['country_id']?.toInt();
    code = json['code']?.toString();
    name = json['name']?.toString();
    isActive = json['is_active']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['country_id'] = countryId;
    data['code'] = code;
    data['name'] = name;
    data['is_active'] = isActive;
    return data;
  }
}

class PaketCityDepartureModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 5,
      "country_id": 1,
      "code": "SBY",
      "name": "Surabaya",
      "is_active": 1
    }
  ],
  "message": "success"
} 
*/

  bool? success;
  List<PaketCityDepartureModelData?>? data;
  String? message;

  PaketCityDepartureModel({
    this.success,
    this.data,
    this.message,
  });
  PaketCityDepartureModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <PaketCityDepartureModelData>[];
      v.forEach((v) {
        arr0.add(PaketCityDepartureModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
