///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PaketDetailModelDataRoom {
/*
{
  "id": 3,
  "name": "Quad",
  "capacity": 4,
  "price": 26000000,
  "price_short": "Rp. 26.000.000"
} 
*/

  int? id;
  String? name;
  int? capacity;
  int? price;
  String? priceShort;

  PaketDetailModelDataRoom({
    this.id,
    this.name,
    this.capacity,
    this.price,
    this.priceShort,
  });
  PaketDetailModelDataRoom.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    capacity = json['capacity']?.toInt();
    price = json['price']?.toInt();
    priceShort = json['price_short']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['capacity'] = capacity;
    data['price'] = price;
    data['price_short'] = priceShort;
    return data;
  }
}

class PaketDetailModelDataAgenda {
/*
{
  "day": 1,
  "description": "07.00\nJamaah Chatour berkumpul di bandara Juanda terminal 1A {domestik}\n07.30\nPengarahan tekhnis dan doa bersama, serta perpisahan dengan anggota keluarga\n08.00 \nIstirahat, makan siang, di ruang excutive lounge bandara, boarding dan chek imigrasi\n11.40\nBismillah terbang dari Surabaya menuju Madinah dengan Saudi Arabian Airlines SV 3595\nDilanjutkan sholat Dzuhur dengan menjamak takdim Ashr di dalam pesawat\n18.00\nAlhamdulillah tiba di bandara Prince Mohammed Madinah di lanjutkan dengan proses imigrasi dan pengambilan bagasi, jamaah dijemput oleh staff perwakilan kemudian melanjutkan perjalanan menuju hotel dengan bus.  \n20.00\nTiba di hotel, pembagian kunci kamar dan istirahat dilanjutkan sholat Isya’ dengan menjamak ta’khir dimasjid Nabawi",
  "banner_path": "https://dev.chatourtravel.id/chatour/media/image-no.jpg"
} 
*/

  int? day;
  String? description;
  String? bannerPath;

  PaketDetailModelDataAgenda({
    this.day,
    this.description,
    this.bannerPath,
  });
  PaketDetailModelDataAgenda.fromJson(Map<String, dynamic> json) {
    day = json['day']?.toInt();
    description = json['description']?.toString();
    bannerPath = json['banner_path']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['day'] = day;
    data['description'] = description;
    data['banner_path'] = bannerPath;
    return data;
  }
}

class PaketDetailModelDataHotel {
/*
{
  "id": 5,
  "name": "ANJUM",
  "rating": 0,
  "map_url": "null",
  "picture_path": "https://dev.chatourtravel.id/media/hotel-picture-1676367381.png",
  "city": "Mekkah",
  "banner": [
    ""
  ]
} 
*/

  int? id;
  String? name;
  int? rating;
  String? mapUrl;
  String? picturePath;
  String? city;
  List<String?>? banner;

  PaketDetailModelDataHotel({
    this.id,
    this.name,
    this.rating,
    this.mapUrl,
    this.picturePath,
    this.city,
    this.banner,
  });
  PaketDetailModelDataHotel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    rating = json['rating']?.toInt();
    mapUrl = json['map_url']?.toString();
    picturePath = json['picture_path']?.toString();
    city = json['city']?.toString();
    if (json['banner'] != null) {
      final v = json['banner'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      banner = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['rating'] = rating;
    data['map_url'] = mapUrl;
    data['picture_path'] = picturePath;
    data['city'] = city;
    if (banner != null) {
      final v = banner;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['banner'] = arr0;
    }
    return data;
  }
}

class PaketDetailModelDataFacilityNotIncluded {
/*
{
  "name": "Termasuk Perlengkapan Ibadah",
  "icon_path": "https://dev.chatourtravel.id/media/facility-icon-1676275916.png"
} 
*/

  String? name;
  String? iconPath;

  PaketDetailModelDataFacilityNotIncluded({
    this.name,
    this.iconPath,
  });
  PaketDetailModelDataFacilityNotIncluded.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    iconPath = json['icon_path']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['icon_path'] = iconPath;
    return data;
  }
}

class PaketDetailModelDataFacility {
/*
{
  "name": "Sudah termasuk PPN 10% Saudia",
  "icon_path": "https://dev.chatourtravel.id/media/facility-icon-1676274964.png"
} 
*/

  String? name;
  String? iconPath;

  PaketDetailModelDataFacility({
    this.name,
    this.iconPath,
  });
  PaketDetailModelDataFacility.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    iconPath = json['icon_path']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['icon_path'] = iconPath;
    return data;
  }
}

class PaketDetailModelData {
/*
{
  "id": 59,
  "city_name": "Surabaya",
  "name": "UMRAH RAMADHAN PLUS",
  "date_departure": "",
  "duration": 10,
  "price": "Rp. 26.000.000",
  "thumbnail_path": "https://dev.chatourtravel.id/media/package-thumbnail-1676365890.png",
  "banner": [
    "https://dev.chatourtravel.id/media/package-banner-1676365890.png"
  ],
  "description": "Paket ini menawarkan jarak hotel paling dekat dan nyaman untuk keluarga. Dengan pilihan Hotel terbaik dikelasnya serta dengan pilihan terbaik keluarga, jamaah dipastikan mersakan kenyamanan ibadah yang aman,khusyuk, dan menyenangkan. Paket ini paling cocok untuk anda yang ingin berangkat bersama keluarga dengan usia balita dan bersama orang tua.",
  "facility": [
    {
      "name": "Sudah termasuk PPN 10% Saudia",
      "icon_path": "https://dev.chatourtravel.id/media/facility-icon-1676274964.png"
    }
  ],
  "facility_not_included": [
    {
      "name": "Termasuk Perlengkapan Ibadah",
      "icon_path": "https://dev.chatourtravel.id/media/facility-icon-1676275916.png"
    }
  ],
  "hotel": [
    {
      "id": 5,
      "name": "ANJUM",
      "rating": 0,
      "map_url": "null",
      "picture_path": "https://dev.chatourtravel.id/media/hotel-picture-1676367381.png",
      "city": "Mekkah",
      "banner": [
        ""
      ]
    }
  ],
  "agenda": [
    {
      "day": 1,
      "description": "07.00\nJamaah Chatour berkumpul di bandara Juanda terminal 1A {domestik}\n07.30\nPengarahan tekhnis dan doa bersama, serta perpisahan dengan anggota keluarga\n08.00 \nIstirahat, makan siang, di ruang excutive lounge bandara, boarding dan chek imigrasi\n11.40\nBismillah terbang dari Surabaya menuju Madinah dengan Saudi Arabian Airlines SV 3595\nDilanjutkan sholat Dzuhur dengan menjamak takdim Ashr di dalam pesawat\n18.00\nAlhamdulillah tiba di bandara Prince Mohammed Madinah di lanjutkan dengan proses imigrasi dan pengambilan bagasi, jamaah dijemput oleh staff perwakilan kemudian melanjutkan perjalanan menuju hotel dengan bus.  \n20.00\nTiba di hotel, pembagian kunci kamar dan istirahat dilanjutkan sholat Isya’ dengan menjamak ta’khir dimasjid Nabawi",
      "banner_path": "https://dev.chatourtravel.id/chatour/media/image-no.jpg"
    }
  ],
  "room": [
    {
      "id": 3,
      "name": "Quad",
      "capacity": 4,
      "price": 26000000,
      "price_short": "Rp. 26.000.000"
    }
  ]
} 
*/

  int? id;
  String? cityName;
  String? name;
  String? dateDeparture;
  int? duration;
  String? price;
  String? thumbnailPath;
  String? brochureDownload;
  List<String?>? banner;
  String? description;
  List<PaketDetailModelDataFacility?>? facility;
  List<PaketDetailModelDataFacilityNotIncluded?>? facilityNotIncluded;
  List<PaketDetailModelDataHotel?>? hotel;
  List<PaketDetailModelDataAgenda?>? agenda;
  List<PaketDetailModelDataRoom?>? room;

  PaketDetailModelData({
    this.id,
    this.cityName,
    this.name,
    this.dateDeparture,
    this.duration,
    this.price,
    this.thumbnailPath,
    this.brochureDownload,
    this.banner,
    this.description,
    this.facility,
    this.facilityNotIncluded,
    this.hotel,
    this.agenda,
    this.room,
  });
  PaketDetailModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    cityName = json['city_name']?.toString();
    name = json['name']?.toString();
    dateDeparture = json['date_departure']?.toString();
    duration = json['duration']?.toInt();
    price = json['price']?.toString();
    thumbnailPath = json['thumbnail_path']?.toString();
    brochureDownload = json['brochure_download']?.toString();
    if (json['banner'] != null) {
      final v = json['banner'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      banner = arr0;
    }
    description = json['description']?.toString();
    if (json['facility'] != null) {
      final v = json['facility'];
      final arr0 = <PaketDetailModelDataFacility>[];
      v.forEach((v) {
        arr0.add(PaketDetailModelDataFacility.fromJson(v));
      });
      facility = arr0;
    }
    if (json['facility_not_included'] != null) {
      final v = json['facility_not_included'];
      final arr0 = <PaketDetailModelDataFacilityNotIncluded>[];
      v.forEach((v) {
        arr0.add(PaketDetailModelDataFacilityNotIncluded.fromJson(v));
      });
      facilityNotIncluded = arr0;
    }
    if (json['hotel'] != null) {
      final v = json['hotel'];
      final arr0 = <PaketDetailModelDataHotel>[];
      v.forEach((v) {
        arr0.add(PaketDetailModelDataHotel.fromJson(v));
      });
      hotel = arr0;
    }
    if (json['agenda'] != null) {
      final v = json['agenda'];
      final arr0 = <PaketDetailModelDataAgenda>[];
      v.forEach((v) {
        arr0.add(PaketDetailModelDataAgenda.fromJson(v));
      });
      agenda = arr0;
    }
    if (json['room'] != null) {
      final v = json['room'];
      final arr0 = <PaketDetailModelDataRoom>[];
      v.forEach((v) {
        arr0.add(PaketDetailModelDataRoom.fromJson(v));
      });
      room = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['city_name'] = cityName;
    data['name'] = name;
    data['date_departure'] = dateDeparture;
    data['duration'] = duration;
    data['price'] = price;
    data['thumbnail_path'] = thumbnailPath;
    data['brochure_download'] = brochureDownload;
    if (banner != null) {
      final v = banner;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['banner'] = arr0;
    }
    data['description'] = description;
    if (facility != null) {
      final v = facility;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['facility'] = arr0;
    }
    if (facilityNotIncluded != null) {
      final v = facilityNotIncluded;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['facility_not_included'] = arr0;
    }
    if (hotel != null) {
      final v = hotel;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['hotel'] = arr0;
    }
    if (agenda != null) {
      final v = agenda;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['agenda'] = arr0;
    }
    if (room != null) {
      final v = room;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['room'] = arr0;
    }
    return data;
  }
}

class PaketDetailModel {
/*
{
  "success": true,
  "data": {
    "id": 59,
    "city_name": "Surabaya",
    "name": "UMRAH RAMADHAN PLUS",
    "date_departure": "",
    "duration": 10,
    "price": "Rp. 26.000.000",
    "thumbnail_path": "https://dev.chatourtravel.id/media/package-thumbnail-1676365890.png",
    "banner": [
      "https://dev.chatourtravel.id/media/package-banner-1676365890.png"
    ],
    "description": "Paket ini menawarkan jarak hotel paling dekat dan nyaman untuk keluarga. Dengan pilihan Hotel terbaik dikelasnya serta dengan pilihan terbaik keluarga, jamaah dipastikan mersakan kenyamanan ibadah yang aman,khusyuk, dan menyenangkan. Paket ini paling cocok untuk anda yang ingin berangkat bersama keluarga dengan usia balita dan bersama orang tua.",
    "facility": [
      {
        "name": "Sudah termasuk PPN 10% Saudia",
        "icon_path": "https://dev.chatourtravel.id/media/facility-icon-1676274964.png"
      }
    ],
    "facility_not_included": [
      {
        "name": "Termasuk Perlengkapan Ibadah",
        "icon_path": "https://dev.chatourtravel.id/media/facility-icon-1676275916.png"
      }
    ],
    "hotel": [
      {
        "id": 5,
        "name": "ANJUM",
        "rating": 0,
        "map_url": "null",
        "picture_path": "https://dev.chatourtravel.id/media/hotel-picture-1676367381.png",
        "city": "Mekkah",
        "banner": [
          ""
        ]
      }
    ],
    "agenda": [
      {
        "day": 1,
        "description": "07.00\nJamaah Chatour berkumpul di bandara Juanda terminal 1A {domestik}\n07.30\nPengarahan tekhnis dan doa bersama, serta perpisahan dengan anggota keluarga\n08.00 \nIstirahat, makan siang, di ruang excutive lounge bandara, boarding dan chek imigrasi\n11.40\nBismillah terbang dari Surabaya menuju Madinah dengan Saudi Arabian Airlines SV 3595\nDilanjutkan sholat Dzuhur dengan menjamak takdim Ashr di dalam pesawat\n18.00\nAlhamdulillah tiba di bandara Prince Mohammed Madinah di lanjutkan dengan proses imigrasi dan pengambilan bagasi, jamaah dijemput oleh staff perwakilan kemudian melanjutkan perjalanan menuju hotel dengan bus.  \n20.00\nTiba di hotel, pembagian kunci kamar dan istirahat dilanjutkan sholat Isya’ dengan menjamak ta’khir dimasjid Nabawi",
        "banner_path": "https://dev.chatourtravel.id/chatour/media/image-no.jpg"
      }
    ],
    "room": [
      {
        "id": 3,
        "name": "Quad",
        "capacity": 4,
        "price": 26000000,
        "price_short": "Rp. 26.000.000"
      }
    ]
  },
  "message": "success"
} 
*/

  bool? success;
  PaketDetailModelData? data;
  String? message;

  PaketDetailModel({
    this.success,
    this.data,
    this.message,
  });
  PaketDetailModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? PaketDetailModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
