///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PaketModelData {
/*
{
  "id": 59,
  "city_name": "Surabaya",
  "name": "UMRAH RAMADHAN PLUS",
  "price": "Rp. 26.000.000",
  "curency": "IDR",
  "icon_path": "https://chatour.xenopati.id/media/package-thumbnail-1676365890.png",
  "day": 10,
  "thumbnail_path": "https://chatour.xenopati.id/media/package-thumbnail-1676365890.png",
  "banner_path": "https://chatour.xenopati.id/media/package-banner-1676365890.png"
} 
*/

  int? id;
  String? cityName;
  String? name;
  String? price;
  String? curency;
  String? iconPath;
  int? day;
  String? thumbnailPath;
  String? bannerPath;

  PaketModelData({
    this.id,
    this.cityName,
    this.name,
    this.price,
    this.curency,
    this.iconPath,
    this.day,
    this.thumbnailPath,
    this.bannerPath,
  });
  PaketModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    cityName = json['city_name']?.toString();
    name = json['name']?.toString();
    price = json['price']?.toString();
    curency = json['curency']?.toString();
    iconPath = json['icon_path']?.toString();
    day = json['day']?.toInt();
    thumbnailPath = json['thumbnail_path']?.toString();
    bannerPath = json['banner_path']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['city_name'] = cityName;
    data['name'] = name;
    data['price'] = price;
    data['curency'] = curency;
    data['icon_path'] = iconPath;
    data['day'] = day;
    data['thumbnail_path'] = thumbnailPath;
    data['banner_path'] = bannerPath;
    return data;
  }
}

class PaketModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 59,
      "city_name": "Surabaya",
      "name": "UMRAH RAMADHAN PLUS",
      "price": "Rp. 26.000.000",
      "curency": "IDR",
      "icon_path": "https://chatour.xenopati.id/media/package-thumbnail-1676365890.png",
      "day": 10,
      "thumbnail_path": "https://chatour.xenopati.id/media/package-thumbnail-1676365890.png",
      "banner_path": "https://chatour.xenopati.id/media/package-banner-1676365890.png"
    }
  ],
  "message": "success"
} 
*/

  bool? success;
  List<PaketModelData?>? data;
  String? message;

  PaketModel({
    this.success,
    this.data,
    this.message,
  });
  PaketModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <PaketModelData>[];
      v.forEach((v) {
        arr0.add(PaketModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
