///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ScheduleModelData {
/*
{
  "id": 81,
  "date_departure": "2023-05-17T17:00:00.000000Z",
  "short_date": "Kamis, 18 Mei 2023",
  "date_month_year": "Mei 2023",
  "date_day": "18",
  "date_departure_ymd": "2023-05-18"
}
*/

  int? id;
  String? dateDeparture;
  String? shortDate;
  String? dateMonthYear;
  String? dateDay;
  String? dateDepartureYmd;

  ScheduleModelData({
    this.id,
    this.dateDeparture,
    this.shortDate,
    this.dateMonthYear,
    this.dateDay,
    this.dateDepartureYmd,
  });
  ScheduleModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    dateDeparture = json['date_departure']?.toString();
    shortDate = json['short_date']?.toString();
    dateMonthYear = json['date_month_year']?.toString();
    dateDay = json['date_day']?.toString();
    dateDepartureYmd = json['date_departure_ymd']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['date_departure'] = dateDeparture;
    data['short_date'] = shortDate;
    data['date_month_year'] = dateMonthYear;
    data['date_day'] = dateDay;
    data['date_departure_ymd'] = dateDepartureYmd;
    return data;
  }
}

class ScheduleModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 81,
      "date_departure": "2023-05-17T17:00:00.000000Z",
      "short_date": "Kamis, 18 Mei 2023",
      "date_month_year": "Mei 2023",
      "date_day": "18",
      "date_departure_ymd": "2023-05-18"
    }
  ],
  "message": "success"
}
*/

  bool? success;
  List<ScheduleModelData?>? data;
  String? message;

  ScheduleModel({
    this.success,
    this.data,
    this.message,
  });
  ScheduleModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ScheduleModelData>[];
      v.forEach((v) {
        arr0.add(ScheduleModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
