///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AssetDowntimeCategoryModelData {
/*
{
  "id": 6,
  "code": "B-HRM",
  "name": "B-HRM",
  "uom": "JAM",
  "parent": 0
} 
*/

  String? id;
  String? code;
  String? name;
  String? uom;
  String? parent;

  AssetDowntimeCategoryModelData({
    this.id,
    this.code,
    this.name,
    this.uom,
    this.parent,
  });
  AssetDowntimeCategoryModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    uom = json['uom']?.toString();
    parent = json['parent']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    data['uom'] = uom;
    data['parent'] = parent;
    return data;
  }
}

class AssetDowntimeCategoryModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 6,
      "code": "B-HRM",
      "name": "B-HRM",
      "uom": "JAM",
      "parent": 0
    }
  ],
  "page": 1,
  "length": 10,
  "message": "Sukses"
} 
*/

  bool? success;
  List<AssetDowntimeCategoryModelData?>? data;
  String? page;
  String? length;
  String? message;

  AssetDowntimeCategoryModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  AssetDowntimeCategoryModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <AssetDowntimeCategoryModelData>[];
      v.forEach((v) {
        arr0.add(AssetDowntimeCategoryModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['message'] = message;
    return data;
  }
}
