///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AssetPerformanceModelData {
/*
{
  "id": 4,
  "doc_no": "000004/BA.AP/BIMOPS/I/2023",
  "date_doc": "2023-01-24",
  "doc_status": "Draft",
  "apv_level": 0,
  "year": 2023,
  "period_no": 1,
  "cabang_code": "CAB08",
  "created_at": 1674554906,
  "updated_at": null,
  "created_by": 37,
  "updated_by": null,
  "is_delete": 0,
  "company_id": 1,
  "site": "PELABUHAN BAGENDANG"
} 
*/

  String? id;
  String? docNo;
  String? dateDoc;
  String? docStatus;
  String? apvLevel;
  String? year;
  String? periodNo;
  String? cabangCode;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;
  String? isDelete;
  String? companyId;
  String? site;

  AssetPerformanceModelData({
    this.id,
    this.docNo,
    this.dateDoc,
    this.docStatus,
    this.apvLevel,
    this.year,
    this.periodNo,
    this.cabangCode,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
    this.isDelete,
    this.companyId,
    this.site,
  });
  AssetPerformanceModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    docNo = json['doc_no']?.toString();
    dateDoc = json['date_doc']?.toString();
    docStatus = json['doc_status']?.toString();
    apvLevel = json['apv_level']?.toString();
    year = json['year']?.toString();
    periodNo = json['period_no']?.toString();
    cabangCode = json['cabang_code']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
    isDelete = json['is_delete']?.toString();
    companyId = json['company_id']?.toString();
    site = json['site']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['doc_no'] = docNo;
    data['date_doc'] = dateDoc;
    data['doc_status'] = docStatus;
    data['apv_level'] = apvLevel;
    data['year'] = year;
    data['period_no'] = periodNo;
    data['cabang_code'] = cabangCode;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    data['is_delete'] = isDelete;
    data['company_id'] = companyId;
    data['site'] = site;
    return data;
  }
}

class AssetPerformanceModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 4,
      "doc_no": "000004/BA.AP/BIMOPS/I/2023",
      "date_doc": "2023-01-24",
      "doc_status": "Draft",
      "apv_level": 0,
      "year": 2023,
      "period_no": 1,
      "cabang_code": "CAB08",
      "created_at": 1674554906,
      "updated_at": null,
      "created_by": 37,
      "updated_by": null,
      "is_delete": 0,
      "company_id": 1,
      "site": "PELABUHAN BAGENDANG"
    }
  ],
  "page": 1,
  "length": 1,
  "message": "Sukses"
} 
*/

  bool? success;
  List<AssetPerformanceModelData?>? data;
  String? page;
  String? length;
  String? message;

  AssetPerformanceModel({
    this.success,
    this.data,
    this.page,
    this.length,
    this.message,
  });
  AssetPerformanceModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <AssetPerformanceModelData>[];
      v.forEach((v) {
        arr0.add(AssetPerformanceModelData.fromJson(v));
      });
      this.data = arr0;
    }
    page = json['page']?.toString();
    length = json['length']?.toString();
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['page'] = page;
    data['length'] = length;
    data['Message'] = message;
    return data;
  }
}
