///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ViewAssetPerformanceModelDataLine {
/*
{
  "id": 73,
  "asset_performance_id": 4,
  "asset_code": "CCR035-0001",
  "asset_name": "CC01-Hitachi-Bagendang",
  "cabang_code": "CAB08",
  "periode": 1,
  "year": 2023,
  "total_data_pm": 0,
  "total_data_cm": 0,
  "total_data_pdm": 0,
  "total_data_em": 0,
  "total_data_ac": 0,
  "total_data_sd": 0,
  "total_data": 0,
  "pm": "0.0000",
  "cm": "0.0000",
  "pdm": "0.0000",
  "em": "0.0000",
  "ac": "0.0000",
  "sd": "0.0000",
  "activity": "0.0000",
  "availability_contract": "1.0000",
  "availability_real": "1.0000",
  "utilisasi": "0.0000",
  "realibility": "0.0000",
  "mtbf": "0.0000",
  "mttr": "0.0000",
  "jam_operasi": 0,
  "jam_available": 744,
  "company_id": 2
} 
*/

  String? id;
  String? assetPerformanceId;
  String? assetCode;
  String? assetName;
  String? cabangCode;
  String? periode;
  String? year;
  String? totalDataPm;
  String? totalDataCm;
  String? totalDataPdm;
  String? totalDataEm;
  String? totalDataAc;
  String? totalDataSd;
  String? totalData;
  String? pm;
  String? cm;
  String? pdm;
  String? em;
  String? ac;
  String? sd;
  String? activity;
  String? availabilityContract;
  String? availabilityReal;
  String? utilisasi;
  String? realibility;
  String? mtbf;
  String? mttr;
  String? jamOperasi;
  String? jamAvailable;
  String? companyId;

  ViewAssetPerformanceModelDataLine({
    this.id,
    this.assetPerformanceId,
    this.assetCode,
    this.assetName,
    this.cabangCode,
    this.periode,
    this.year,
    this.totalDataPm,
    this.totalDataCm,
    this.totalDataPdm,
    this.totalDataEm,
    this.totalDataAc,
    this.totalDataSd,
    this.totalData,
    this.pm,
    this.cm,
    this.pdm,
    this.em,
    this.ac,
    this.sd,
    this.activity,
    this.availabilityContract,
    this.availabilityReal,
    this.utilisasi,
    this.realibility,
    this.mtbf,
    this.mttr,
    this.jamOperasi,
    this.jamAvailable,
    this.companyId,
  });
  ViewAssetPerformanceModelDataLine.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    assetPerformanceId = json['asset_performance_id']?.toString();
    assetCode = json['asset_code']?.toString();
    assetName = json['asset_name']?.toString();
    cabangCode = json['cabang_code']?.toString();
    periode = json['periode']?.toString();
    year = json['year']?.toString();
    totalDataPm = json['total_data_pm']?.toString();
    totalDataCm = json['total_data_cm']?.toString();
    totalDataPdm = json['total_data_pdm']?.toString();
    totalDataEm = json['total_data_em']?.toString();
    totalDataAc = json['total_data_ac']?.toString();
    totalDataSd = json['total_data_sd']?.toString();
    totalData = json['total_data']?.toString();
    pm = json['pm']?.toString();
    cm = json['cm']?.toString();
    pdm = json['pdm']?.toString();
    em = json['em']?.toString();
    ac = json['ac']?.toString();
    sd = json['sd']?.toString();
    activity = json['activity']?.toString();
    availabilityContract = json['availability_contract']?.toString();
    availabilityReal = json['availability_real']?.toString();
    utilisasi = json['utilisasi']?.toString();
    realibility = json['realibility']?.toString();
    mtbf = json['mtbf']?.toString();
    mttr = json['mttr']?.toString();
    jamOperasi = json['jam_operasi']?.toString();
    jamAvailable = json['jam_available']?.toString();
    companyId = json['company_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['asset_performance_id'] = assetPerformanceId;
    data['asset_code'] = assetCode;
    data['asset_name'] = assetName;
    data['cabang_code'] = cabangCode;
    data['periode'] = periode;
    data['year'] = year;
    data['total_data_pm'] = totalDataPm;
    data['total_data_cm'] = totalDataCm;
    data['total_data_pdm'] = totalDataPdm;
    data['total_data_em'] = totalDataEm;
    data['total_data_ac'] = totalDataAc;
    data['total_data_sd'] = totalDataSd;
    data['total_data'] = totalData;
    data['pm'] = pm;
    data['cm'] = cm;
    data['pdm'] = pdm;
    data['em'] = em;
    data['ac'] = ac;
    data['sd'] = sd;
    data['activity'] = activity;
    data['availability_contract'] = availabilityContract;
    data['availability_real'] = availabilityReal;
    data['utilisasi'] = utilisasi;
    data['realibility'] = realibility;
    data['mtbf'] = mtbf;
    data['mttr'] = mttr;
    data['jam_operasi'] = jamOperasi;
    data['jam_available'] = jamAvailable;
    data['company_id'] = companyId;
    return data;
  }
}

class ViewAssetPerformanceModelDataAction {
/*
{
  "submit": true,
  "approve": false,
  "reject": false,
  "void": false,
  "print": false,
  "delete": true
} 
*/

  bool? submit;
  bool? approve;
  bool? reject;
  bool? theVoid;
  bool? print;
  bool? delete;

  ViewAssetPerformanceModelDataAction({
    this.submit,
    this.approve,
    this.reject,
    this.theVoid,
    this.print,
    this.delete,
  });
  ViewAssetPerformanceModelDataAction.fromJson(Map<String, dynamic> json) {
    submit = json['submit'];
    approve = json['approve'];
    reject = json['reject'];
    theVoid = json['void'];
    print = json['print'];
    delete = json['delete'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['submit'] = submit;
    data['approve'] = approve;
    data['reject'] = reject;
    data['void'] = theVoid;
    data['print'] = print;
    data['delete'] = delete;
    return data;
  }
}

class ViewAssetPerformanceModelData {
/*
{
  "id": 4,
  "doc_no": "000004/BA.AP/BIMOPS/I/2023",
  "date_doc": "2023-01-24",
  "doc_status": "Draft",
  "apv_level": 0,
  "year": 2023,
  "period_no": 1,
  "cabang_code": "CAB08",
  "created_at": 1674554906,
  "updated_at": null,
  "created_by": 37,
  "updated_by": null,
  "is_delete": 0,
  "company_id": 1,
  "action": {
    "submit": true,
    "approve": false,
    "reject": false,
    "void": false,
    "print": false,
    "delete": true
  },
  "line": [
    {
      "id": 73,
      "asset_performance_id": 4,
      "asset_code": "CCR035-0001",
      "asset_name": "CC01-Hitachi-Bagendang",
      "cabang_code": "CAB08",
      "periode": 1,
      "year": 2023,
      "total_data_pm": 0,
      "total_data_cm": 0,
      "total_data_pdm": 0,
      "total_data_em": 0,
      "total_data_ac": 0,
      "total_data_sd": 0,
      "total_data": 0,
      "pm": "0.0000",
      "cm": "0.0000",
      "pdm": "0.0000",
      "em": "0.0000",
      "ac": "0.0000",
      "sd": "0.0000",
      "activity": "0.0000",
      "availability_contract": "1.0000",
      "availability_real": "1.0000",
      "utilisasi": "0.0000",
      "realibility": "0.0000",
      "mtbf": "0.0000",
      "mttr": "0.0000",
      "jam_operasi": 0,
      "jam_available": 744,
      "company_id": 2
    }
  ]
} 
*/

  String? id;
  String? docNo;
  String? dateDoc;
  String? docStatus;
  String? apvLevel;
  String? year;
  String? periodNo;
  String? cabangCode;
  String? createdAt;
  String? updatedAt;
  String? createdBy;
  String? updatedBy;
  String? isDelete;
  String? companyId;
  ViewAssetPerformanceModelDataAction? action;
  List<ViewAssetPerformanceModelDataLine?>? line;

  ViewAssetPerformanceModelData({
    this.id,
    this.docNo,
    this.dateDoc,
    this.docStatus,
    this.apvLevel,
    this.year,
    this.periodNo,
    this.cabangCode,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
    this.isDelete,
    this.companyId,
    this.action,
    this.line,
  });
  ViewAssetPerformanceModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    docNo = json['doc_no']?.toString();
    dateDoc = json['date_doc']?.toString();
    docStatus = json['doc_status']?.toString();
    apvLevel = json['apv_level']?.toString();
    year = json['year']?.toString();
    periodNo = json['period_no']?.toString();
    cabangCode = json['cabang_code']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
    isDelete = json['is_delete']?.toString();
    companyId = json['company_id']?.toString();
    action = (json['action'] != null)
        ? ViewAssetPerformanceModelDataAction.fromJson(json['action'])
        : null;
    if (json['line'] != null) {
      final v = json['line'];
      final arr0 = <ViewAssetPerformanceModelDataLine>[];
      v.forEach((v) {
        arr0.add(ViewAssetPerformanceModelDataLine.fromJson(v));
      });
      line = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['doc_no'] = docNo;
    data['date_doc'] = dateDoc;
    data['doc_status'] = docStatus;
    data['apv_level'] = apvLevel;
    data['year'] = year;
    data['period_no'] = periodNo;
    data['cabang_code'] = cabangCode;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    data['is_delete'] = isDelete;
    data['company_id'] = companyId;
    if (action != null) {
      data['action'] = action!.toJson();
    }
    if (line != null) {
      final v = line;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['line'] = arr0;
    }
    return data;
  }
}

class ViewAssetPerformanceModel {
/*
{
  "success": true,
  "data": {
    "id": 4,
    "doc_no": "000004/BA.AP/BIMOPS/I/2023",
    "date_doc": "2023-01-24",
    "doc_status": "Draft",
    "apv_level": 0,
    "year": 2023,
    "period_no": 1,
    "cabang_code": "CAB08",
    "created_at": 1674554906,
    "updated_at": null,
    "created_by": 37,
    "updated_by": null,
    "is_delete": 0,
    "company_id": 1,
    "action": {
      "submit": true,
      "approve": false,
      "reject": false,
      "void": false,
      "print": false,
      "delete": true
    },
    "line": [
      {
        "id": 73,
        "asset_performance_id": 4,
        "asset_code": "CCR035-0001",
        "asset_name": "CC01-Hitachi-Bagendang",
        "cabang_code": "CAB08",
        "periode": 1,
        "year": 2023,
        "total_data_pm": 0,
        "total_data_cm": 0,
        "total_data_pdm": 0,
        "total_data_em": 0,
        "total_data_ac": 0,
        "total_data_sd": 0,
        "total_data": 0,
        "pm": "0.0000",
        "cm": "0.0000",
        "pdm": "0.0000",
        "em": "0.0000",
        "ac": "0.0000",
        "sd": "0.0000",
        "activity": "0.0000",
        "availability_contract": "1.0000",
        "availability_real": "1.0000",
        "utilisasi": "0.0000",
        "realibility": "0.0000",
        "mtbf": "0.0000",
        "mttr": "0.0000",
        "jam_operasi": 0,
        "jam_available": 744,
        "company_id": 2
      }
    ]
  },
  "message": "Sukses"
} 
*/

  bool? success;
  ViewAssetPerformanceModelData? data;
  String? message;

  ViewAssetPerformanceModel({
    this.success,
    this.data,
    this.message,
  });
  ViewAssetPerformanceModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? ViewAssetPerformanceModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
