///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BARealisasiModelData {
/*
{
  "pdf": "http://bimops-api.erdata.id/storage/pdf/report/QmltYXlpaTI3ODI3-realisasi.pdf"
}
*/

  String? pdf;

  BARealisasiModelData({
    this.pdf,
  });
  BARealisasiModelData.fromJson(Map<String, dynamic> json) {
    pdf = json['pdf']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pdf'] = pdf;
    return data;
  }
}

class BARealisasiModel {
/*
{
  "success": true,
  "data": {
    "pdf": "http://bimops-api.erdata.id/storage/pdf/report/QmltYXlpaTI3ODI3-realisasi.pdf"
  },
  "message": "Sukses"
}
*/

  bool? success;
  BARealisasiModelData? data;
  String? message;

  BARealisasiModel({
    this.success,
    this.data,
    this.message,
  });
  BARealisasiModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? BARealisasiModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
