///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ViewBAModelData {
/*
{
  "pdfPersetujuan": null,
  "pdfRealisasi": null
} 
*/

  String? pdfPersetujuan;
  String? pdfRealisasi;

  ViewBAModelData({
    this.pdfPersetujuan,
    this.pdfRealisasi,
  });
  ViewBAModelData.fromJson(Map<String, dynamic> json) {
    pdfPersetujuan = json['pdfPersetujuan']?.toString();
    pdfRealisasi = json['pdfRealisasi']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pdfPersetujuan'] = pdfPersetujuan;
    data['pdfRealisasi'] = pdfRealisasi;
    return data;
  }
}

class ViewBAModel {
/*
{
  "success": true,
  "data": {
    "pdfPersetujuan": null,
    "pdfRealisasi": null
  },
  "message": "Sukses"
} 
*/

  bool? success;
  ViewBAModelData? data;
  String? message;

  ViewBAModel({
    this.success,
    this.data,
    this.message,
  });
  ViewBAModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data =
        (json['data'] != null) ? ViewBAModelData.fromJson(json['data']) : null;
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['Message'] = message;
    return data;
  }
}
