///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ConfigModelData {
/*
{
  "Long": -8.160927807736735,
  "Lat": 112.44418490930914,
  "CoverageArea": 5,
  "CoverageAreaType": "kilometer"
} 
*/

  double? Long;
  double? Lat;
  double? CoverageArea;
  String? CoverageAreaType;

  ConfigModelData({
    this.Long,
    this.Lat,
    this.CoverageArea,
    this.CoverageAreaType,
  });
  ConfigModelData.fromJson(Map<String, dynamic> json) {
    Long = json['Long']?.toDouble();
    Lat = json['Lat']?.toDouble();
    CoverageArea = json['CoverageArea']?.toDouble();
    CoverageAreaType = json['CoverageAreaType']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Long'] = Long;
    data['Lat'] = Lat;
    data['CoverageArea'] = CoverageArea;
    data['CoverageAreaType'] = CoverageAreaType;
    return data;
  }
}

class ConfigModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "success get config location",
  "Data": {
    "Long": -8.160927807736735,
    "Lat": 112.44418490930914,
    "CoverageArea": 5,
    "CoverageAreaType": "kilometer"
  }
} 
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  ConfigModelData? Data;

  ConfigModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
  });
  ConfigModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    Data =
        (json['Data'] != null) ? ConfigModelData.fromJson(json['Data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
