///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FirebaseTokenModelData {
/*
{
  "token": "31|Hxog5vrunfYQ2jyAHGIj9wc0uh6TfFHPmwtJb5fi",
  "id": "MQ==",
  "username": "adminatria",
  "company_id": 1,
  "company_name": "PT. Berkah Industri Mesin Angkat",
  "cabang_id": 42,
  "cabang_code": "CAB28",
  "cabang_name": "PRIMA MULTI TERMINAL"
} 
*/

  String? token;
  String? id;
  String? username;
  int? companyId;
  String? companyName;
  int? cabangId;
  String? cabangCode;
  String? cabangName;

  FirebaseTokenModelData({
    this.token,
    this.id,
    this.username,
    this.companyId,
    this.companyName,
    this.cabangId,
    this.cabangCode,
    this.cabangName,
  });
  FirebaseTokenModelData.fromJson(Map<String, dynamic> json) {
    token = json['token']?.toString();
    id = json['id']?.toString();
    username = json['username']?.toString();
    companyId = json['company_id']?.toInt();
    companyName = json['company_name']?.toString();
    cabangId = json['cabang_id']?.toInt();
    cabangCode = json['cabang_code']?.toString();
    cabangName = json['cabang_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['token'] = token;
    data['id'] = id;
    data['username'] = username;
    data['company_id'] = companyId;
    data['company_name'] = companyName;
    data['cabang_id'] = cabangId;
    data['cabang_code'] = cabangCode;
    data['cabang_name'] = cabangName;
    return data;
  }
}

class FirebaseTokenModel {
/*
{
  "success": true,
  "data": {
    "token": "31|Hxog5vrunfYQ2jyAHGIj9wc0uh6TfFH  PmwtJb5fi",
    "id": "MQ==",
    "username": "adminatria",
    "company_id": 1,
    "company_name": "PT. Berkah Industri Mesin Angkat",
    "cabang_id": 42,
    "cabang_code": "CAB28",
    "cabang_name": "PRIMA MULTI TERMINAL"
  },
  "message": "Login Sukses"
} 
*/

  bool? success;
  FirebaseTokenModelData? data;
  String? message;

  FirebaseTokenModel({
    this.success,
    this.data,
    this.message,
  });
  FirebaseTokenModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? FirebaseTokenModelData.fromJson(json['data'])
        : null;
    message = json['Message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['Message'] = message;
    return data;
  }
}
