///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelData {
/*
{
  "Name": "aditya fullname",
  "Division": "Engineer",
  "Token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOjE3MTg0OTUxOTIsIklkIjoiMDFKMDZEU0c4WlRWWlRCVzVOWjg3WFJWTVgifQ.vook50_afNFiP55zB8nDgL-H9ityc9tWYAh55uGmK20SuTF4sMHNjKoF1uhnioyMSC6u49EVpgr4GJh3Hknouhalr_--xPY1KcSypnRtaSq-iiVccWm8GqPnNm4Na2YNhDZxZvXi4C_JSS2GJq6zBFOwWjAf9kMnYU6BTVCuTho",
  "RefreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOjE3MTg1MzExOTIsIklkIjoiMDFKMDZEU0c4WlRWWlRCVzVOWjg3WFJWTVgifQ.SEoXJHVvUGQPVs2p-tL8m3wpGbNmyyS4qHN7pgTSHcdR8qZOCigdhUolBX9rJIqMh5_rNBKRf79w0WL9uxJnYL19gII6Yjdkshnm2NH5iu4tGAcZeKk9ge1qJ4oBBfTFBrgH7n0UqNmqeZ004I3kWUFVwhH_LMT70wEJjv2Zs6U"
} 
*/

  String? Name;
  String? Division;
  String? Token;
  String? RefreshToken;

  LoginModelData({
    this.Name,
    this.Division,
    this.Token,
    this.RefreshToken,
  });
  LoginModelData.fromJson(Map<String, dynamic> json) {
    Name = json['Name']?.toString();
    Division = json['Division']?.toString();
    Token = json['Token']?.toString();
    RefreshToken = json['RefreshToken']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Name'] = Name;
    data['Division'] = Division;
    data['Token'] = Token;
    data['RefreshToken'] = RefreshToken;
    return data;
  }
}

class LoginModel {
/*
{
  "Success": true,
  "StatusCode": 200,
  "Message": "berhasil login",
  "Data": {
    "Name": "aditya fullname",
    "Division": "Engineer",
    "Token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOjE3MTg0OTUxOTIsIklkIjoiMDFKMDZEU0c4WlRWWlRCVzVOWjg3WFJWTVgifQ.vook50_afNFiP55zB8nDgL-H9ityc9tWYAh55uGmK20SuTF4sMHNjKoF1uhnioyMSC6u49EVpgr4GJh3Hknouhalr_--xPY1KcSypnRtaSq-iiVccWm8GqPnNm4Na2YNhDZxZvXi4C_JSS2GJq6zBFOwWjAf9kMnYU6BTVCuTho",
    "RefreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOjE3MTg1MzExOTIsIklkIjoiMDFKMDZEU0c4WlRWWlRCVzVOWjg3WFJWTVgifQ.SEoXJHVvUGQPVs2p-tL8m3wpGbNmyyS4qHN7pgTSHcdR8qZOCigdhUolBX9rJIqMh5_rNBKRf79w0WL9uxJnYL19gII6Yjdkshnm2NH5iu4tGAcZeKk9ge1qJ4oBBfTFBrgH7n0UqNmqeZ004I3kWUFVwhH_LMT70wEJjv2Zs6U"
  }
} 
*/

  bool? Success;
  int? StatusCode;
  String? Message;
  LoginModelData? Data;

  LoginModel({
    this.Success,
    this.StatusCode,
    this.Message,
    this.Data,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    Success = json['Success'];
    StatusCode = json['StatusCode']?.toInt();
    Message = json['Message']?.toString();
    Data =
        (json['Data'] != null) ? LoginModelData.fromJson(json['Data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Success'] = Success;
    data['StatusCode'] = StatusCode;
    data['Message'] = Message;
    if (Data != null) {
      data['Data'] = Data!.toJson();
    }
    return data;
  }
}
