///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelData {
/*
{
  "token": "111|0xH9t1y1csW61ZmjQyZNddrBMEqUdubit6ymXV8K",
  "id": "OA==",
  "username": "19950601831",
  "name": "Sahala Tua Parulian Hutagalung",
  "jabatan": "Planner",
  "company_id": 1,
  "company_name": "PT. Berkah Industri Mesin Angkat",
  "cabang_id": 34,
  "cabang_code": "CAB06",
  "cabang_name": "PELABUHAN TANJUNG PERAK (JAMRUD)"
} 
*/

  String? token;
  String? id;
  String? username;
  String? name;
  String? jabatan;
  int? companyId;
  String? companyName;
  int? cabangId;
  String? cabangCode;
  String? cabangName;

  LoginModelData({
    this.token,
    this.id,
    this.username,
    this.name,
    this.jabatan,
    this.companyId,
    this.companyName,
    this.cabangId,
    this.cabangCode,
    this.cabangName,
  });
  LoginModelData.fromJson(Map<String, dynamic> json) {
    token = json['token']?.toString();
    id = json['id']?.toString();
    username = json['username']?.toString();
    name = json['name']?.toString();
    jabatan = json['jabatan']?.toString();
    companyId = json['company_id']?.toInt();
    companyName = json['company_name']?.toString();
    cabangId = json['cabang_id']?.toInt();
    cabangCode = json['cabang_code']?.toString();
    cabangName = json['cabang_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['token'] = token;
    data['id'] = id;
    data['username'] = username;
    data['name'] = name;
    data['jabatan'] = jabatan;
    data['company_id'] = companyId;
    data['company_name'] = companyName;
    data['cabang_id'] = cabangId;
    data['cabang_code'] = cabangCode;
    data['cabang_name'] = cabangName;
    return data;
  }
}

class LoginModel {
/*
{
  "success": true,
  "data": {
    "token": "111|0xH9t1y1csW61ZmjQyZNddrBMEqUdubit6ymXV8K",
    "id": "OA==",
    "username": "19950601831",
    "name": "Sahala Tua Parulian Hutagalung",
    "jabatan": "Planner",
    "company_id": 1,
    "company_name": "PT. Berkah Industri Mesin Angkat",
    "cabang_id": 34,
    "cabang_code": "CAB06",
    "cabang_name": "PELABUHAN TANJUNG PERAK (JAMRUD)"
  },
  "message": "Login Sukses"
} 
*/

  bool? success;
  LoginModelData? data;
  String? message;

  LoginModel({
    this.success,
    this.data,
    this.message,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data =
        (json['data'] != null) ? LoginModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}

class ForgotArguments {
  final String token;
  final String email;

  ForgotArguments(this.token, this.email);
}
